### ISSUE TITLE
DPI awarness

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#103]
So I have looked into MinGW and MSDN and it turns out that most of the functions I had problems with are actually supported.

The thing is:

- I just need to add defines which specify target minimum Windows version as specified [here](http://mingw.org/wiki/Use_more_recent_defined_functions), otherwise their declarations are getting ifdefed out for obvious reasons.
- At least 1 of the functions (eg [GetDpiForWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow)) used in elements is only available since Windows 10 version 1607. Are you sure you want to have that high requirements? I would like to run my project on Win 7 and 8 too. How about an extra build flag?

**Comment by djowel** [comment]
> * At least 1 of the functions (eg [GetDpiForWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow)) used in elements is only available since Windows 10 version 1607. Are you sure you want to have that high requirements? I would like to run my project on Win 7 and 8 too. How about an extra build flag?

Absolutely! We don't need stinkin' old OSes ;-) It's 2020!

Seriously, it's OK as long as it is able to have the same behavior using an alternative API, it's fine :-)

**Comment by Xeverous** [comment]
There is no alternative API. Programs on older Windows versions are just not aware and on never versions, if they do not declare to be aware they will always get the value 96 from the API.

Some time ago I noticed "example scaling issue" with Notepad++ in the office (to which I currently do not go because corona) and I'm not sure if there is any solution to this problem: Programs get different scaling/DPI depending on the moitor they are on. Either is fine. But if I stretch the program's window to occupy 2 monitors (I and some colleagues use it for some tasks) there is no way to get the same image if settings of DPI/resolution/text are different. The program can not adapt to 2 minots at once in one window. People in the project just swap monitors with others to get a pair with the same properties.

**Comment by Xeverous** [comment]
Another thing:

https://github.com/cycfi/elements/blob/773b60b6fd759a3687f9d654d92555d953ef9f7c/lib/host/windows/app.cpp#L68-L73

In `app::app` you use `PROCESS_SYSTEM_DPI_AWARE` but elsewhere use `GetDpiForWindow`. Shouldn't you use `PROCESS_PER_MONITOR_DPI_AWARE`?

**Comment by djowel** [comment]
> In `app::app` you use `PROCESS_SYSTEM_DPI_AWARE` but elsewhere use `GetDpiForWindow`. Shouldn't you use `PROCESS_PER_MONITOR_DPI_AWARE`?

Very good point! yes, PROCESS_PER_MONITOR_DPI_AWARE is better.

**Comment by Xeverous** [comment]
While going over the code in order to find what is required to be changed to support Win7, I found 2 other things in this function:

https://github.com/cycfi/elements/blob/773b60b6fd759a3687f9d654d92555d953ef9f7c/lib/host/windows/app.cpp#L94-L99

1) `path` is leaked. The returned `LPWSTR` needs to be freed with `CoTaskMemFree`. I will fix this together with #44 where I add some Windows-specific RAII wrappers.

2) The obtained known folder is not the right one.

From https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid on `FOLDERID_AppDataProgramData`:

> This FOLDERID is used internally by .NET applications to enable cross-platform app functionality. It is not intended to be used directly from an application.

Given the name of the function, you probably want one of these:

- `FOLDERID_LocalAppData` (`%LOCALAPPDATA%`, `%USERPROFILE%\AppData\Local`, per-user
- `FOLDERID_ProgramData` (`%ALLUSERSPROFILE%`, `%ProgramData%`, `%SystemDrive%\ProgramData`), fixed system-wide

**Comment by djowel** [comment]
Wonderful! That will be very welcome. I spend less time on Windows (my main dev computer is MacOS), and when I do, most of the time, I admit there's a fair amount of hacking :-) It would be very welcome if you can straighten things up!

**Comment by Xeverous** [comment]
See #104

I added new header - there will be much more things in it after #44

**Comment by Xeverous** [comment]
> I spend less time on Windows [..] most of the time, I admit there's a fair amount of hacking

Nothing new to me. Windows has many API problems and the documentation doesn't help it either. It's easier to RAII-wrap POSIX C interface and get anything done there than to wrap COM becuse on Windows everything is so coupled. IIRC the story behind completely ground-up-designed WinRT actually-ISO-C++ API is that someone in the company was shown that is actually possible without any C++/CX forks, compiler extensions or tons of macros.

**Comment by Xeverous** [comment]
Thanks for the merge, now I can rebase my implementation of #44 onto it.
