### ISSUE TITLE
Crash on startup on Linux

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#109]
I don't get what's the problem:

```
$ ./examples/basic_sliders_and_knobs/BasicSlidersAndKnobs

(process:21452): Gtk-CRITICAL **: 01:45:02.437: gtk_application_new: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed

(process:21452): GLib-GObject-WARNING **: 01:45:02.438: invalid (NULL) pointer instance

(process:21452): GLib-GObject-CRITICAL **: 01:45:02.438: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:21452): GLib-GIO-CRITICAL **: 01:45:02.447: g_application_run: assertion 'G_IS_APPLICATION (application)' failed

(process:21452): GLib-GObject-CRITICAL **: 01:45:02.447: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(process:21452): GLib-GObject-CRITICAL **: 01:45:02.447: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

This is my first time launching elements on Linux Mint 19.3. There are some entries on the web about these asserts but people get a window there anyway despite the log. I will need to check what's going on in the code and where to debug things. Got any information that could help me? Have you experienced such problem before?

**Comment by Xeverous** [comment]
Ok, I got it.

https://github.com/cycfi/elements/blob/e891f86be6c375e0f60526fb3ffee57127dd2c65/lib/host/linux/app.cpp#L36-L43

IMO this is bad code. Failing to load (necessary?) configuration file in release should not result in UB.

**Comment by Xeverous** [comment]
Error handling is one thing, but I would also like to discuss the configuration itself (perhaps in a separate issue). I don't really like current state: we need to have a separate file, we drag in a separate library just to load this file and both of them are only to provide some sample strings for window construction.

**Comment by djowel** [comment]
> just to load this file

That is incorrect. There are other planned uses of it. And that library, which used to be in infra, is a small header only library. Please avoid sweeping statements without really understanding the reasons why.

**Comment by djowel** [comment]
> Error handling is one thing

What happened? Did you not have the config file? Wrong paths?

**Comment by djowel** [comment]
> > Error handling is one thing
> 
> What happened? Did you not have the config file? Wrong paths?

Anyway, you are right. I'd probably rewrite this by throwing a std::runtime_error instead.

**Comment by Xeverous** [comment]
> Did you not have the config file? Wrong paths?

Yes, no file was present but read further...

> Anyway, you are right. I'd probably rewrite this by throwing a std::runtime_error instead.

Yes, anything is better than UB when file loading fails.

> Cmake should have installed that (config file) for you. Why is it missing? I'd like to know what happened.

I checked and CMake did everything correctly. The thing is, I launched the executable from the command line with a relative path, so the program had a different working directory than the place of the executable. This caused `config.json` to be searched in a different directory.

I tested and exactly the same issue is present on Windows when the working directory does not match executable's directory.

**Comment by sehe** [comment]
I'm running into the same issue (when building my first standalone copy of "empty", it works when in-tree, altough there too I noted the need to cd into the dir with the binary).

However, I have copied the entire `resources` dir (including the config.json` as well as the config file separately to no avail. Getting the exact same message. It's unnecessarily hard to pinpoint with a debugger (`catch throw` doesn't do anything because execution just continues). I imagine this will be a stumbling block for more first time users

**Comment by sehe** [comment]
Never mind. Figured it out. I had copied the config.json from the src "resources" directory. Apparently there's some CMake magic to add essential¹ information to it.

(¹ ? doesn't look overly essential but eh, maybe I'll get that later)

**Comment by djowel** [comment]
> Never mind. Figured it out. I had copied the config.json from the src "resources" directory. Apparently there's some CMake magic to add essential¹ information to it.
> 
> (¹ ? doesn't look overly essential but eh, maybe I'll get that later)

Suggestions on making this less error prone, easier and more intuitive very welcome.

**Comment by djowel** [comment]
> > Never mind. Figured it out. I had copied the config.json from the src "resources" directory. Apparently there's some CMake magic to add essential¹ information to it.
> > (¹ ? doesn't look overly essential but eh, maybe I'll get that later)
> 
> Suggestions on making this less error prone, easier and more intuitive very welcome.

A PR even more welcome! :-)

**Comment by jpcima** [comment]
The PR #152 fixes this problem, on Linux only.
The same path resolution logic could be applied for Windows too. (as it was mentioned above)

**Comment by djowel** [comment]
Before we proceed, see https://github.com/cycfi/elements/issues/158.

**Comment by djowel** [comment]
Go check out the no-boost-deps branch. The branch is now free from all Boost dependencies:

https://github.com/cycfi/elements/tree/no-boost-deps

JSON dependency is removed
ASIO is now a standalone submodule in elements

There's an API change, obviously (see discussion: https://github.com/cycfi/elements/issues/158). I'll announce that, perhaps in a WIKI announcement page that links to the top readme.

**Comment by djowel** [comment]
This is already merged to develop and master. Closing this now...
