### ISSUE TITLE
CMake assumes MSVC compiler on Windows

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#11]
The following things break using GCC on Windows:

___

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L23-L34

It's recommended to avoid touching internal CMake compiler/linker flags as they are very fragile and may prevent other (modern) CMake features from working.

The bigger problem is that **these flags are global and any project messing with them will impact and can break any other project which uses this library**.

I'd recommend to use generator expressions instead and limit their scope to the target:

```cmake
target_compile_options(libelements PRIVATE
    $<$<CXX_COMPILER_ID:GNU>:-Wno-missing-braces -Wno-comma -ftemplate-backtrace-limit=0>
    $<$<CXX_COMPILER_ID:Clang>:-Wno-missing-braces -Wno-comma -ftemplate-backtrace-limit=0>
    $<$<CXX_COMPILER_ID:MSVC>:/wd4244 /wd4305 /wd4996 /wd4267 /wd4018>
)

```

___

There are multiple ifs which change recipe behaviour on Windows, but they all are MSVC-specific.

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L39-L49

Such code fragments should use `if(MSVC)` at least, or go with target properties approach.

___

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L178-L182

Such lines should use preferred names instead of variables (that is, `Boost::filesystem` for each compiled library and/or `Boost::boost` for all header-only libraries)

See https://cliutils.gitlab.io/modern-cmake/chapters/packages/Boost.html

___

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/CMakeMain.txt#L93-L98

This is currently my biggest offeder. It directly breaks GCC on Windows by disabling modern CMake features, resulting in `g++ -03 -DNDEBUG` compiler flags only, resulting in fatal error of no input files. It probably also poisons any other project (`CMAKE_*` are global flags) but I haven't tried including Elements in any of my projects yet.

**Comment by djowel** [comment]
PRs very welcome!

**Comment by Xeverous** [comment]
This will be a complex PR - need to do multiple things at once as currently a lot of cmake code is using global state which allows much more unordered commands.

___

Some questions:

Is this needed at all? It uses `CMAKE_SYSTEM_NAME` which [CMake explicitly states is not documented](https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/How-To-Write-Platform-Checks#cmake-system). I would like to avoid as much platform-specific CMake code as possible and replace conditions with WIN32, UNIX, APPLE variables which are predefined by CMake.

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L14-L20

___

What's the purpose of this?

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L153-L156

I would rather name the project `elements` and rely on default behavior. CMake already adds the `lib` prefix to dynamic and static library objects.

___

`target_include_directories` is unneded if the library is already exposed as a CMake target - contrary to the name `target_link_libraries` adds linker, compiler defines and compiler include flags. It is definitely in the case of boost, but I'm not sure if any other dependencies of Elements have the target defined - if not this should be reported as a bug to each dependency as said by Daniel Pfeifer on his CppCon talk.


___

What's the point of this?

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L206

___

It is recomemnded to avoid source file globbing. IIRC there is some issue with supporting sources update and the fact that multiple target build systems do not support globbing so CMake can't reflect it well. Would you like to list all files explicitly?

___

What's the reason behind separate finding logic for Cairo and Freetype on Windows?

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L36-L64

___

What's the reason behind this code?

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L90-L101

Boost already works by finding the package and linking to it through `target_link_libraries`.

**Comment by djowel** [comment]
> Is this needed at all? It uses `CMAKE_SYSTEM_NAME` which [CMake explicitly states is not documented](https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/How-To-Write-Platform-Checks#cmake-system). I would like to avoid as much platform-specific CMake code as possible and replace conditions with WIN32, UNIX, APPLE variables which are predefined by CMake.

Feel free to simplify.

**Comment by djowel** [comment]
> I would rather name the project `elements` and rely on default behavior. CMake already adds the `lib` prefix to dynamic and static library objects.

Same here. Feel free to simplify as long as all platforms build as expected.

**Comment by djowel** [comment]
> What's the reason behind separate finding logic for Cairo and Freetype on Windows?

Windows sucks and this is what I find that works well. If you can get rid of it, sure! But you have to make sure that everything builds without any problems on Windows and VS.

**Comment by djowel** [comment]
> Boost already works by finding the package and linking to it through `target_link_libraries`.

It's what we use in-house. Again if you can simplify this, as long as everything builds without issues on all platforms, I'm fine with it.

**Comment by djowel** [comment]
> What's the point of this?
> 
> https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L206

You mean "-fobjc-arc" ?

**Comment by Xeverous** [comment]
> Windows sucks and this is what I find that works well. If you can get rid of it, sure! But you have to make sure that everything builds without any problems on Windows and VS.

Ok, I will try and in case of failure I will just change `if(WIN32)` to `if(MSVC)`.

> You mean "-fobjc-arc" ?

Yes. This looks like an Obj-C flag. Why is it needed?

**Comment by djowel** [comment]
> > You mean "-fobjc-arc" ?
> 
> Yes. This looks like an Obj-C flag. Why is it needed?

Automatic reference counting. Please don't mess with it. And again, whatever you do, make sure everything builds and runs on all platforms. cmake is often a delicate balance and it's easy to mess things up.

**Comment by Xeverous** [comment]
I can't test the change on Mac OS, I will mostly:

- Edit currently MSVC-specific behavior to use MSVC variable instead of WIN32 (this will open the way for other compilers on Windows).
- Edit global function to targets-specific functions. **Do any of the currently added compiler/linker flags need to be applied to descendant projects? - I don't know much about ref counting on Mac OS** (this is the difference between PUBLIC and PRIVATE target properties)
- remove type-unsafe CMake code (CMAKE_SYSTEM_NAME string comparison) and use predefined CMake variables instead
- remove globbing
- less variable-based code and more target-based code (targets automatically apply linker,compiler defines, compiler includes and more)

Current Mac OS-specific and MSVC-specific behaviour will be preserved.

**Comment by Xeverous** [comment]
Which of these dependencies are private and which public?

https://github.com/cycfi/elements/blob/9e73461a0520bd13c74969e35a3a5939dc3618d0/lib/CMakeLists.txt#L198-L232

**Comment by djowel** [comment]
> Which of these dependencies are private and which public?

I am not sure if I want to make any of those private.

**Comment by djowel** [comment]
> * Edit global function to targets-specific functions. **Do any of the currently added compiler/linker flags need to be applied to descendant projects? - I don't know much about ref counting on Mac OS** (this is the difference between PUBLIC and PRIVATE target properties)

Yes.

**Comment by djowel** [comment]
> I can't test the change on Mac OS, I will mostly:

In that case, we should probably make a separate target branch for this so I can test without disrupting the develop branch.

**Comment by Xeverous** [comment]
> I am not sure if I want to make any of those private.

Are you sure? If a dependency/compile flag/compile define/any other target property is `PUBLIC` CMake  will recursively apply it to all derived projects. Compiler flags are usually an implementation detail (except some important flags like `_UNICODE` on Windows).

If any of the dependencies is exposed in public API, then it must be public. But if it is an implementation detail (eg the choice of specific libraries to implement widgets like cairo, GTK or Freetype) it would be better left as private unless you are sure it is not going to change and you would like to explicitly allow any elements-derived project to also use these libraries.

___

I have also found that the repository contains Cairo and Freetype headers, but not their sources. You have commited compiled binaries (which IMO should be always avoided).

I don't want to break anything with this PR so I will preserve this behaviour but change it from being Windows-specific to MSVC-specific. MSVC is only used on Windows and this will open the way for GCC and Clang on Windows, with the same approach as on other systems.

I know CMake requires more work to work on Windows - especially for projects which do not have their own CMake scripts (like cairo). I will leave cairo as it is now, but will try later to use IMPORTED target so cairo will look like ordinary CMake-based project and any derived project using `target_link_libraries(... PUBLIC/PRIVATE cairo)` will automatically get all the compiler/linker flags. But this will be a separate PR, because the one for this issue is already going to be quite big.

___

Some of the CMake code will be reordered, because modern CMake (target-based recipes) have some restrictions (mostly for safety and better implementation).

___

Boost has multiple package-search affecting options (eg `Boost_USE_STATIC_LIBS`) and not everyone might have the specific configuration - these will be exposed as elements options to allows users to use any of static/dynamic MT/non-MT static/dynamic runtime combination. I will preserve current defaults.

**Comment by djowel** [comment]
> Are you sure? If a dependency/compile flag/compile define/any other target property is `PUBLIC` CMake will recursively apply it to all derived projects. Compiler flags are usually an implementation detail (except some important flags like `_UNICODE` on Windows).

Yeah, gave it a second thought. I think Cairo, Freetype and Boost should be private (is should GTK). Cairo in particular should not be exposed and depended on because I want to be able to switch to something else later.

**Comment by djowel** [comment]
> I have also found that the repository contains Cairo and Freetype headers, but not their sources. You have commited compiled binaries (which IMO should be always avoided).

Again, windows library mess. If you find a workable solution, feel free. I just wanted to have something that works quickly, initially. The other platforms do not do this. Again, make sure it builds and works on VS.

**Comment by Xeverous** [comment]
Ok, now I understand why you did what you did. Downloaded cairo and saw 40 000 line shell configure script. Looks like a really fun thing to build ... which only provides shell based scripts and some makefiles. And the implementation has a ton of defines and build-generation options...

So, what is the cairo configuration needed by elements?

**Comment by djowel** [comment]
> Ok, now I understand why you did what you did. Downloaded cairo and saw 40 000 line shell configure script. Looks like a really fun thing to build ... which only provides shell based scripts and some makefiles. And the implementation has a ton of defines and build-generation options...
> 
> So, what is the cairo configuration needed by elements?

Here's what I have in my notes:

"A Standalone Cairo DLL for Windows"
https://preshing.com/20170529/heres-a-standalone-cairo-dll-for-windows/
https://github.com/preshing/cairo-windows/releases

HTH

**Comment by Xeverous** [comment]
Ok so it looks like the linked builds are using default cairo configuration only with Win32 text render implementation replaced by Freetype library (this is likely not affecting the public API).

After some investigation, it turns out cairo and it's dependencies (after building and installation) create `.pc` files in order to be "managed" using `pkg-config` program **which has built-in support in CMake**. This is great news, because all of the cairo, Freetype, pixman can be build using their shell scripts and very easily discovered by CMake.

However, there is a quite annoying thing:

- the default installation paths on Windows are using `C:/Program Files/` or ``C:/Program Files (x86)/``
- `pkg-config` just can't deal with paths that contain spaces (it always splits them into multiple paths) - I'm pretty sure this is a bug:

```
$ pkg-config.exe --validate "/c/Program Files (x86)/libpng/lib/pkgconfig/libpng.pc"
Package C:/Program was not found in the pkg-config search path.
Perhaps you should add the directory containing `C:/Program.pc'
to the PKG_CONFIG_PATH environment variable
No package 'C:/Program' found
Package Files was not found in the pkg-config search path.
Perhaps you should add the directory containing `Files.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Files' found
Failed to open '(x86)/libpng/lib/pkgconfig/libpng.pc': No such file or directory
No package '(x86)/libpng/lib/pkgconfig/libpng.pc' found
```

Some of the dependencies are alredy searched through pkg-config, I will add flags to do make it possible for others too.

I will issue a PR when everything builds seamlessly for me.

**Comment by djowel** [comment]
> I will issue a PR when everything builds seamlessly for me.

That will be wonderful!

**Comment by Xeverous** [comment]
Looks like building any library with autoconf is much harder than expected:

```
$ make
/usr/bin/sh: -c: line 0: syntax error near unexpected token `('
/usr/bin/sh: -c: line 0: `test -f config.h || C:/Program Files (x86)/GnuWin32/bin/make  stamp-h1'
make: *** [config.h] Error 1
```

From autoconf documentation:

```
Autoconf uses shell-script processing extensively, so the file names that it processes should not contain characters that are special to the shell. Special characters include space, tab, newline, NUL, and the following:

     " # $ & ' ( ) * ; < = > ? [ \ ` |
```

Most of the tools/libraries/scipts install in `C:/Program Files` or `C:/Program Files (x86)`. I don't even know how much stuff is broken at this point. Now I need a really powerful workaround.

**Comment by Xeverous** [comment]
I'm back with some good news:

- Elements uses fontconfig library. This is nowhere stated, not even in CMake files.
- Cairo's has the disgusting thing that it has different API depending on it's build configuration - essentially implementation leaks to the public interface. It supports both Win32 and Freetype font backends, but they have even separate includes and you can not write backend-generic code out-of-the-box. That was a pain to discover.
- I managed to build all dependencies. Autotools scripts were a huge pain to make them work (had to reinstall all Windows tools to a different path (no spaces) and then workaround multiple include/linker/ifdef specification bugs - all well known by various other libraries using cairo/freetype/fontconfig - none fixed in years)
- I have obtained newer GCC 9.2.1 which does support shell scaling API

I'm going back to work on the CMake recipe, got some questions:

- What is the purpose of `ELEMENTS_CLASS_PREFIX` in CMake script? It is not given any value.
- What is the purpose of `-Wno-comma`? There is no such flag in current GCC or Clang
- FYI: There are tons of `-Wunused-parameter` warnings. Want to disable this warning or fix the code (in other PR ofc)?
- FYI: There are some "comparison of integers of different signess" warnings. Same question as above.

**Comment by djowel** [comment]
> I'm back with some good news:
> 
[snips]

Wonderful news!

> I'm going back to work on the CMake recipe, got some questions:
> 
> * What is the purpose of `ELEMENTS_CLASS_PREFIX` in CMake script? It is not given any value.

When writing plugins (there's a QPLug library in the making for that), AU, being written in objective-C, requires prefixes in lieu of namespaces (Obj-C has no namespaces). Without it, there can be name clashes when the element's view is exposed as a DLL by multiple plugins. Silly, I know, but that is reality.

> * What is the purpose of `-Wno-comma`? There is no such flag in current GCC or Clang

IDK, to be honest ;-)

> * FYI: There are tons of `-Wunused-parameter` warnings. Want to disable this warning or fix the code (in other PR ofc)?

Fix the code, ideally. E.g. foo(int /*unused*/)

> * FYI: There are some "comparison of integers of different signess" warnings. Same question as above.

Gah, I hate that one! Suggestions welcome!

**Comment by Xeverous** [comment]
Sorry for long time to update, I'm currently working on a different project (it will likely depend on elements though) and missed the reply on this. I have planned a large time span for elements and related projects starting at the end of January - might be earlier if I get some spare time in work. Would really like to use elements for the GUI.

I have checked Conan but there is no cairo package and some if its dependencies are not present either. Now I really get why you bundled cairo into the repository. I have a big file of notes (>100 lines) describing which libraries need which options to work with elements and how to workaround their build problems (eg Freetype tries to build platform/API-specific tests for platform/API you did not enabled and it's impossible to disable building tests without hacks). Might add these notes to the building description and/or forward them to Conan devs who said are interested in any build recipe help.

I have the CMake script working, that is, it builds elements correctly on Windows but I need to carefully map all of existing functionality to modern CMake not to break existing builds. The current CMake file structure looks like: defs/paths/flags for A, defs/paths/flags for B, ... for C... while the modern CMake encourages defs for A/B/C, flags for A/B/C, ... for A/B/C.

I have found that `-Wno-comma` disables `-Wcomma` warning which *warns about possible misuse of the comma operator*:

- https://clang.llvm.org/docs/DiagnosticsReference.html#wcomma
- https://reviews.llvm.org/D3976

I will remove `-Wno-comma` then - if some new warning pops up it very likely will be an actual bug/code smell.

Regarding comparison of different signedness - the standard (C++20) way will be `.ssize()` but for now we can do these things:

- use ranged for if possible
- (preferred) change the type of `i` to `std::size_t` (1 word change usually, more work if the loop is backwards as `i >= 0` is never `false` for unsigned types)
- cast `.size()` result to the type of `i` (a bit verbose)
- change index to iterators

**Comment by djowel** [comment]
Sounds good, @Xeverous!

**Comment by Xeverous** [comment]
Good news: it builds for me with examples (and with some warnings). I will cleanup the commented code and make a PR (probably 1-2 days). The commit will likely still need some changes, as I tested only the Windows build.

A lot of stuff has been modernized, eg the use of global `CMAKE_CXX_FLAGS`  replaced with `target_compile_options` and many dependency-related code reduced to only `target_link_libraries()` which automatically adds include flags, required compiler options etc. This does wonders for dependency management (all `PUBLIC` dependencies are recursively passed to descendant projects - a project linking to elements needs to only declare it depends on elements) but works only if there are proper targets (that is, `add_library`/`add_executable` etc, no variables). Since CMake has built-in support for making such pretty targets from pkg-config, dependencies are now discovered using `pkg_check_modules(... REQUIRED IMPORTED_TARGET ...)`. Everything should work seamlessly as long as it provides a pc file for pkg-config or can be found by default `find_package()`.

Sadly, cairo had to be made `PUBLIC` because at least one of element's public headers includes `<cairo.h>`.

MSVC-specific and MACOS-specific behavior has been preserved.

**Comment by djowel** [comment]
Wonderful news! 

> MSVC-specific and MACOS-specific behavior has been preserved.

Let's fix that then!

**Comment by Xeverous** [comment]
#13 has arrived!

Please tell me how much stuff I have broken :)

**Comment by Xeverous** [comment]
I think that you can change this statement in the post about the library:

> [...] the Windows and Linux ports are currently in an unusable state due to recent low-level refactoring.

I successfully build all examples with GCC on Windows (using refactored CMake lists). In one example's dropdown there is a problem that sometimes multiple options are highlighted (not only the howevered one), there could be some bug (not sure if in the library or in the example's code). Besides this everything works.

___

Also, for this:

> I'll be targeting a different branch for this, so we can have it stabilize smoothly.

What's your definition of "stabilized"? I have no more CMake changes planned (maybe fix warnings if they appear). Still haven't verified Linux build though, but I need to do some git maneuvering on Windows to compile and submit PRs: apply CMake patches, apply DPI scaling workaround patch, change flags or apply other patches to reduce warnings bloat etc.

**Comment by djowel** [comment]
> I think that you can change this statement in the post about the library:
> 
> > [...] the Windows and Linux ports are currently in an unusable state due to recent low-level refactoring.
> 
> I successfully build all examples with GCC on Windows (using refactored CMake lists). In one example's dropdown there is a problem that sometimes multiple options are highlighted (not only the howevered one), there could be some bug (not sure if in the library or in the example's code). Besides this everything works.

Good idea. Hmmm... I'll go check the menu highlight bug.

> Also, for this:
> 
> > I'll be targeting a different branch for this, so we can have it stabilize smoothly.
> 
> What's your definition of "stabilized"? I have no more CMake changes planned (maybe fix warnings if they appear). Still haven't verified Linux build though, but I need to do some git maneuvering on Windows to compile and submit PRs: apply CMake patches, apply DPI scaling workaround patch, change flags or apply other patches to reduce warnings bloat etc.

As soon as I get a chance to check everything out :-) (ASAP)

**Comment by Xeverous** [comment]
Another question: do you mind more widgets in the library? I noticed some common ones are not present (eg radio box, breadcrumb [like this](https://camo.githubusercontent.com/f91262588aa154a754bc51f632ed954c1f19e5dd/687474703a2f2f7777772e6e616e6170726f2e6f72672f656e2d75732f646f63756d656e746174696f6e2f776964676574732f696d616765732f63617465676f72697a652e706e67), tab widget [like this](https://github.com/qPCR4vir/nana-docs/raw/master/source/tabbar.png) - maybe not necessarily with the buttons on the right) and some of the built-in ones (eg knobs, sliders) do not really match in style with what I'm building (quite far from composing/editing music).

I'm pretty sure I will need radio buttons and tabs, so could issue PRs for them once I get familiar with library's code.

**Comment by djowel** [comment]
Absolutely! I would love more. Currently, I only add what I need. This library just got out of my toolbox. I wasn't quite ready when it got posted and hit the interwebs  :-)

**Comment by Xeverous** [comment]
Well, I picked this one because I struggled to find anything that would satisfy my needs (similar to yours in the post: non-intrusive build, modular, modern C++ API, no extra tools to write the GUI, ability to compose custom widgets, support for theming, MPL or more liberal license) and modifying elements seemed much easier than trying to workaround problems of other libraries. I also have time so can focus more on the "irresistible perfection" part instead of trying to develop something as fast as possible. You might consider yourself lucky or just better than the competition (in case of needs of my open source projects).

**Comment by djowel** [comment]
> The only thing I don't get is the JSON library. Thought it is another JSON parser library used to load/save configs but it doesn't look like such library (noticed it uses spirit generators). What's the actual purpose of it? Is this some serialization?

Yes. type-safe serialization. Direct in-situ c++ struct to json and back where the struct is the schema. You should go check it out (start with the tests). It's awesome cool!

**Comment by Xeverous** [comment]
Hmm, looks interesting. Could make some use of it, I'm already working with JSON files in one project and some (de)serialization of C++ types is already needed. The size of the library is at least intriguing - it has ~700 lines but some traditional implementations are much bigger (nlohmann/json has >20 000 lines). How was this achieved? Just because of spirit?

Have you tested it? JSON can be much harder than it seems to be ([as on this image from some test suite](http://seriot.ch/json/pruned_results.png)).

**Comment by djowel** [comment]
> Hmm, looks interesting. Could make some use of it, I'm already working with JSON files in one project and some (de)serialization of C++ types is already needed. The size of the library is at least intriguing - it has ~700 lines but some traditional implementations are much bigger (nlohmann/json has >20 000 lines). How was this achieved? Just because of spirit?

Yes. And the usage of spirit is rather unorthodox, where the type drives the parser and not the other way around.
> 
> Have you tested it? JSON can be much harder than it seems to be ([as on this image from some test suite](http://seriot.ch/json/pruned_results.png)).

No, I only use it for what I need (e.g. configs).  Feel free to play around with the tests.

**Comment by djowel** [comment]
> No, I only use it for what I need (e.g. configs). Feel free to play around with the tests.

At one point, I was thinking about having it presented in a C++Now talk, but that's about it. Other matters superseded and took my time :)

**Comment by Xeverous** [comment]
Spirit itself is already amazing enough (using it in one of my biggest projects so far) that I can very safely write parsers for custom domain-specific languages with no string-find-else-if sphagetti but I have a constant feeling I'm still not using it to its full capability.

**Comment by djowel** [comment]
> Spirit itself is already amazing enough (using it in one of my biggest projects so far) that I can very safely write parsers for custom domain-specific languages with no string-find-else-if sphagetti but I have a constant feeling I'm still not using it to its full capability.

Go try it out. It's a single-header file! As minimal as you can get, and that is one of its objectives:

https://github.com/cycfi/json/tree/master/include/json

It's a clever little thing that I am quite fond of!

**Comment by Xeverous** [comment]
Can we push/merge/review the modern-cmake branch? Currently I have issued PRs for all the refactor and cosmetic stuff, but I would like the CMake patch to be at least on develop before implementing new widgets. Otherwise there will be conflicts as new widgets require build script changes.

**Comment by djowel** [comment]
I am getting these errors:

```
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=~/dev/boost -G "CodeBlocks - Unix Makefiles" /Users/joel/dev/cycfi/elements
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Link-time optimization supported. Will be enabled in Release build type
CMake Error: Could not find cmake module file: CMakeDetermineOBJCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJC_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJC_COMPILER
CMake Error: Could not find cmake module file: /Users/joel/dev/cycfi/elements/cmake-build-debug/CMakeFiles/3.15.3/CMakeOBJCCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDetermineOBJCXXCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJCXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJCXX_COMPILER
CMake Error: Could not find cmake module file: /Users/joel/dev/cycfi/elements/cmake-build-debug/CMakeFiles/3.15.3/CMakeOBJCXXCompiler.cmake
CMake Error at lib/CMakeLists.txt:9 (project):
  No CMAKE_OBJC_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_OBJC_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeOBJCInformation.cmake
CMake Error at lib/CMakeLists.txt:9 (project):
  No CMAKE_OBJCXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_OBJCXX_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeOBJCXXInformation.cmake
CMake Error: CMAKE_OBJC_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_OBJCXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/Users/joel/dev/cycfi/elements/cmake-build-debug/CMakeFiles/CMakeOutput.log".

[Failed to reload]
```

**Comment by Xeverous** [comment]
My mistake. `project` command should be in a top level CMake file. It initializes necessary CMake internal variables. See #51

Now I have noticed that `OBJC` and `OBJCXX` are only supported since CMake 3.16.3. Not sure, we have 2 options now:

- Remove these 2 languages. It will probably work without them as previously. We can also drop the `if` then.
- Leave the current `if(APPLE)` and extra languages. This is more appropriate but it will raise minim CMake to 3.16.3

**Comment by Xeverous** [comment]
I see you have already merged the PR. Any decision on the question above? I think you should try to remove the `if` and `OBJC` and `OBJCXX` and see if it works - otherwise we need to bump minim required CMake version.

**Comment by djowel** [comment]
I have 3.16.2

**Comment by djowel** [comment]
It's building without the if and OBJC and OBJCXX. Let's just drop it.

**Comment by djowel** [comment]
Merged and pushed to develop.

**Comment by Xeverous** [comment]
Great news. Expect new widgets implementations and questions soon.
