### ISSUE TITLE
config.json and beyond

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#110]
In #109 it was stated about json:

> That is incorrect. There are other planned uses of it.

I would like to know what are the other planned uses. I don't really like the current situation. And it's not about having an extra header-only library (not a big issue for me). I'm more concerned with having to have a separate file (with hardcoded name) next to the executable.

Some platforms require to pass some extra information in order to initialize on them. But why is it a file? Why not pass the data in the code - eg `app` constructor? It's already taking `argc` and `argv`, why not also the `config` object?

*Elements is a lightweight, fine-grained, resolution independent, modular GUI library.* - personally I find the config thing to be somewhat unwanted coupling and unmodular. I prefer to pass such init-required-data through the library API and use my own, independent way of obtaining it.

Can we get more (finely-grained) choices for the configuration? More constructor overloads?

**Comment by djowel** [comment]
I do not have time to explain right now, but I suggest you read about MacOS bundles and Info.plist. These are configuration information and more related to an app. Config files are rather common! Passing parameters via the command line is so old-style and sooo 70s. But beyond config files, the GUI app also typically includes resources such as fonts, images, etc. I find it odd to have to explain this!

About "modularity"... I think you are talking about a different thing entirely, which does not have anything to do with app resources at all. Modularity is about the code (i.e. how classes are structured and how you combine them.) I think you are confusing modularity with something else.

reference: https://developer.apple.com/documentation/bundleresources/information_property_list?language=objc

**Comment by djowel** [comment]
So basically, the elements "app" is modeled somewhat after the MacOS app "bundle". Essentially, an app is a bundle of the executable, resources, and the information (key-value store) relevant to the app:

https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1

My main dev system is the Mac, so call me biased. But that's just the way it is going to be.

**Comment by Xeverous** [comment]
I understand your needs and I get the point of a central `app` object as it is useful for other things (eg storing fonts) but I would like to have more choices how it is handled. Other platforms have much simpler requirements (except UWP IIRC) and I would like to be able to have a higher control there. That's why I'm asking for more `app` constructor overloads; that is, being able to provide the `config` object at runtime (instead of the default automatic file load).

**Comment by djowel** [comment]
> That's why I'm asking for more `app` constructor overloads; that is, being able to provide the `config` object at runtime (instead of the default automatic file load).

Why would you want to do that? Preference? Such key-value stores can become unmanageable, except for very simple configurations. An app life cycle usually starts with just a few configs here and there, and as it matures, it gets to have more, and more and yet more, and yet even more. Configs are a future proof way forward, but you want to go backwards? I don't understand it. The concept of the Mac app is way ahead than that of Windows and Linux, due to the latter two having throwbacks to legacy command line programs.

**Comment by Xeverous** [comment]
> Configs are a future proof way forward, but you want to go backwards? I don't understand it.

No, definitely not. I have my own settings saves too. Virtually any GUI application wants to save some state when it closes.

> The concept of the Mac app is way ahead than that of Windows and Linux, due to the latter two having throwbacks to legacy command line programs.

I agree with this, but why do you insist so heavily on the library-hardcoded `config.json` file? Can't I just load my own and provide the data myself? You have already made a structure for it.

**Comment by Xeverous** [comment]
> Can't I just load my own and provide the data myself?

Note: I get that you are using the library for your own projects (which have specific use case), but I'm trying to look on the issue from a more OSS point of view that also cares about Unix and Windows systems. So far all of the changes I have made (especially CMake) were preserving existing defaults, even if I considered them to be bad defaults (from OSS point of view). I get that you want to have some OSS behind your projects but I want to have at least an option to do specific things differently that are more OSS-oriented than your specific use case. Having these "things" as default is a bonus (as you are the author and I don't want to maintain my own fork) but I want to have at least an option to do them differently.

**Comment by djowel** [comment]
Look at it this way... have you read my link about the bundle? If not please have a quick read:

https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1

Now, see: 

> Info.plist: (Required) The information property list file is a structured file that contains configuration information for the application. The system relies on the presence of this file to identify relevant information about your application and any related files.


Could Apple have done it differently? Sure! is there a better way to do it? Perhaps, but I haven't seen any other better way. 

But more importantly...

I've yet to see ANY programmer complaining about this and ask the Apple devs to allow another way of doing it. It's the same thing. Your preference might go against the way Apple did it, sure, but in the end, it's just your preference. It will be silly to bend backwards to satisfy the preferences of everyone.

**Comment by djowel** [comment]
> Note: I get that you are using the library for your own projects (which have specific use case), but I'm trying to look on the issue from a more OSS point of view that also cares about Unix and Windows systems.

I've been doing OSS since the late 90s. I don't think I have to convince you that I care about Unix and Windows less than you do.

**Comment by Xeverous** [comment]
> I've been doing OSS since the late 90s. I don't think I have to convince you that I care about Unix and Windows and at the very least not less than you do.

Well, then you did OSS even before I was born ... so what are the planned additional, future uses of the json library? I'm interested what do you have in mind. Maybe this will give me a better idea of the whole json usage.

**Comment by djowel** [comment]
> > I've been doing OSS since the late 90s. I don't think I have to convince you that I care about Unix and Windows and at the very least not less than you do.
> 
> Well, then you did OSS even before I was born ... so what are the planned additional, future uses of the json library? I'm interested what do you have in mind. Maybe this will give me a better idea of the whole json usage.

I will do so, in due time... I'm sorry I do not have time right now to give it justice. But here's the least I can say: the cycle json library is not well advertised. I haven't given it enough promotion that it deserves. It does not even have any documentation at all! It is understandable that you do not yet appreciate the value of type-safe json I/O. There is nothing like it (yet), where the C++ structure IS the schema. Likewise, it is apparent that you do not yet appreciate the concept of the 'application bundle' that I gave references for above. When you do, let's talk again on why the type-safe json is superior in many respects to other alternatives out there (for app configuration and more!), including Apple's XML based Info.plist. And believe me (or not), app configuration, as well as app state persistence, is very important, but often neglected, often resorting to ad-hoc solutions. 

That, my friend, is speaking from more than 30 years experience writing libraries, frameworks and applications.

**Comment by Xeverous** [comment]
> json library is not well advertised. I haven't given it enough promotion that it deserves. It does not even have any documentation at all! It is understandable that you do not yet appreciate the value of type-safe json I/O. There is nothing like it (yet), where the C++ structure IS the schema.

You might have missed some of my messages then because:

- I have read the source of your json library to see how it works (document it please)
- I have used a similar mechanism in my job when we needed a convenient C++ <=> JSON mapping mechanism (some RPC stuff)
- After some experiments and experience in using it in the job, I have extracted such mechanism to form a separate open source library:
  - https://www.reddit.com/r/cpp/comments/gbj5wu/fuser_ultraminimal_singlefile_headeronly_library/
  - https://github.com/Xeverous/fuser (see the tests)

> And believe me (or not), app configuration, as well as app state persistence, is very important, but often neglected, often resorting to ad-hoc solutions.

So is this more complex than just saving the state in a file and falling back to some defaults when the file/cache is not present?

**Comment by redtide** [comment]
TBH I'm also a bit confused by this, Linux have an (eco)system that provides a place for configuration files in `$HOME/.config` (or, as installed read only resource files in some `/usr/share/<appname>` directory), not using bundles which, from my POV is a personal choice to have an independent all-in-one place storage (maybe distros like GUIX or NixOS use it?).
Or maybe this have to do with having to do with something like [PortableApps] or, in Linux, there is [AppImg] at least.

About translations (as mentioned [here]) for example someone would like to use the gettext way, providing `.po` sources built in the system locale ( as compiled `.mo`) which are not used only on Linux: AFAIR wxWidgets make it works on all platform as universal i18n solution, providing functions like `_()` to pass the translated strings (same way Qt uses `tr()` for his `.ts` / `.qm` files).

Using QSettings (like I used previously with wxConfig) I prefer to use INI files anywhere, even on Windows ("registry? no thanks.") and one thing I like to have are also comments, something AFAIK JSON doesn't support, unlike something like YAML.

FWIW, in brief if I don't miss something else, I would like to have this feature as optional.

[here]: https://github.com/cycfi/elements/issues/44#issuecomment-629826728
[PortableApps]: https://portableapps.com/
[AppImg]: https://appimage.org/

**Comment by redtide** [comment]
see also #151

**Comment by djowel** [comment]
The latest develop and master no longer require json, so this issue is resolved. Closing now... Feel free to reopen if I missed something.
