### ISSUE TITLE
missing includes in receiver.hpp

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#112]
This file has missing includes for `std::string` and `std::string_view`: https://github.com/cycfi/elements/blob/master/lib/include/elements/element/receiver.hpp

It is currently relying on other headers providing them indirectly.

Also, do you remember when some time ago I was talking that I got multiple indexing problems with elements when using Eclipse? A lot of functions are not being indexed and get underlined as if they did not exist. Often Eclipse doesn't tell clearly what's the problem but its built-in parser is very strict so I have a stong belief something is indeed wrong.

It can detect subtle issues that are not discovered by the compiler such as:

- missing includes in some header like the presented `receiver.hpp` (code compiles because receiver is never ncluded first and relies on other headers indirectly defining needed entities)
- broken includes (eg missing `#endif` at the bottom or duplicated header guard name in multiple headers)
- multiple definitions of the same name in multiple translation units (not an error but cause indexer to open a dialog upon ctrl+clicking the name to select specific definition)

For a long time I had problems with most element factories. Trivial stuff like `rect`, `color` works but anything from `vtile`, `htile`, even `label` is being underlined. I have finally found the root cause.

Nothing is wrong with elements source code (maybe only easily-fixable stuff like receiver). It's actually a bug in the indexer: an empty `main.cpp` file has no problems, but adding just `#include <elements/element/layer.hpp>` stops the indexer from parsing entire include chain due to `java.lang.ArrayIndexOutOfBoundsException`. There are some unique templates in this file that I think are causing the exception, I'm trying to minimize the code before submiting a bug.

**Comment by djowel** [comment]
Interesting. IIRC, there's a tool for finding out missing includes that are indirectly being included. I don't remember what exactly.

**Comment by Xeverous** [comment]
FYI, this is minimal code that crashes Eclipse parser/indexer:

```cpp
#include <cstddef>

namespace elements
{
   template <typename T, std::size_t N>
   struct array {};

   template <typename Container, typename Base>
   class composite : public Base, public Container {};

   template <std::size_t N, typename Base>
   using array_composite = composite<array<std::size_t, N>, Base>;

   template <typename... E>
   inline auto layer(E&&... elements)
   {
      return array_composite<sizeof...(elements), int>{};
   }
}
```

The sample comes from `layer.hpp` which is indirectly included by most public headers.

> a tool for finding out missing includes that are indirectly being included

https://include-what-you-use.org ?

**Comment by Xeverous** [comment]
Added in 6d1f98cda14866becc0b1cc467afd50c5efef477.
