### ISSUE TITLE
dynamic change of size-related elements

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#113]
Labels and buttons can dynamically change text. What if we could change values of various trivial elements without redoing the whole hierarchy?

I found some inconsistency in `size.hpp`:

https://github.com/cycfi/elements/blob/0038cf48380955f3c4f500d34baad23961456d1f/lib/include/elements/element/size.hpp#L451-L465

https://github.com/cycfi/elements/blob/0038cf48380955f3c4f500d34baad23961456d1f/lib/include/elements/element/size.hpp#L496-L509

Some size-related types have public member variables, others private. What if we could expose them by public functions on each respective element? I'm thinking of public member functions that have the same name as the factories.

Example what would be possible:

```cpp
auto e = /* ... */;
auto x = hmax_size(100.0f, e);
auto y = vstretch(2.0f, e);
x.hmax_size(150.0f);
y.vstretch(1.5f);
```

From implementation point of view, there is nothing to do apart from adding setters as all of the floats are being re-read in all element interface functions.

**Comment by djowel** [comment]
> Some size-related types have public member variables, others private. What if we could expose them by public functions on each respective element? I'm thinking of public member functions that have the same name as the factories.

Very good points! I like it. Go for it!

**Comment by Xeverous** [comment]
#115
