### ISSUE TITLE
repair proxy element forwarding

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#117]
(copy from tab issue, for further investigation and discussion here)

___

https://github.com/cycfi/elements/blob/40037b2b49fe23b842ac12e6957e516c7856a01e/lib/include/elements/element/proxy.hpp#L61-L88

Both of these functions take `Subject&& subject` argument, but:

- There is no perfect forwarding because `Subject` is not deduced. It's already specified by the class template and both the constructor and `subject` setter are simply using it. Perfect forwarding is only possible when the function template can apply reference collapsing during type deduction.
- Because of how we use proxy (we always store values of non-reference type), the `std::decay` is a no-op. It has no purpose when `Subject` is not deduced and at this point (inside the class) `Subject` already must be a non-reference type.
- Beacuse `Subject&&` is not deduced, both `std::forward`s are no-op.
- Beacuse `Subject&&` is not deduced, both the constructor and the setter are expecting rvalues. This hit me during some tab factory works when I supplied an lvalue to the constructor. You can trigger the error by any lvalue object: `proxy<element>(empty())` works, but `auto e = empty(); proxy<element>(e);` fails on forbidden lvalue-to-rvalue convertion.

**Comment by Xeverous** [comment]
> Correct. Indeed. The ctor should probably take a template to allow convertibility, etc. That is the intent here IIRC.

This is possible but has an important consequence: if the constructor deduces the type, the class will need to be already instantiated. So you will need to specify class template parameter first, only then you will be able to call the deducing constructor.

I think we do not need such converting constructor. Proxy by design is to *proxy* other elements, so I don't see any point in converting proxied element. We should just do a factory function that will deduce the passed type and use it for the class template parameter, ensuring the type satisfies requirements. Something like this:

```cpp
template <typename Base = proxy_base, typename Subject, typename... Args>
auto proxy(Subject&& subject, Args&&... args)
{
    static_assert(std::is_base_of_v<proxy_base, Base>,
        "proxy Base type needs to be or inherit from proxy_base");

    using subject_type = std::decay_t<Subject>;
    return proxy_element<subject_type, proxy_base>{ std::forward<Subject>(subject), std::forward<Args>(args)... };
}
```

Then edit the constructor to follow standard modern C++ guideline - take by value and move from it.

```cpp
// Args - deduced and perfectly forwarded
// Subject - class template parameter, non-deduced (expected to be a non-reference type)
template <typename... Args>
proxy(Subject subject, Args&&... args)
: Base(std::forward<Args>(args)...)
, _subject(std::move(subject)) {}
```

**Comment by djowel** [comment]
> I think we do not need such converting constructor. Proxy by design is to _proxy_ other elements, so I don't see any point in converting proxied element. 

Yes, you are right. It is indeed not necessary. 

> We should just do a factory function that will deduce the passed type and use it for the class template parameter, ensuring the type satisfies requirements. Something like this:

I don't think that is necessary either. You do not directly construct a proxy. They are created by derived proxy classes, and that's taken cared of already.

**Comment by Xeverous** [comment]
> You do not directly construct a proxy

Right, there is no point in doing so.

> They are created by derived proxy classes, and that's taken cared of already.

I don't think that they are taking care of correctly. Every factory looks like this:

https://github.com/cycfi/elements/blob/e29d1fad659291a25294f8d93798ef223ef7dc4f/lib/include/elements/element/size.hpp#L41-L46

All such factories deduce the `Subject` and instantiate the proxy with that deduced type depending on the passed argument.

- if the factory is passed a `T` rvalue, `Subject` is deduced to `T` and the function takes `T&&`
- if the factory is passed a `T` lvalue, `Subject` is deduced to `T&` and the function takes `Subject&&` which is `T& &&` which (after reference collapsing) is `T&`
- if the factory is passed a `T const` lvalue, `Subject` is deduced to `T const&` and the function takes `Subject&&` which is `T const& &&` which (after reference collapsing) is `T const&`

The last two cases instantiate then a proxy class template with a reference type. This breaks proxy interface in multiple places because there are no deductions and all of member functions taking `Subject&&` are either taking rvalue or non-const lvalue only. Example problem:

```cpp
auto x = no_hstretch(empty()); // fine, instantiates proxy<element>

auto e1 = empty();
auto const e2 = empty();
auto y = no_hstretch(e1); // bad, instantiates proxy<element&>
x.subject(e2); // compile error: proxy<Subject>::subject(Subject&&) [with Subject = element&] expects an argument of type element& but is given element const&

```

```
main.cpp:19:12: error: binding reference of type 'cycfi::elements::element&' to 'const cycfi::element
s::element' discards qualifiers
   19 |  y.subject(e2);
      |            ^~
```

**Comment by Xeverous** [comment]
Said differently, I think there is a need for a proxy factory that will strip the reference from passed `Subject` type.

In a different approach, we could let instantiate proxy with a reference type and then "fix" it in its member functions by using `subject_type` (which is `std::decay_t<Subject>`) parameters. But I think the first option is better and more intuitive - it's easier to reason about proper instantiation than to reason about `proxy<T&>` which actually holds `std::decay_t<T&>` element.

**Comment by djowel** [comment]
> Said differently, I think there is a need for a proxy factory that will strip the reference from passed `Subject` type.
> 
> In a different approach, we could let instantiate proxy with a reference type and then "fix" it in its member functions by using `subject_type` (which is `std::decay_t<Subject>`) parameters. But I think the first option is better and more intuitive - it's easier to reason about proper instantiation than to reason about `proxy<T&>` which actually holds `std::decay_t<T&>` element.

OK, that's a very good point!

**Comment by Xeverous** [comment]
For proper proxy code I would ideally use `std::remove_cvref` but it requires C++20. How about adding equivalent implementation to infra?

**Comment by Xeverous** [comment]
See https://github.com/cycfi/infra/pull/8

**Comment by djowel** [comment]
> For proper proxy code I would ideally use `std::remove_cvref` but it requires C++20. How about adding equivalent implementation to infra?

merged

**Comment by Xeverous** [comment]
#119

This change brings `proxy` in line with `indirect`, `reference` and `shared_reference` which:

- require proper type to instantiate the class - I have added static asserts to the `proxy`
- uses the supplied type explicitly with no hidden transformation traits or reference collapsing - there were many cases with functions taking `Subject&&` but because it was not a deduced context all of the `std::forward`s were a no-op and/or were breaking the interface due to reference collapsing

**Comment by djowel** [comment]
> #119
> 
> This change brings `proxy` in line with `indirect`, `reference` and `shared_reference` which:
> 
> * require proper type to instantiate the class - I have added static asserts to the `proxy`
> * uses the supplied type explicitly with no hidden transformation traits or reference collapsing - there were many cases with functions taking `Subject&&` but because it was not a deduced context all of the `std::forward`s were a no-op and/or were breaking the interface due to reference collapsing
> * `proxy` ctor now takes by value and moves from it
> * all factories creating proxy-derived types now correctly forward the argument and correctly instantiate the `proxy` class template

Wonderful! Nice one, @Xeverous.
