### ISSUE TITLE
input box API

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#118]
When writing theme editor example, I noticed few things with this widget:

First, there is the weird factory different from everything else that returns `std::pair` instead of a single element:

https://github.com/cycfi/elements/blob/616233d17122ec44cb7448258a7677d494b7f254/lib/include/elements/element/gallery/text_entry.hpp#L42-L55

Across the entire library source, all uses of this function immediately use the `.first` on the result.

There was some discussion about it before and there was an idea to make a pair widget instead that has some way to expose a specific contained widget.

Second thing, I find the `basic_input_box` callbacks to be a bit awkward:

https://github.com/cycfi/elements/blob/616233d17122ec44cb7448258a7677d494b7f254/lib/include/elements/element/text.hpp#L169-L170

- Why does the `text_function` has to return a string? Whatever library I have seen so far just reported current text to the callback. If the callback wanted to replace the text in the box, it just manually did `box.set_text(str)`.
- What's the purpose of the `enter_function`? Why is it tied to enter key specifically?

My propositions:

- change the `text_function` to just get the currently stored string OR a reference to the box
- change the factory in one of 2 ways:
    - instead of returning a pair, take callback as a factory argument and bind it immediately - this removes the practically only wanted use of the object (binding a callback)
    - let user create the sole `basic_input_box` and then offer a factory that encapsulates the widget in some hierarchy as this one:

https://github.com/cycfi/elements/blob/616233d17122ec44cb7448258a7677d494b7f254/lib/include/elements/element/gallery/text_entry.hpp#L23-L40

**Comment by djowel** [comment]
> There was some discussion about it before and there was an idea to make a pair widget instead that has some way to expose a specific contained widget.

Yes, I like that.

**Comment by djowel** [comment]
> * Why does the `text_function` has to return a string? Whatever library I have seen so far just reported current text to the callback. If the callback wanted to replace the text in the box, it just manually did `box.set_text(str)`.

Because it allows you to use it as a filter, without having to set the text directly yourself. For example, not allowing letters in numeric input boxes.

> * What's the purpose of the `enter_function`? Why is it tied to enter key specifically?

Because the final commit of the text that you entered is done when the user presses enter. It gives the app a chance to check the validity of the input, for example if a number entered is out of range, and so the app can also have a chance to bring up an alert and not accept the text.
