### ISSUE TITLE
Absolute resource paths are defective

### ISSUE THREAD

**Issue by jpcima** [cycfi/elements#120]
Hi, there is an implementation error in `resource_paths.cpp` regarding absolute paths.
It checks `full_path` to exist on disk, but this string is empty at this point in code.

See
https://github.com/cycfi/elements/blob/e29d1fad659291a25294f8d93798ef223ef7dc4f/lib/src/support/resource_paths.cpp#L16-L22

**Comment by djowel** [comment]
> Hi, there is an implementation error in `resource_paths.cpp` regarding absolute paths.
> It checks `full_path` to exist on disk, but this string is empty at this point in code.

Good catch! It's an easy fix. Will you do a PR?

**Comment by jpcima** [comment]
Sure I make you one in a sec.
