### ISSUE TITLE
Fonts in custom resource path on Linux, cannot load

### ISSUE THREAD

**Issue by jpcima** [cycfi/elements#123]
Hello, on Linux it's impossible to load the font shipped along with my plugin.
The library cannot deduce a resource path on this OS, so it decides one based on the work directory.
This technique is unable to work in particular cases like audio plugins.

https://github.com/cycfi/elements/blob/e29d1fad659291a25294f8d93798ef223ef7dc4f/lib/src/support/font.cpp#L156

What is the preferred solution to resolve this problem?
I would be satisfied if there exists a way to set up the font path externally, similar to the resource path.

**Comment by djowel** [comment]
Looks like you hit a bug. The right way to deal with this is to provide a generic to way to allow users to set fonts path or paths, perhaps similar to the way resources such as images are loaded. This should be easy. I'll think of a way, but feel free to suggest!

**Comment by jpcima** [comment]
The solution has worked, I close it.
