### ISSUE TITLE
ancillary wrapping element

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#126]
I started to brainstorm potential element that could hold an extra element that is contained within, to replace the following code:

https://github.com/cycfi/elements/blob/3d79f57223e4a291edd9dc7a1d13d8c60ee35a72/lib/include/elements/element/gallery/text_entry.hpp#L42-L55

the design is rather simple:

```cpp
template <typename Base, typename Subject>
class ancillary_element : public Base
{
public:
    static_assert(std::is_base_of_v<element, Base>);

    template <typename... Args>
    ancillary_element(Subject& subject_, Args&&... args)
    : Base(std::forward<Args>(args)...), _subject(&subject_)
    {
    }

    Subject& subject() { return *_subject; }
    Subject const& subject() const { return *_subject; }

private:
    Subject* _subject;
};
```

However, such class is the first element type that can not use rule of zero and requires custom ctor and assignment operators. What's worse is that copy ctor and assignment can not be implemented for this class because it lacks any knowledge how to obtain correct subject pointer from copied hierarchy.

This would be the first element that is moveable only.

Currently elements has copies in 2 places:

- proposed PR with tab: https://github.com/cycfi/elements/pull/122/commits/d0e20110e05d0f2ee343cd8a236a45111e6a221c#diff-3180a915b31c814043a5d98ec602d66eL48-R59
- some examples which do not use `std::move` in all places where possible

Note that the current implementation of `input_box` factory creates a hierarchy that contains a shared pointer element inside, which means that input box copies are shallow copies only.

**Comment by Xeverous** [comment]
@djowel do you have any design choice for copying widgets? Support copying? Do not support? Support for unproblematic types? There are many factories which are using `std::shared_ptr` which results in constructed hierarchies to have shallow copies only.

Shallow copies are generally fine, but they can cause problems when one creates a hierarchy that contains shared widgets with unique behavior: eg input box. Such widgets are practically always desired to deep copy themselves.

**Comment by djowel** [comment]
> @djowel do you have any design choice for copying widgets? Support copying? Do not support? Support for unproblematic types? There are many factories which are using `std::shared_ptr` which results in constructed hierarchies to have shallow copies only.
> 
> Shallow copies are generally fine, but they can cause problems when one creates a hierarchy that contains shared widgets with unique behavior: eg input box. Such widgets are practically always desired to deep copy themselves.

Very good question. Elements are typically copyable (do you see problematic non-copyable elements?). Beyond that, I think we should also support deep copies for elements with shared objects. Copy should be via operator=. Deep copy (perhaps `clone`) can probably be a free function that calls a virtual member function.

**Comment by Xeverous** [comment]
> do you see problematic non-copyable elements?

Nothing apart from the wrapping element in this issue.

The question is, how can we make deep copy vs shallow copy an intuitive behavior? If I create a hierarchy that contains an input box, copying it via copy ctor or `operator=` should be a deep copy because I intuitively want multiple input boxes wrapped in their enclosing hierarchy. I don't see any point in shallow copies, I would only copy shared pointers to ensure lifetime.

**Comment by djowel** [comment]
> The question is, how can we make deep copy vs shallow copy an intuitive behavior? If I create a hierarchy that contains an input box, copying it via copy ctor or `operator=` should be a deep copy because I intuitively want multiple input boxes wrapped in their enclosing hierarchy. I don't see any point in shallow copies, I would only copy shared pointers to ensure lifetime.

Very good point, actually. But it somehow does not feel right because it violates the semantics of copying shared_ptr and containers of shared_ptr such as std::vector<shared_ptr<T>>. My intuition tells me that deep copy should be explicit. E.g.:

```c++
auto e = deep_copy(rhs);
```

I think we should not hide the fact that some elements are "held" by indirect mechanisms such as shared_ptr. Oh, and there is also one that is held by reference (https://github.com/cycfi/elements/blob/master/lib/include/elements/element/indirect.hpp#L84), which intuitively should look like a reference.

So, for such "indirect" objects, I think the behavior should the same way that operator= on a struct with a shared_ptr or reference_wrapper.

**Comment by Xeverous** [comment]
Interface idea:

```cpp
template <typename E>
E deep_copy(E const& e)
{
    return e;
}
```

This works out of the box for most elements, others will just have to specialize the function template.

**Comment by djowel** [comment]
> Interface idea:
> 
> ```c++
> template <typename E>
> E deep_copy(E const& e)
> {
>     return e;
> }
> ```
> 
> This works out of the box for most elements, others will just have to specialize the function template.

I think it should be:

```c++
template <typename E>
E deep_copy(E const& e)
{
    return e->deep_copy();
}
```

It is possible to have a shared_ptr to a base class (shared_ptr<element>), so `e->deep_copy();` will actually have to be `virtual`.

**Comment by Xeverous** [comment]
What if the element was not dynamically allocated?

Note that the current implementation of `share` moves to a shared pointer to copies depending on the value category of passed argument:

https://github.com/cycfi/elements/blob/3d79f57223e4a291edd9dc7a1d13d8c60ee35a72/lib/include/elements/element/element.hpp#L74-L79

**Comment by Xeverous** [comment]
How about having *both* of the copy interfaces?

- When you have a shared pointer to base, virtual function is the only way to go. Potential elements which are non-copyable should throw.
- When you have a concrete type available, copying can happen without smart pointers. Most element types will work out of the box, others which hold eg composite will use the virtual function interface internally inside the non-virtual function template.

**Comment by djowel** [comment]
Sounds good!

**Comment by Xeverous** [comment]
The more I think and attempt to write any of these copy interfaces the more problems I see with them:

- `composite` holds a lot of state that is not available to set at comstruction time.
- `proxy` and all derived types would need an extra constructor that takes an instance of `base_type` because the only reasonable way to copy such element is to "ask" the subject to copy itself and ask base type to do it aswell.
- Various types are holding callbacks. If the callback holds any referenced user data, copying such callback will be very surprising as 2 widgets will do the same on user action.
- Various types override `operator=`. This further complicates any implementation, because one can not use any idiomatic C++ code.

At this point I think it is better to explicitly "ban" copying any elements and require library users to just call element factories again - all examples are already doing it.

**Comment by djowel** [comment]
> At this point I think it is better to explicitly "ban" copying any elements and require library users to just call element factories again - all examples are already doing it.

Let me think about it some more.

**Comment by Xeverous** [comment]
Thinking about the auxiliary element holder: it can not store a pointer or a reference because at the point of all factories objects are being moved around so a pointer/reference to a temporary will not work.

The same thing would be needed as in the existing factory: create a shared pointer to the inner element, put `hold(e)` into the enclosing hierarchy and then put that hierarchy + shared pointer to such wrapping class. I don't see this to be a really clean solution, but I think it's better than returning a `std::pair` which is different than every other factory.

**Comment by Xeverous** [comment]
Note that `notebook` does not have such problem: it first constructs the hierarchy and then uses `find_element` to move through it and setup callbacks.

**Comment by djowel** [comment]
> Note that `notebook` does not have such problem: it first constructs the hierarchy and then uses `find_element` to move through it and setup callbacks.

Perhaps a simpler solution is to simply return a single element if we make `find_element` a standard API for users.

**Comment by Xeverous** [comment]
Yes, optionally it is also possible to create an input box first, setup callbacks and then call the factory that wraps it in some margins etc.
