### ISSUE TITLE
stretching bug

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#127]
Working on the theme editor example, encountered this:

```cpp
#include <elements.hpp>

using namespace cycfi::elements;

auto make_widgets()
{
   return htile(
      label("test"),
      no_hstretch(input_box("r").first),
      no_hstretch(input_box("g").first),
      no_hstretch(input_box("b").first),
      no_hstretch(input_box("a").first)
   );
}

int main(int argc, char* argv[])
{
   app _app(argc, argv);
   window _win(_app.name());
   _win.on_close = [&_app]() { _app.stop(); };

   view view_(_win);

   view_.content(
      make_widgets(),
      box(rgba(35, 35, 37, 255))
   );

   _app.run();
   return 0;
}
```

The following code has broken input boxes, none are visible but min and max window size remains correct. Remove all `no_hstretch` calls and the examle works correctly.

**Comment by Xeverous** [comment]
I found this to be problematic code:

- There is some inconsistency between `float` and `double` usage
- The algorithm is not correct (looks like naive brute force with no proper loop condition)
- The comment is wrong (it loops 9 times)
- The is at least 1 bug within the algorithm (division by 0)

https://github.com/cycfi/elements/blob/700f0d1adeb77ee7a459bfdfd3316980053361b3/lib/src/element/tile.cpp#L43-L72

I have got the algorithm that does it correctly: http://coliru.stacked-crooked.com/a/a2aea684eee28760 (has O(n log n) complexity). Want a PR?

**Comment by djowel** [comment]
> I have got the algorithm that does it correctly: http://coliru.stacked-crooked.com/a/a2aea684eee28760 (has O(n log n) complexity). Want a PR?

Sounds good!

**Comment by djowel** [comment]
> > I have got the algorithm that does it correctly: http://coliru.stacked-crooked.com/a/a2aea684eee28760 (has O(n log n) complexity). Want a PR?
> 
> Sounds good!

I'll study it more later, but it is looking good! Nice!

**Comment by Xeverous** [comment]
#136

**Comment by Xeverous** [comment]
> I'll study it more later, but it is looking good! Nice!

Just open the layout example. It should look the same as previously but the following will also work which is currently bugged:

```cpp
#include <elements.hpp>

using namespace cycfi::elements;

auto make_widgets()
{
   return vtile(htile(
      label("test"),
      input_box("r").first,
      input_box("g").first,
      input_box("b").first,
      input_box("a").first
   ),
   htile(
      label("test no hstretch"),
      no_hstretch(input_box("r").first),
      no_hstretch(input_box("g").first),
      no_hstretch(input_box("b").first),
      no_hstretch(input_box("a").first)
   ));
}

int main(int argc, char* argv[])
{
   app _app(argc, argv);
   window _win(_app.name());
   _win.on_close = [&_app]() { _app.stop(); };

   view view_(_win);

   view_.content(
      make_widgets(),
      box(rgba(35, 35, 37, 255))
   );

   _app.run();
   return 0;
}
```

**Comment by djowel** [comment]
@Xeverous, this code is fantastic! Merged to develop! Thank you for working on this.

This gets me thinking that I really need to start doing testing. Layout is very important and should probably be the first to be tested. I wonder what more bugs are lurking inside there that can be exposed with formal testing.

**Comment by Xeverous** [comment]
PR merged, closing.
