### ISSUE TITLE
Offline documentation using Jekyll locally

### ISSUE THREAD

**Issue by redtide** [cycfi/elements#130]
I was playing with the website pages to load them locally but I'm not sure if it could be a useful feature for you; I saw recently a commit on master that you use to link to website pages instead local ones plus, AFAIK, Jekyll on Windows is problematic (no idea under macOS, should be fine I suppose), otherwise I could send a PR for this.

**Comment by djowel** [comment]
> I was playing with the website pages to load them locally but I'm not sure if it could be a useful feature for you; I saw recently a commit on master that you use to link to website pages instead local ones plus, AFAIK, Jekyll on Windows is problematic (no idea under macOS, should be fine I suppose), otherwise I could send a PR for this.

Sure, go ahead! Sounds good.

**Comment by redtide** [comment]
Thanks! Closing.
