### ISSUE TITLE
basic_text_box bugs

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#134]
things I have noticed while working on theme editor:

- `basic_input_box::on_text` (as the name suggests) is not called on every text change, it is called only when a new text is inserted through keyboard. Pasting or removing characters does not trigger the callback.
- delete key is working the same as backspace - removing characters before the caret instead of after

**Comment by Xeverous** [comment]
@djowel, this is my most needed thing now

**Comment by djowel** [comment]
> * `basic_input_box::on_text` (as the name suggests) is not called on every text change, it is called only when a new text is inserted through keyboard. Pasting or removing characters does not trigger the callback.

That is not correct. Pasting should trigger the callback:
https://github.com/cycfi/elements/blob/master/lib/src/element/text.cpp#L1020

(I retested that to be sure)

> * delete key is working the same as backspace - removing characters before the caret instead of after

Grrr, Mac does not have such a key. "The delete key on a Mac, however, acts like the backspace key on a Windows keyboard. That is, it deletes the character to the left of the cursor. The delete key on a Windows keyboard does the opposite and deletes the character to the right of the cursor"

Anyway, should be easy...

**Comment by djowel** [comment]
> * removing characters does not trigger the callback.

I'm testing that now.

**Comment by djowel** [comment]
partial fix in https://github.com/cycfi/elements/issues/134

- Paste (no need to fix)
- Delete now calls `on_text`
- Added example on how to add an `on_text` callback

I'll fix the delete/backspace later, so keep this open. I'll have to switch to windows to test it. If you want to do it, go ahead, it's easy:

https://github.com/cycfi/elements/blob/master/lib/src/element/text.cpp#L377-L384

A way to do it is to add a bool variable to the delete_() member function:

```c++
virtual void            delete_(bool forward = false);
```
It should be #ifdefed on MacOS because there, there is no distinction.

**Comment by Xeverous** [comment]
> I'll fix the delete/backspace later, so keep this open. I'll have to switch to windows to test it.

The bug is also present on Linux. I actually don't remember where I noticed it first.

> It should be #ifdefed on MacOS because there, there is no distinction.

Why? It could be desired by the library users.

**Comment by djowel** [comment]
> > It should be #ifdefed on MacOS because there, there is no distinction.
> 
> Why? It could be desired by the library users.

You are right. It is needed.

**Comment by djowel** [comment]
Forward delete is now implemented in develop and artist_port
