### ISSUE TITLE
basic_input_box on_text callback change

### ISSUE THREAD

**Issue by djowel** [cycfi/elements#140]
Unless there is an objection (@Xeverous ?), I'm changing the signature of the callback to:

```c++
std::function<std::optional<std::string>(std::string_view text)>
```

...for efficiency. I need to distinguish if the callback wants to modify the text or not without incurring any overhead when no change is needed.

**Comment by Xeverous** [comment]
The initial callback signature was weird for me. IMO the signature should be `void (std::string_view)` or `void (input_box&, std::string_view)`. I have never seen an approach when the on-text callback has to return something (at most `bool` whether callback succeeded). IMO it would be better to just add a reference to the input box to the callback and let the callback set different text if it wants. Input processing and callbacks is done before rendering in a loop so the initial text will not be rendered and the next frame will already contain the text set through the callback.

**Comment by djowel** [comment]
You do not need input_box, you can already capture that in a lambda if you need it. I'll probably go for a simple bool return. Keep it simple.

**Comment by Xeverous** [comment]
What will be the meaning of the returned boolean?

**Comment by djowel** [comment]
> What will be the meaning of the returned boolean?

It was originally meant as a means to 'accept'. For example, it allows a filter to accept only numbers. But thinking about it some more, that kind of filtering is very limited and probably not needed. Input error correction should probably happen only on `on_enter` by reporting back the error (e.g. in a dialog).

So yeah, you win. It's best to keep it as simple as possible and remove it.

**Comment by djowel** [comment]
Fixed in https://github.com/cycfi/elements/commit/85b31024d04db0ef1d3998f848d0d6fb354ad8f5
