### ISSUE TITLE
Dynamic layouts

### ISSUE THREAD

**Issue by redtide** [cycfi/elements#146]
It could be nice to have some feature that permits changes in the layout based on different conditions:
I wish an array of knobs which is different based on the file I'm loading.
In brief, to have some 'add/remove/insert" feature in grid elements to add/insert/remove widgets programmatically.

**Comment by djowel** [comment]
Have you tried creating your own layers? The layer is the same element that the view uses to dynamically add/remove items. For example, popups are added as new layers on top of existing layers and removed on close. The deck is another way to do it. The deck is a layer where only one is active. Buttons currently are two-layer decks, the on state and the off state.

**Comment by djowel** [comment]
BTW, basically, all composite elements allow add/remove/insert. That includes vtile/htile/layers,decks, etc. Check out the layout docs: http://cycfi.github.io/elements/layout. For example: see layer_composite:

The layer_composite is basically a std::vector<element_ptr> that the client uses to manage the composite’s elements. The lifetime of the container, c, is the client’s responsibility. You use layer_composite just as you would a std::vector, such as push_back a child element. Just keep in mind that we are dealing with element_ptr items.

Example

```c++
c.push_back(share(child));
:point_right: share turns an element object into an element_ptr held by the std::vector<element_ptr> in layer_composite.
```

layer_composite is itself also an element and while it has std::vector’s interface, it can also be shared like any element, which allows you to build complex hierarchical structures.

**Comment by djowel** [comment]
Hint: the view "contents" is actually  just a `layer_composite`

```c++
   view_.content(
                     // Add more content layers here. The order
                     // specifies the layering. The lowest layer
                     // is at the bottom of this list.

      background     // Replace background with your main element,
                     // or keep it and add another layer on top of it.
   );

```

**Comment by Xeverous** [comment]
Adding more to the context, I'm using `proxy` as a container of always 1 element (you can replace stored element by `.subject()`). Otherwise (when I need to swap elements) I use `deck`.

**Comment by redtide** [comment]
Thank you for information, will test this soon. I'm going to close this.
