### ISSUE TITLE
menu elements API and factories

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#148]
So I have checked multiple examples but I haven't found any menu that would fully satisfy me.

My ideal menu element would:

- Have just 1 callback (`void (std::size_t index)`). I may store arbitrary elements and getting the selected item index is the only reasonable way for the library to report it.
- The menu would expose a standard container interface (eg vector, either by deriving from it or having `m.options()`) so that one can add/remove option elements freely (this is much more flexible than `is_enabled` option functor). Adding things such as `menu_item_spacer` should not change/shift indexes of reported selections.
- There should be an access to the menu's label (eg `m.label()`)

Obviosuly I know that any arbitrary widget can be made through use of other library parts. This is just the thing that IMO is a good general use-case scenario to be in the API which is not overly complex at the same time.

**Comment by djowel** [comment]
I think that would amount to a very simplistic, but very inflexible code. But OK, perhaps I do not understand sufficiently what you mean (e.g. your comment on `is_enabled` makes no sense). So, as always, show me some code and I will consider it.

**Comment by Xeverous** [comment]
> your comment on is_enabled makes no sense

After looking deeper into it, indeed it makes no sense. I just realized that elements for which this fucntion returns `false` are rendered in a different color. Initially I thought they are not rendered at all, as if they did not exist.

> So, as always, show me some code and I will consider it.

Ok, another PR to my TODO list.
