### ISSUE TITLE
Structure of the Linux bundle

### ISSUE THREAD

**Issue by jpcima** [cycfi/elements#151]
Hi, I would like to hear your opinion about a suggestion for the Linux bundle.

Currently, the Linux app host would search `config.json` is the current working directory.
The linux graphical apps often don't run in the cwd where the binary is located, and this can be an obstacle for installation and typical use.

I had in mind to let the program identify its bundle locations according to the location of the binary.
If the program resides in a folder `bin`, as in Linux FHS, the program may select an adequate hierarchy if it exists on disk; otherwise it can be allowed to fall back to the usual.

As an example
- `bin/<myprogram>`
- `share/<myprogram>/config.json`
- `share/<myprogram>/[resources...]`

**Comment by djowel** [comment]
As they say, when in rome, do as the romans do. Obviously, I am Mac centric. I am OK with this, but to move forward towards the correct direction, what is it would you suggest is the best 'linux-y' way to deal with resources (fonts, configs, images, etc.)?

**Comment by jpcima** [comment]
There is not much standardized file organization beside this.
The folder `share/<program>` is there to be used as the user pleases, there's no problem to make it the resource root. Many existing programs operate according to such hierarchy.

It's notable that `config.json` is read-only for non-admin users, so it should not be used for storing settings. If there should ever be a file for user settings, it should exist in the home directory instead.

**Comment by djowel** [comment]
> There is not much standardized file organization beside this.
> The folder `share/<program>` is there to be used as the user pleases, there's no problem to make it the resource root. Many existing programs operate according to such hierarchy.
> 
> It's notable that `config.json` is read-only for non-admin users, so it should not be used for storing settings. If there should ever be a file for user settings, it should exist in the home directory instead.

Yes, config.json should be read-only. Same is true on all platforms. Actually, I'm probably OK about removing config.json for a more native solution. That would ultimately lessen the dependency on boost for such basic things. I know either you or someone else criticized about this. I'll cross the bridge when I get to the point where I need to store user data, but that should probably be a choice (I'm not sure yet).

**Comment by djowel** [comment]
> Actually, I'm probably OK about removing config.json for a more native solution.

BTW, in MacOS, elements actually uses Info.plist, which is an xml file.

**Comment by redtide** [comment]
On Linux I like that everything has its own place, both global/admin only and local to override global configurations.
Recently I use to store also libraries and plugins in `$HOME/.local/lib` and `$HOME/.local/lib/{vst3|lv2}` for convenience when debugging.
Same for configuration files that can go also in `/etc` other than `/usr/share/<appname>` if only for configurations, which can be override by `$HOME/.<appname>` (please don't use this) or better `$HOME/.config/<appname>`.

See also <https://stackoverflow.com/questions/1024114/location-of-ini-config-files-in-linux-unix>

**Comment by redtide** [comment]
I forgot to mention that when using CMake `install` command, by using the [GNUInstallDirs] module, there is a `CMAKE_INSTALL_DATADIR`. This is my usual script in that case:
```
if (UNIX AND NOT APPLE)
    include (GNUInstallDirs)
    install (TARGETS ${PROJECT_NAME}
        DESTINATION ${CMAKE_INSTALL_BINDIR})
    install (DIRECTORY resources/icons/posix/
        DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor)
    install (FILES resources/linux/${PROJECT_NAME}.appdata.xml
        DESTINATION ${CMAKE_INSTALL_DATADIR}/metainfo)
    install (FILES resources/linux/${PROJECT_NAME}.desktop
        DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
endif()
```
it could be some `install (FILES resources/config.json DESTINATION ${CMAKE_INSTALL_DATADIR}/${PROJECT_NAME})` --> `/usr/share/<appname>/config.json`

[GNUInstallDirs]: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by djowel** [comment]
We no longer need config.json. Please check the code changes in develop (also now merged to master) and see if all is well. Feel free to close this issue, or tell me what you think if there are other things that need to be addressed.

**Comment by jpcima** [comment]
Thanks, I will check give this update a more detailed look.
At first, i notice the Linux program has trouble to launch again because it's reliant on the current directory.
I will make a change to adapt the path logic.

**Comment by djowel** [comment]
Wonderful! Merged. Feel free to close this as you see fit. Many thanks @jpcima

**Comment by jpcima** [comment]
It's good thanks.
