### ISSUE TITLE
Compile Error MSVC elements/element/grid.hpp

### ISSUE THREAD

**Issue by petiaccja** [cycfi/elements#160]
Hi,

I think here:
https://github.com/cycfi/elements/blob/a7d1348ae81f7c0416a3b4a8ea09857c9543203e/lib/include/elements/element/grid.hpp#L73
https://github.com/cycfi/elements/blob/a7d1348ae81f7c0416a3b4a8ea09857c9543203e/lib/include/elements/element/grid.hpp#L111

you meant:
```c++
#if defined(_MSC_VER)
   template <typename... E, std::size_t N = sizeof...(/* THIS INSTEAD: */ E)>
   inline auto hgrid(float const(&coords)[N], E&&... elements)
#else
```
The compiler says that ```elements``` refers to the namespace, thus it cannot take its ```sizeof...```.

**Comment by djowel** [comment]
Right... Could you do a PR please? 

Which version of MSVC, BTW? I'm curious why CI is passing the build...

**Comment by petiaccja** [comment]
It's version 19.26.28806 (latest as of today). The build works just fine, but when I tried to use the library in my own app, it didn't compile. I did not compile the examples.

I can do a PR but it's a little overkill, it's really just the 2 words in the 2 lines.

**Comment by djowel** [comment]
> I can do a PR but it's a little overkill, it's really just the 2 words in the 2 lines.

I know. I just want to track changes with PRs as much as possible, even for the smallest changes, so the author of the commit will be you, instead of me.

**Comment by djowel** [comment]
> > I can do a PR but it's a little overkill, it's really just the 2 words in the 2 lines.
> 
> I know. I just want to track changes with PRs as much as possible, even for the smallest changes, so the author of the commit will be you, instead of me.

That said, of course I'll do it if you prefer.

**Comment by petiaccja** [comment]
No worries. I've sent you a PR here: https://github.com/cycfi/elements/pull/161/commits.
