### ISSUE TITLE
Elements fails to open absolute paths.

### ISSUE THREAD

**Issue by pumkinpal** [cycfi/elements#164]
I observed this behaviour when copying the hello_universe example and changing the image path to an absolute path.

The issue occurs in the function `cycfi::elements::find_file`.

```
std::string find_file(std::string_view file)
{
  std::string full_path;
  if (fs::path(file.data()).is_absolute())
  {
     if (fs::exists(full_path))
        full_path = file;
  }
  else
  {
     for (auto const& path : resource_paths)
     {
        fs::path target = fs::path(path) / file.data();
        if (fs::exists(target))
        {
           full_path = target.string();
           break;
        }
     }
  }
  return full_path;
}
```
In this function when `file` is found to be an absolute path, `fs::exists` is called on the uninitialized string `full_path` which will always return false.

**Comment by djowel** [comment]
> In this function when `file` is found to be an absolute path, `fs::exists` is called on the uninitialized string `full_path` which will always return false.

Have you tried develop? I think this has been fixed:

https://github.com/cycfi/elements/blob/develop/lib/src/support/resource_paths.cpp#L15-L37

**Comment by pumkinpal** [comment]
Yeah, sorry my mistake. I assumed that master was the most up-to-date branch. Thanks for the quick reply.

**Comment by djowel** [comment]
> Yeah, sorry my mistake. I assumed that master was the most up-to-date branch. Thanks for the quick reply.

I should probably merge to master soon.
