### ISSUE TITLE
infra twice in elements src tree

### ISSUE THREAD

**Issue by sergioferrari** [cycfi/elements#167]
Hi, I downloaded the source code of elements from github.
Why is the external infra library replicated twice in the elements source code?
Under the lib directory we note the following src tree structure:
<pre>
lib
 |
 +--external
 +--host
 +--include
 +--infra
 +--json
 |   |
 |   +--infra
 |
 +--src
</pre>``

**Comment by djowel** [comment]
Long story... Anyway, that will not be the case anymore once no-boost-deps branch is merged to develop and master. Check the branch. I'll close this now...
