### ISSUE TITLE
SetProcessDpiAwareness breaks Win32 builds

### ISSUE THREAD

**Issue by DerekSauer** [cycfi/elements#170]
When building in Windows the linker is unable to find SetProcessDpiAwareness() used in [/host/windows/app.cpp](https://github.com/cycfi/elements/blob/master/lib/host/windows/app.cpp) because the WIN32_LEAN_AND_MEAN definition removes the header file containing that function. The header is added back in app.cpp (shellscalingapi.h) but Shcore.lib which the linker is looking for remains missing. I'm not really sure why it is present when WIN32_LEAN_AND_MEAN is not defined but gone when it is; probably a check CMake does, I don't know for sure.

Removing WIN32_LEAN_AND_MEAN will of course break Asio since Windows.h includes Winsock.h.

Adding a target link to Shcore.lib in element's [CMakeList](https://github.com/cycfi/elements/blob/master/lib/CMakeLists.txt) clears up the issue. 

`
if (WIN32)
  target_link_libraries(elements PUBLIC Shcore)
endif()
`

**Comment by djowel** [comment]
Thanks for noting, @DerekSauer. Would you be so kind as to file a PR for this? I know this is a very easy fix, but I want to keep track of the changes from "issues" via PRs, and reflect the commit author as well.

**Comment by DerekSauer** [comment]
Oh course, happy to. #171 #

**Comment by djowel** [comment]
> Oh course, happy to. #171

Wonderful!

**Comment by Xeverous** [comment]
@DerekSauer note that for MinGW there might be a different issue: certain Windows functions are only defined when you compile against newer Windows version (the default one is same as native on which MinGW is running) (http://www.mingw.org/wiki/Use_more_recent_defined_functions)

@djowel I'm a bit busy now, I see you replied to my issue on the layout, I will test it when I have time.
