### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by arximboldi** [cycfi/elements#175]
Hi!

This project looks excellent. These days I am using QML mostly but I am always looking for new ways to write UI's for applications with a C++ core. I am particularly interested in integrating this with [Lager](https://github.com/arximboldi/lager) and [Immer](https://github.com/arximboldi/immer), let's say how it goes...

Anyway, my question is: I haven't seen anything in the framework particularly tailored towards animation. It would be nice to hear your thoughts on how to integrate that on the API, and also in the general case on the development of custom components/elements with their own additional state.

**Comment by djowel** [comment]
> This project looks excellent. These days I am using QML mostly but I am always looking for new ways to write UI's for applications with a C++ core. I am particularly interested in integrating this with [Lager](https://github.com/arximboldi/lager) and [Immer](https://github.com/arximboldi/immer), let's say how it goes...

Interesting libraries! Very nice!

> Anyway, my question is: I haven't seen anything in the framework particularly tailored towards animation. It would be nice to hear your thoughts on how to integrate that on the API, and also in the general case on the development of custom components/elements with their own additional state.

Yes, that is one aspect not handled explicitly. My thinking was that 1). Keep it as simple as possible and 2) Additional "features" are orthogonal and can be taken as separate libraries on top of Elements, so long as the proper low-level facilities are in place. To me, that would be ASIO and ASIO's timers, which is one reason why I insist on having it as part of the foundation.

Let's start with a good API and let's see how Element's foundation can support that. Do you have particular ideas?

**Comment by djowel** [comment]
> > I am particularly interested in integrating this with [Lager](https://github.com/arximboldi/lager) and [Immer](https://github.com/arximboldi/immer), let's say how it goes...
> 
> Interesting libraries! Very nice!

Aside: I think you have some very interesting ideas there! I'm going to read and learn more about your work.

**Comment by arximboldi** [comment]
Thankss @djowel for the fast response :)

I agree with the general principle of keeping a core "basis" that allows other things to be built on top, it is one of the things that's very attractive about this project! (Plus your credentials as boost contributor ;))

With animation though, it might not be enough to rely simply on external timers (e.g. ASIO), since ideally you want to drive the animation from the UI thread (or the render thread, which in some frameworks like QML is a separate one), using potentially vsync to determine your frame delta time. (In this sense, I think we both work on real time audio stuff, modern graphics is looking more and more like audio processing ;)) For this purpose it is good to have some high level constructions to combine and compose animations:
```
shared_ptr<thing> x = ...; 
view.run(parallel(sequence(linear(x, &thing::width, 0, 10, 200ms),
                                            exp(x, &thing::color, blue, red, 150ms)),
              sigmoid(y, &thing::opacity, 1, 1, 500ms)));
```
Then there is a simple scheduler that "ticks" these animations on render. I have built similar API's to this one in the past for some engine and it is not tooo hard (famous last words haha). However, this is just a starting point.

One thing I like about QML also, is to be able to express "behaviors". This is, animations that are applied to a property whenever it changes. You can also do that in CSS, I reckon. It is quite useful to separate the animation design from the layout, etc. However how to express that in C++ may be a bit more tricky, I haven't explored your library enough yet to have specific suggestion in this regard. One idea that comes to mind is that maybe one can use the setter of a value to specify a behavior too, as a factory for an animation: over a property.
```
x.opacity([] (auto self, auto curr, auto next) { 
   return linear(self, curr, new, 100ms);
});
```

**Comment by djowel** [comment]
> since ideally you want to drive the animation from the UI thread

The view already exposes a post member function that is guaranteed to be called in the UI thread. Currently it sits at 60fps, but I plan to bump that to 1ms for finer resolution. That can already be used for simple animations as-is, but a separate sub-library specialized for scheduling animations would be good to have.

Yes, I think a higher-level scheduler can be built on top of that.

**Comment by arximboldi** [comment]
Oh, I see. Nice!

**Comment by djowel** [comment]
I'll see if I can squeeze some time to do a simple animation demo.

**Comment by djowel** [comment]
Better late than never. I added a simple animation example in develop:
https://github.com/cycfi/elements/blob/develop/examples/simple_animation/main.cpp

There is an ongoing work on changing the canvas API to using more performant graphics libraries such as skia. See https://github.com/cycfi/artist. By then, we will see more improvements on real time performance. For now, simple animations such as this example should suffice.

**Comment by arximboldi** [comment]
Thanks @djowel !
