### ISSUE TITLE
MVC advice

### ISSUE THREAD

**Issue by Radagan** [cycfi/elements#180]
Considering the heavy use of auto when compositing UIs, how does one structure a complex UI where the screens (MVC views) are delegated to different classes? 

I've tried a couple of different ways to do this, including passing a view& and letting the class set the contend, but that gave very strange errors related to fontconfig file missing. 

I thought I'd just ask for what the best practice was for elements.

I really like this UI library and I'm glad to be working with it again after being pulled away on another project.

**Comment by djowel** [comment]
You can capture any complex element using `share(e)` where e is any complex element. That can be captured as a std::shared_ptr<element> and placed as a member in your class.

**Comment by Radagan** [comment]
Thank you for the quick reply. I didn't make the connection between share() and std::shared_ptr<element> though in hindsight it's a pretty obvious oversight on my part. 

Unfortunately, I still get an odd error at runtime:

```
C:\Users\Radagan\Development\cpp\SOFarmer\cmake-build-debug\SOFarmer.exe
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Exception: Exception 0xc0000005 encountered at address 0x6c23ed: Access violation reading location 0x0000000b
Exception: Exception 0xc0000005 encountered at address 0x6c23ed: Access violation reading location 0x0000000b
Exception: Exception 0xc0000005 encountered at address 0x6c23ed: Access violation reading location 0x0000000b
Exception: Exception 0xc0000005 encountered at address 0x6c23ed: Access violation reading location 0x0000000b
Exception: Exception 0xc0000005 encountered at address 0x6c23ed: Access violation reading location 0x0000000b

Process finished with exit code 0
```

When I create the UI in the main class that owns the app, window, and view, it works fine, but when I delegate the content creation to a separate class, the above error happens and the window immediately closes. I'm in the master branch and my fork is up to date with the elements repo. 

Here's my view classs:

```
using namespace cycfi::elements;

namespace lp {
    class MainView {
    public:
        MainView();

        std::shared_ptr<element> render_main();
    };
}
```

cpp:
```
namespace lp {
    MainView::MainView() {}

    std::shared_ptr<element> MainView::render_main() {
        auto bkd_color = rgba(62, 62, 62, 255);
        auto background = box(bkd_color);
        auto plots = align_left(scroller(box(colors::transparent.opacity(0.5))));

        auto aligns = margin({10, 10, 10, 10},
             htile(
                 margin({10, 10, 10, 10},
                        group("Sections & Beds", plots, 0.9, false)
                 ),
                 margin({10, 10, 10, 10},
                        group("Details", margin({20, 40, 30, 30}, basic_text_box{"I'm a detail!"}), 0.9,
                              false)
                 )
             )
        );

        auto top = align_right(fixed_size({30, 30}, box(colors::transparent.opacity(0.5))));
        auto content = hold_any(share(aligns));
        auto main_pane = pane(top, link(content), false);
        auto main_element = margin({10, 10, 10, 10}, main_pane);

        return share(main_element);
    }
}
```

Any idea what's going on?

**Comment by djowel** [comment]
Can you provide an MVCE?

**Comment by Radagan** [comment]
No problem. I replaced the HelloUniverse example with this code and the failure reproduces:

Console Error:
```
C:\Users\Radagan\Development\cpp\libs\hello_universe\cmake-build-debug\HelloUniverse.exe
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Exception: Exception 0xc0000005 encountered at address 0x100b861: User-mode data execution prevention (DEP) violation at location 0x0100b861
```

Code:
```
#include <elements.hpp>

using namespace cycfi::elements;

class MainView {
public:
    MainView();

    std::shared_ptr<element> render_main();
};

MainView::MainView() {}

std::shared_ptr<element> MainView::render_main() {
    auto bkd_color = rgba(62, 62, 62, 255);
    auto background = box(bkd_color);
    auto plots = align_left(scroller(box(colors::transparent.opacity(0.5))));

    auto aligns = margin({10, 10, 10, 10},
         htile(
             margin({10, 10, 10, 10},
                    group("Sections & Beds", plots, 0.9, false)
             ),
             margin({10, 10, 10, 10},
                    group("Details", margin({20, 40, 30, 30}, basic_text_box{"I'm a detail!"}), 0.9,
                          false)
             )
         )
    );

    auto top = align_right(fixed_size({30, 30}, box(colors::transparent.opacity(0.5))));
    auto content = hold_any(share(aligns));
    auto main_pane = pane(top, link(content), false);
    auto main_element = margin({10, 10, 10, 10}, main_pane);

    return share(main_element);
}

int main(int argc, char* argv[])
{
    app _app(argc, argv, "Text and Icons", "com.cycfi.text-and-icons");
    window _win(_app.name());
    _win.on_close = [&_app]() { _app.stop(); };

    view view_(_win);

    MainView main_view{};

    view_.content(
        main_view.render_main()
    );

    _app.run();
    return 0;
}
```

**Comment by Radagan** [comment]
@djowel Is that what you meant by MVCE? Just copy the HelloUniverse example outside the elements project and replace the main.cpp with the code above to reproduce the problem.

**Comment by djowel** [comment]
> @djowel Is that what you meant by MVCE? Just copy the HelloUniverse example outside the elements project and replace the main.cpp with the code above to reproduce the problem.

Yes it is! :-)

Is this on Windows? I can check it on my scheduled Windows dev. Also, does this not happen with plain/unchanged HelloUniverse example outside the elements project? I suspect it is a separate issue.

**Comment by Radagan** [comment]
Thanks, I wasn't sure. You're correct, the error is on Windows 10 with latest Updates, and normal HelloUniverse works fine outside of elements. 

Would it be helpful for me to confirm the bug on macOS Mojave? I haven't tried to build yet there, but I could. I'm not sure what your test resources look like--I'm very new to this project. But I don't mind helping if needed. I definitely need a C++ cross-platform UI library, and I really don't want to go back to wxWidgets.  

Thank you very much for making this available and under an MIT license. You've done a ton of work here and the code quality is inspiring.

**Comment by Radagan** [comment]
@djowel Btw, do you recommend my working in master or develop for production code? Often it is a version tag under master, but I thought I would ask since elements seems to have a lot of active work being done.

**Comment by Xeverous** [comment]
@Radagan generally PRs are done on develop. Bigger changes are on separate branches, then merged to develop. If unsure what is considered big just look at my contributions.

**Comment by Radagan** [comment]
@Xeverous Hi Xeverous! Thanks. That makes sense, but you're a major contributor to the library. As I am just coming up to speed and using the library for production, should I stick with master or latest develop? That's more my question. Good to know that any PR I create would go against develop though.

**Comment by djowel** [comment]
> @Xeverous Hi Xeverous! Thanks. That makes sense, but you're a major contributor to the library. As I am just coming up to speed and using the library for production, should I stick with master or latest develop? That's more my question. Good to know that any PR I create would go against develop though.

The goal is to have master be stable, once we reach a certain milestone. Develop is the one with more active changes happening. Users typically should just use master. Perhaps we can aim for a version tag soon.

**Comment by djowel** [comment]
> Thanks, I wasn't sure. You're correct, the error is on Windows 10 with latest Updates, and normal HelloUniverse works fine outside of elements.

That is odd. Internally, `view_.content(...)` uses shared elements. I'll go check as soon as I can.

**Comment by djowel** [comment]
> Thank you very much for making this available and under an MIT license. You've done a ton of work here and the code quality is inspiring.

Thank you very much for the kind words. Such comments make this project a lot more inspiring to do :-)

**Comment by Xeverous** [comment]
@Radagan I'm using develop because almost all of my contributions were motivated by my needs. The API is changing often and I want to work with the bleeding edge when new things are available.

**Comment by Radagan** [comment]
@djowel No problem--I really meant them. After coming back to modern C++ after many years away, this library is a wonderful discovery. I second your goals for it wholeheartedly as laid out in the docs. These are not spectator words either. This is the first open source project I've felt a strong desire to contribute to. 

For now I need to use elements for my project and come up to speed on how it works, but in time I'm sure I can help move it along. Besides, once it is my project's UI library, you will have me by the code! So, if you have guidelines or expectation from contributors please let me know. I'm pretty new to open source projects in general. I've developed for over two decades, but always on closed source efforts as an employee, contractor, or as an independent. 

@Xeverous Understood. Sounds like I should give develop a try.

**Comment by Radagan** [comment]
@djowel Have you had a chance to look into this issue?

**Comment by djowel** [comment]
> @djowel Have you had a chance to look into this issue?

I plan to do that today, but  have you tried develop? I typically use shared_ptr in my other projects using elements and have had no problems at all. In fact the latest example also uses shared: https://github.com/cycfi/elements/blob/develop/examples/simple_animation/main.cpp#L34

**Comment by djowel** [comment]
> I plan to do that today

Update. I can repro the crash. Hrmmm... Investigating...

**Comment by djowel** [comment]
Ah here's your bad boy: `link(content)`.  Let me reformulate the code...

**Comment by djowel** [comment]
So to be clear, `link` creates a reference to the one linked to (e.g. `content`). If you do that, better make the referenced element's lifetime persist beyond the lifetime of the "referencee". In this case it se happens that the while the lifetime of `* content ` is good, the lifetime of`& content` is a temporary.

**Comment by djowel** [comment]
Feel free to close when you can.

**Comment by Radagan** [comment]
Ah, of course! Thank you.

**Comment by Xeverous** [comment]
> Update. I can repro the crash. Hrmmm... Investigating... Seems like lifetime issues.

@djowel coming back to the repository; what do you think about documenting lifetime management in elements? I get now how `link`, `share` and `hold` works, but for beginner library users (who do not know the implementation) incorrect use of these lifetime-managing functions can result in 2 bad things:

1. hard to understand compilation errors (missed overloads, especially when using deep template factories)
2. runtime problems (crashes)

By "documenting" I actually meant some guideline when to use each of mentioned functions. Ideally, one could only use these and never copy any element.

**Comment by djowel** [comment]
Absolutely! I am currently writing another document: "Basic Building Blocks" that details the 'lego' like building blocks such as these and the basic elements (e.g. buttons, images, and so on).
