### ISSUE TITLE
Adding other UI then background and image blocks elements

### ISSUE THREAD

**Issue by cansik** [cycfi/elements#182]
I would like to include elements into an existing application as a cmake subproject. I am working on MacOS where I also had to include the Cocoa libraries, otherwise they are not linked (I also followed the thread here https://github.com/cycfi/elements/issues/95).

Everything runs fine now, I can open a window and display a `background` or even an `image`. But as soon as I would like to add **any other control** (maybe the ones that use os-specific components), elements blocks and does not give any output or creating a window. I have tried with `label` and `scroller`.

Here is my cmake file (maybe I have imported something the wrong way):
https://github.com/cansik/mirrorly/blob/ui/CMakeLists.txt

Would be great if you could give me a hint into a further direction.

**Comment by Xeverous** [comment]
This issue occurs only on MacOS, right?

**Comment by djowel** [comment]
Hmmm... Do you think you can make an MVCE for this that I can try? Maybe a stand-alone minimal cmake project?

**Comment by cansik** [comment]
@Xeverous I could not test it yet on another os.
@djowel Of course, I've created a project which you can find here: https://github.com/cansik/elements-example

It seems that elements is trying to include cocoa (two times?), but it is not included when linking, so I added it [manually](https://github.com/cansik/elements-example/blob/master/CMakeLists.txt#L24) in cmake:

```
-- Link-time optimization disabled for elements
-- building elements with cocoa host UI library
-- Link-time optimization disabled for elements
-- building elements with cocoa host UI library
-- Configuring done
-- Generating done
```

**Comment by cansik** [comment]
@Xeverous  Finally I could test it under Windows and yes here it is working fine. It's an OSX problem I guess.

**Comment by djowel** [comment]
> @Xeverous Finally I could test it under Windows and yes here it is working fine. It's an OSX problem I guess.

I'll go check later today.

**Comment by djowel** [comment]
> > @Xeverous Finally I could test it under Windows and yes here it is working fine. It's an OSX problem I guess.
> 
> I'll go check later today.

Hmmm, I'm probably misunderstanding. What do you mean by "as soon as I would like to add any other control (maybe the ones that use os-specific components), elements blocks and does not give any output or creating a window", and how and where does that happen here: https://github.com/cansik/elements-example/blob/master/main.cpp ?

**Comment by djowel** [comment]
OK, please try using develop (Note: I will merge to master later).

**Comment by djowel** [comment]
> OK, please try using develop (Note: I will merge to master later).

Oh and this is the correct cmake file:

```
cmake_minimum_required(VERSION 3.16)
project(elements_example LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 17)

# elements
set(ELEMENTS_ROOT ${PROJECT_SOURCE_DIR}/elements)
get_filename_component(ELEMENTS_ROOT "${ELEMENTS_ROOT}" ABSOLUTE)
set (CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${ELEMENTS_ROOT}/cmake")

set(ELEMENTS_BUILD_EXAMPLES OFF)

# If we are building outside the project, you need to set ELEMENTS_ROOT:
if (NOT ELEMENTS_BUILD_EXAMPLES)
   include(ElementsConfigCommon)
   set(ELEMENTS_BUILD_EXAMPLES OFF)
   add_subdirectory(${ELEMENTS_ROOT} elements)
endif()

set(ELEMENTS_APP_PROJECT "Elements_Example")
set(ELEMENTS_APP_TITLE "Elements Example")
set(ELEMENTS_APP_COPYRIGHT "Copyright (c) 2020 cansik")
set(ELEMENTS_APP_ID "ch.cansik.example")
set(ELEMENTS_APP_VERSION "1.0")

set(ELEMENTS_APP_RESOURCES)

include(ElementsConfigApp)

```

**Comment by djowel** [comment]
@cansik, is this still an issue with the correct cmake above? Or can we close this now?

**Comment by cansik** [comment]
@djowel develop branch with the [provided](https://github.com/cycfi/elements/issues/182#issuecomment-663920600) cmake works! Thank you very much!
