### ISSUE TITLE
Alternative control method for dial

### ISSUE THREAD

**Issue by jpcima** [cycfi/elements#184]
Hi, there is a user request for a different way of manipulating dials by mouse.

The value is increased or decreased according to the distance from the click origin. (the Manhattan distance I believe)
Moving up and right increases, left and down decreases.

Additionally the dial may have other properties
- it can be associated with a default value, that a click with the middle button can reset to
- a modifier key can allow finer control of the edited value when pressed (shift?)

As I understand, some users of musical software feel more familiar with this paradigm.

**Comment by djowel** [comment]
I knew someone would ask soon :-) Would you like to do some coding? Feel free to add the "manhattan" behavior. I suggest that the rotary or "Manhattan" behavior be a theme variable, so it can be use configurable.

Your other suggestions are also cool! Would you be interested to code that in?

**Comment by jpcima** [comment]
Yes no problem, I try to implement this functionality later today.
This must not be very difficult from what I remember of it.
