### ISSUE TITLE
building on linux

### ISSUE THREAD

**Issue by labidus** [cycfi/elements#191]
It's probably me, but I followed the instruction, for linux

It's say to make a build folder and invoke cmake.

So it create a CMakeCache.txt in the build folder.

Later you say open it with CLion. I don't use this editor and it's not free and I suppose it is not working on LINUX anyway.

I try to build the makefile using make, but I get an error: CMakeCache.txt:17: *** missing separator.  Stop.

I would appreciate to know what to do :)

Thank you, I like your project anyway, cannot wait to test it and use it!

**Comment by djowel** [comment]
CLion is optional. CMake is a build generator. You do not make using the CMakeCache.txt. If successful, cmake should generate Unix Make files in the build directory.

**Comment by labidus** [comment]
Ok so the build folder does not have any other file than (CMakeCache.txt and some folders)

So the unix make file was not generated. I did not see error, I will re-do the opetation tonight to see if I don't see any issues using cmake... 

Thank you I will keep you updated!

**Comment by redtide** [comment]
@labidus maybe you made a normal, non [recursive] clone and you miss a `git submodule update --init --recursive` step? Elements requires the infra library. CMake should tell you in the log if something went wrong.

[recursive]: https://cycfi.github.io/elements/setup#git

**Comment by labidus** [comment]
I did not use git, I downloaded the source apply this:

sudo apt-get install libcairo2-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install libboost-all-dev
sudo apt-get -y install cmake

cd elements
mkdir build
cd build
cmake -G "Unix Makefiles" ../

**Comment by labidus** [comment]
I will setup this projet with git tonight, with package manager, that will be probably best, I only used the source, at first I wanted just to test your lib :)

**Comment by redtide** [comment]
I'm just an user like you, just had that intuition based on some experience. AFAIK GitHub doesn't include git submodule dependencies in their tarballs, so it seems the issue is the same.

**Comment by labidus** [comment]
ok it worked using the GIT version INSTEAD of downloading the lib thank you!
