### ISSUE TITLE
Example in linux not recognised as program (but it is, screenshot)

### ISSUE THREAD

**Issue by labidus** [cycfi/elements#194]
Here an image of the issue, I was able to get the source with GIT, compile it on linux, all examples in the build folder does not work.

The example of my screenshot show Dialogs (build program file), the allow executing file as program is on but when I click or run on command line does not work, not recognised as program.

![app-not-running](https://user-images.githubusercontent.com/10580216/88608340-8b858a80-d04f-11ea-83e7-1690113825f9.png)

**Comment by labidus** [comment]
Result are fine when I look at it

[ 58%] Building CXX object examples/empty/CMakeFiles/EmptyStarter.dir/main.cpp.o
[ 60%] Linking CXX executable EmptyStarter
[ 60%] Built target EmptyStarter
Scanning dependencies of target HelloUniverse
[ 61%] Building CXX object examples/hello_universe/CMakeFiles/HelloUniverse.dir/main.cpp.o
[ 62%] Linking CXX executable HelloUniverse
[ 62%] Built target HelloUniverse
Scanning dependencies of target TextAndIcons
[ 64%] Building CXX object examples/text_and_icons/CMakeFiles/TextAndIcons.dir/main.cpp.o
[ 65%] Linking CXX executable TextAndIcons
[ 65%] Built target TextAndIcons
Scanning dependencies of target Buttons
[ 67%] Building CXX object examples/buttons/CMakeFiles/Buttons.dir/main.cpp.o
[ 68%] Linking CXX executable Buttons
[ 68%] Built target Buttons
Scanning dependencies of target Menus
[ 70%] Building CXX object examples/menus/CMakeFiles/Menus.dir/main.cpp.o
[ 71%] Linking CXX executable Menus
[ 71%] Built target Menus
Scanning dependencies of target BasicSlidersAndKnobs
[ 72%] Building CXX object examples/basic_sliders_and_knobs/CMakeFiles/BasicSlidersAndKnobs.dir/main.cpp.o
[ 74%] Linking CXX executable BasicSlidersAndKnobs
[ 74%] Built target BasicSlidersAndKnobs
Scanning dependencies of target SpriteSlidersAndKnobs
[ 75%] Building CXX object examples/sprite_sliders_and_knobs/CMakeFiles/SpriteSlidersAndKnobs.dir/main.cpp.o
[ 77%] Linking CXX executable SpriteSlidersAndKnobs
[ 77%] Built target SpriteSlidersAndKnobs
Scanning dependencies of target TextEdit
[ 78%] Building CXX object examples/text_edit/CMakeFiles/TextEdit.dir/main.cpp.o
[ 80%] Linking CXX executable TextEdit
[ 80%] Built target TextEdit
Scanning dependencies of target Layout
[ 81%] Building CXX object examples/layout/CMakeFiles/Layout.dir/main.cpp.o
[ 82%] Linking CXX executable Layout
[ 82%] Built target Layout
Scanning dependencies of target Popups
[ 84%] Building CXX object examples/popups/CMakeFiles/Popups.dir/main.cpp.o
[ 85%] Linking CXX executable Popups
[ 85%] Built target Popups
Scanning dependencies of target Dialogs
[ 87%] Building CXX object examples/dialogs/CMakeFiles/Dialogs.dir/main.cpp.o
[ 88%] Linking CXX executable Dialogs
[ 88%] Built target Dialogs
Scanning dependencies of target Scale
[ 90%] Building CXX object examples/scale/CMakeFiles/Scale.dir/main.cpp.o
[ 91%] Linking CXX executable Scale
[ 91%] Built target Scale
Scanning dependencies of target Typography
[ 92%] Building CXX object examples/typography/CMakeFiles/Typography.dir/main.cpp.o
[ 94%] Linking CXX executable Typography
[ 94%] Built target Typography
Scanning dependencies of target Notebook
[ 95%] Building CXX object examples/notebook/CMakeFiles/Notebook.dir/main.cpp.o
[ 97%] Linking CXX executable Notebook
[ 97%] Built target Notebook
Scanning dependencies of target Aspects
[ 98%] Building CXX object examples/doc_aspects/CMakeFiles/Aspects.dir/main.cpp.o
[100%] Linking CXX executable Aspects
[100%] Built target Aspects

**Comment by djowel** [comment]
I am not sure how I can help you, but there is something definitely wrong in the way you are running the examples. 

I don't think this is an elements "issue". The examples should be running just fine.

**Comment by labidus** [comment]
I am using the latest linux mint 20 version, the file is not valid as program. 

The only way I see it is maybe it worked sometime ago, but it does no longer work now for some reason, using make. :)

I mean it's just a program, i double click a popup tell me it is not a program. same on command line.

I will try one using code::block to see if I get different result...

**Comment by labidus** [comment]
Ok I got it, the issue was I am new to linux, since it is GTK, the application cannot run on double click, need a .desktop file to specify the application type

and from the console let say I want to start dialogs I need to do this ./dialogs

Not quite sure why the application cannot "define" the application type when building from GTK, but it's seam the way linux work :)
