### ISSUE TITLE
input_box has too wide text selection

### ISSUE THREAD

**Issue by redtide** [cycfi/elements#197]
This can be seen in the TextAndIcons example, by trying to select also the placeholder text and drag the mouse on the right for some distance.
I'm not sure if I got this right, but it seems related to the hard-coded size of the scroller in [gallery/text_entry.hpp], which should be relative to the text size instead.

[gallery/text_entry.hpp]: https://github.com/cycfi/elements/blob/develop/lib/include/elements/element/gallery/text_entry.hpp#L34

**Comment by djowel** [comment]
Fix in develop. Please verify and close.

**Comment by redtide** [comment]
Thank you, very quick!
