### ISSUE TITLE
UTF-8 font face(such as chinese) is not supported

### ISSUE THREAD

**Issue by faywong** [cycfi/elements#198]
```c++
   struct text_info
   {
      uint32_t codepoint;
      int      modifiers;
   };

// file: base_view.mm
- (void) insertText:(id)string replacementRange : (NSRange)replacementRange
{
   auto*       event = [NSApp currentEvent];
   auto const  mods = ph::translate_flags([event modifierFlags]);
   auto*       characters = ([string isKindOfClass:[NSAttributedString class]]) ?
                 [string string] : (NSString*) string;

   NSUInteger i, length = [characters length];
   for (i = 0;  i < length;  i++)
   {
     unichar codepoint = [characters characterAtIndex:i];

...
}
```

This will be utf-16 encoded string(in mac os platform) which is not supported by cairo which is only utf-8 aware.

**Comment by djowel** [comment]
Would you like to propose a patch? E.g. convert utf-16 to utf-8?

**Comment by faywong** [comment]
> Would you like to propose a patch? E.g. convert utf-16 to utf-8?

yes, i am debugging the func ``codepoint_to_utf8()`` in text_utils.cpp now.

```c++
std::string codepoint_to_utf8(unsigned codepoint) {
...
}
```

**Comment by faywong** [comment]
update1: i have fixed the utf8 encoding problem, now i continue to figure the multiple unicode char sumbited from IME issue.

**Comment by faywong** [comment]
![image](https://user-images.githubusercontent.com/1934627/90123700-d9a9c600-dd91-11ea-8677-634b3797bf1d.png)

![image](https://user-images.githubusercontent.com/1934627/90123754-eaf2d280-dd91-11ea-87a3-bc533089156a.png)

what i have done, you have done yet.

**Comment by faywong** [comment]
what i can do is contributing a verify case:

![image](https://user-images.githubusercontent.com/1934627/90124039-56d53b00-dd92-11ea-8874-302115242ff6.png)

**Comment by redtide** [comment]
I was wondering, what about merging the example in a single app?

**Comment by djowel** [comment]
> I was wondering, what about merging the example in a single app?

Yes, that would be better. I'll see what I can do. Perhaps the example should just use the chinese font with some chinese text in the example.

Also, I changed the code a bit. @faywong , can you check develop branch?

1. It's better to specify the font in the constructor instead of overriding the theme:

https://github.com/cycfi/elements/blob/develop/examples/text_edit_with_chinese_char/main.cpp#L28-L34

2. For some reason, the font won't match in MacOS if I use "文泉驿微米黑" as font family name. It matches "WenQuanYi Micro Hei" though, so I added that in the font_descr example:

```c++
char const* font_family = "文泉驿微米黑, \"WenQuanYi Micro Hei\"";
```

so it will try to match both names.

3. I had the change font.cpp parsing of font family names to allow double-quoted names.

**Comment by redtide** [comment]
I thought about simply add it on the original example (mixed content), something like this
![immagine](https://user-images.githubusercontent.com/1171962/90312196-b9e5df80-df02-11ea-8cff-b8c415730177.png)

**Comment by djowel** [comment]
> I thought about simply add it on the original example (mixed content), something like this

Yes, exactly.

**Comment by djowel** [comment]
> > I thought about simply add it on the original example (mixed content), something like this
> 
> Yes, exactly.

Done.

**Comment by djowel** [comment]
@faywong , please verify and close if everything is OK.

**Comment by faywong** [comment]
> @faywong , please verify and close if everything is OK.

Yes, i verified your develop branch right now. It works as expected.

There is an input event handle conflict issue when chinese input method is active(for example backspace is handled both in input method and Elements TextEdit widget, expect to handled in input method panel).  I will dig it later.
