### ISSUE TITLE
broken flow layout

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#205]
The following patch breaks flow example:

```diff
diff --git a/examples/layout/main.cpp b/examples/layout/main.cpp
index c97e5c3..c98690e 100644
--- a/examples/layout/main.cpp
+++ b/examples/layout/main.cpp
@@ -165,7 +165,7 @@ auto make_flow()

    auto flow_pane = margin(
       { 0, 50, 10, 10 },
-      align_top(flow(c))
+      deck(align_top(flow(c)), label("label"))
    );

    return margin({ 10, 10, 10, 10 },
```

It stops to lay out any contained boxes, always breaking a line after each of them. Box width has no impact, too short ones will leave huge empty space, too long ones will just overflow and render outside parent element.

**Comment by djowel** [comment]
Given our discussion in discord, I don't think is a bug. See the layout semantics of deck and layer: "The layer’s maximum limit is computed as the minimum of the children elements’ maximum limits."

May I request that you do not flag an issue a "bug" unless you are 100% sure that it is? Thanks!

**Comment by Xeverous** [comment]
Ok, now I understand everything behind this issue.
