### ISSUE TITLE
modern C++: enforcing rule of 5

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#207]
IMO this is an important aspect that can have significant consequences. For reference, the rule of 5 (aka rule of 3 before C++11) says that if you need at least one of:

- non-default dtor
- non-default copy ctor
- non-default move ctor
- non-default copy assignment
- non-default move assignment

...then you probably need all of them.

This rule encourages to create types that fall into specific usage patterns (italic are actual concept names):

- *semiregular* (default all special member functions or all custom)
- (default all except ctor)
- *copyable* (allowed copy, move and destruction)
- *moveable* (custom/default move and destruction, deleted copy)
- *destructible* (non-copyable, non-moveable) - mostly for 1-time-use types in specific design patterns (concurrency)

What are the problems with the library then?

- Elements, like all polymorphic types are prone to slicing. I would like to **make every element non-copyable**. Even moves can potentially slice an object, however the point of moving is having an access to the single use of the instance and such cases pretty much always know the full type of the instance.
- Fix existing types that do not support rule of 5. Example: `window`. This type violates the rule because it has custom destructor but no custom/no deleted copy/move operations - in such case the default copy/move is causing UB. `window` itself should be *moveable* or *destructible*.

**Comment by Xeverous** [comment]
Partially related to this topic, I'm also interested in better/different/custom possibility of separating OS-related types such as window and view (whcih runs an event loop). Right now it doesn't seem really possible to give the user an option to change window style (border, title, miniaturizable etc) because these actions require to destroy a window object. And destroying window object is not possible when the view class runs events and requires window handle in its constructor.

**Comment by djowel** [comment]
These rules should be applied judiciously. The window is a no brainer and should be non-copyable. It is a leaf. And IT IS noncopyable:

    https://github.com/cycfi/elements/blob/master/lib/include/elements/window.hpp#L25

The view too, it is also a leaf:

   https://github.com/cycfi/elements/blob/master/lib/include/elements/base_view.hpp#L292

The elements, on the other hand, no, they need not be, in general. It should probably be applied on a case by case basis.

**Comment by djowel** [comment]
> * Fix existing types that do not support rule of 5. Example: `window`. This type violates the rule because it has custom destructor but no custom/no deleted copy/move operations - in such case the default copy/move is causing UB. `window` itself should be _moveable_ or _destructible_.

Are you not aware of `non_copyable` ?

```c++
class window : non_copyable { ... };
```

**Comment by djowel** [comment]
> Partially related to this topic, I'm also interested in better/different/custom possibility

Let's deal with this separately. Yes, agreed, I'd like that too.

**Comment by Xeverous** [comment]
Window is indeed non-copyable and non-moveable. Mine mistake. How about elements? What do you think about making base `element` class non-copyable?

**Comment by djowel** [comment]
> What do you think about making base `element` class non-copyable?

That's a good question. My answer above was: "The elements, on the other hand, no, they need not be, in general. It should probably be applied on a case by case basis". For example, pixmap is non-copyable (but movable), so image is also non-copyable (but movable). 

Are you suggesting to make elements move only? That might be a good idea, but I am not convinced of the advantages yet. IMO, slicing is a noob issue. Every struct/class is prone to slicing when inheritance comes into play. You, the programmer, are responsible in making sure you do not slice a struct. I always use inheritance and structs and I have had ZERO problems with slicing, after decades doing c++ (e.g. I do inherit from things like std::vector or std::string and all my libraries such as boost.spirit use inheritance and structs all over the place. I've never seen anyone having slicing issues at all). 

Is there anything else besides slicing that you are concerned about?

Elements have mostly value semantics. Most of the time, you hold on to the actual derived type. The old-style OOP using virtual functions is just as a matter of convenience. If I've implemented elements 15 years ago, I wouldn't have used virtual functions and instead use static types and variants, just as I have with my older libraries such as spirit. I've become more practical in time.

**Comment by Xeverous** [comment]
> Is there anything else besides slicing that you are concerned about?

Copying elements. It's generally non-trivial (slicing or virtual clone function + dynamic allocation (easy to forget to implement, which result in cloning a slice)) and I would rather make it clear to library users that one should not copy elements but just construct more of them.

**Comment by djowel** [comment]
> Copying elements. It's generally non-trivial (slicing or virtual clone function + dynamic allocation (easy to forget to implement, which result in cloning a slice)) and I would rather make it clear to library users that one should not copy elements but just construct more of them.

That would be a valid concern, I agree. But at what cost? I fear that usability will suffer. Now you have to move all over the place when before you just use, for example, a local auto variable and copy that into place. The compiler will optimize the copy. I am not sure if the advantage outweighs the cost.

I don't think we are doing any virtual clone, BTW. Could you give me an example? The shared/hold stuff (e.g. composites) are copied by pointer, not virtually cloned.

If you have a use-case, I'd like to see some code. It's easier to reason out with code than discussing in abstract terms.

**Comment by Xeverous** [comment]
> The compiler will optimize the copy.

This is a bit different topic, but do you have any resource that confirms that compilers optimize last of use of the object to move?

> I don't think we are doing any virtual clone, BTW. Could you give me an example?

We aren't. Right now all examples copy the automatic variable by calling it's copy constructor. I wanted only to express that if we go for the virtual `clone`, it will be risky as it's easy to forget to implement this function for any element type which results in calling parent type clone which results in cloning a slice.

**Comment by djowel** [comment]
> > The compiler will optimize the copy.
> 
> This is a bit different topic, but do you have any resource that confirms that compilers optimize last of use of the object to move?

Experience. It's been extensively seen in deep object compositions such as done in value oriented libraries such as Boost.Spirit and Boost.Fusion. It's amazing what the compiler does if you give it as much static information as you can. In fact, I never think of it anymore. But if you do not believe me, try composing/constructing a deep static object and see what the compiler does. This is what's happening in expression template libraries with complex object hierarchies. You do not move, you just copy! Elements is more or less based on experience with expression templates. You have LOTS of small objects that are cheap to copy, often with only very few members and you compose these objects into complex hierarchies.

Move is best suitable for objects that holds resources, but even then, you should just avoid deep copies and just copy handles and pointers. Why do you want deep copy, BTW? I can imagine you want to have value semantics where you can copy a deep hierarchy? If so, make it explicit: `auto x = deep_copy(y); `. Implicit deep copy is not a good idea.

IMO, replacing all copies with moves is premature optimization and will needlessly degrade usability. Take note that we're talking about construction of object hierarchies. Once a complex object is constructed, most of the time, it will end up in a shared pointer stored somewhere. You pass and share the root of shared pointer around. Cheaply.

**Comment by djowel** [comment]
Let me put it this way. I guess you and I both agree that move is best suitable for objects that holds resources, OK? IOTW, plain structs such as `point`, `rect`, `complex` and even `std::array` of plain types do not. They are just copied always. Now, the majority of element objects are just that: plain. If it were not for the virtual functions, they would've just be PODs. 

Now, given that fact, I find it superfluous to force all elements to be non-copyable. Currently the policy is to disallow copies on deep objects like images (they are movable but not copyable). And it makes sense. So, again, as I said, disallowing copy should be applied on a case by case basis, instead of forcing it everywhere. If you notice a certain class can take advantage of being move only, then sure, make it so (the composites perhaps?). But wholesale non-copyable, for all elements is a no-go for me.

**Comment by Xeverous** [comment]
Ok you convinced me, I'm fine with the current state and will close this for now. I have no direct example of any type that has rule-of-5 problems within elements.
