### ISSUE TITLE
stretching behavior

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#208]
This probably isn't a bug, but I don't get why the slider still stretches vertically.

```cpp
        no_vstretch(layer(
            no_vstretch(slider(
                no_vstretch(hsize(10, rbox(colors::medium_blue, 5))),
                vsize(20, box(colors::black)),
                0.5
            )),
            box(colors::black)
        ))
```

**Comment by djowel** [comment]
I think no_vstretch only applies to space allocation in tiles

**Comment by djowel** [comment]
Oh wait... reopening. It might be possible to apply this to align elements as well. I'll see what I can do...

**Comment by djowel** [comment]
Added to https://github.com/cycfi/elements/issues/216
