### ISSUE TITLE
Cropped characters in text_edit sample 

### ISSUE THREAD

**Issue by dirkarnez** [cycfi/elements#215]
![image](https://user-images.githubusercontent.com/26408605/91204878-411f2880-e737-11ea-8570-b443e757b451.png)
![image](https://user-images.githubusercontent.com/26408605/91204929-509e7180-e737-11ea-8b3d-82a117177de8.png)

The letter 'g' is cropped.

**Comment by djowel** [comment]
Nice catch! Will look ASAP.

**Comment by djowel** [comment]
Odd. Again I can't repro in MacOS. Might be Windows thing again. I'll check later.
<img width="961" alt="Screen Shot 2020-08-26 at 9 30 46 AM" src="https://user-images.githubusercontent.com/568094/91244480-07721000-e77f-11ea-8be8-364dd68bd79a.png">

**Comment by djowel** [comment]
> Odd. Again I can't repro in MacOS. Might be Windows thing again. I'll check later.

Ah zooming and looking closely at my screenshot, its seems the "g" is also mildly cropped at the bottom.

**Comment by djowel** [comment]
OK, I'm not 100% sure, but it's looking like a cairo text-layout bug with the chinese font. Try changing the font to an english font like Roboto and notice that it's not cropped. Can you verify? Change this line:

```c++
   char const* font_family = "文泉驿微米黑, \"WenQuanYi Micro Hei\"";
```

```c++
char const* font_family = "Roboto";
```

(Of course you have to remove the chinese text if you change the font.)

**Comment by dirkarnez** [comment]
![image](https://user-images.githubusercontent.com/26408605/91266735-6dbd5980-e7a4-11ea-85ec-66c0ef8e601a.png)

It really is the font issue

**Comment by djowel** [comment]
I'll close this for now, but I'll add an item in the TODO list: we need to create an MVCE and report to the cairo developers. I doubt there will be some action, but we'll see.

**Comment by dirkarnez** [comment]
> I'll close this for now, but I'll add an item in the TODO list: we need to create an MVCE and report to the cairo developers. I doubt there will be some action, but we'll see:
> 
> #216

Sounds like a cairo issue?

**Comment by faywong** [comment]
It's related to the different font & font metrics. I do a simple experiment:

1st: Roboto font + english char:
![image](https://user-images.githubusercontent.com/1934627/91541764-6b4b3300-e94f-11ea-9139-b7a046709beb.png)

2nd: WenQuanYi font + english char:
![image](https://user-images.githubusercontent.com/1934627/91541784-70a87d80-e94f-11ea-9eda-b8d00769c7ad.png)

3rd: WenQuanYi + Chinese char: same to 2nd case
![image](https://user-images.githubusercontent.com/1934627/91541800-74d49b00-e94f-11ea-82da-b88b42d9559e.png)

Per this case, the conclusion is the english font is higher than chinese font. So when explicit chinese is specified(which decides the layout) & fallback english font is used, the english char is rended with crop.
