### ISSUE TITLE
Test cursor handling overhaul branch

### ISSUE THREAD

**Issue by djowel** [cycfi/elements#222]
The "cursor-handling-overhaul" branch contains code with significant changes to the composite cursor member function. Please test the code with the examples hopefully to expose bugs introduced by the changes before I merge to develop.

Build and run the examples and see if there's anything funny going on. These examples in particular: Menus, Dialogs, Popups, and Tooltip (perhaps Scale too) are affected by the changes. Also, try the branch with your app.

https://github.com/cycfi/elements/tree/cursor-handling-overhaul

The branch also contains an improved tooltip element that places the tip at the topmost layer and manages the communication between the main subject and its tooltip as well as changes to the popup element.

**Comment by Xeverous** [comment]
![image](https://user-images.githubusercontent.com/20820409/91658983-fe5da780-eacc-11ea-8231-b268a9fb7384.png)
![image](https://user-images.githubusercontent.com/20820409/91658986-01589800-eacd-11ea-86e4-fcc1f10ff78d.png)

Reproducing: just hovering randomly.

Also, sometines on hover the window changes size and reflows buttons.

**Comment by Xeverous** [comment]
Launch the example and hover option 3 first, the window will resize and reflow.

**Comment by djowel** [comment]
> Launch the example and hover option 3 first, the window will resize and reflow.

Is this stock elements code? Or did you change using flow again?

**Comment by Xeverous** [comment]
Oh shit, forgot to reset working tree after checkouting the branch. No issues with the stock code.

Nonetheless, is such behavior with flow intended?

**Comment by djowel** [comment]
> Oh shit, forgot to reset working tree after checkouting the branch. No issues with the stock code.
> 
> Nonetheless, is such behavior with flow intended?

IDK. I guess not. But I suggest dealing with flow separately. The flow element has not been well-developed, as you've seen, unfortunately. You are actually the first to have used it. I haven't had a use for it in real code, yet. At one point, I intended to use it as the basis for rich text editing, but that was put on hold. Sometime this year, I was actually thinking about removing flow, in the meantime, for lack of actual use.

**Comment by djowel** [comment]
Unless there are objections, I will merge this one to develop now. Let's deal with flow separately -- it is a unique beast.

**Comment by djowel** [comment]
Merged and closing. Many thanks, everyone!
