### ISSUE TITLE
Running on the background

### ISSUE THREAD

**Issue by alandefreitas** [cycfi/elements#223]
Hi,

Great project. Is it possible to create a window without blocking the main thread on Mac OS somehow? Something like:

```cpp
std::thread t([&]() {
    app _app(argc, argv, "Basic Sliders And Knobs",
             "com.cycfi.basic-sliders-and-knobs");
    window _win(_app.name());
    _win.on_close = [&_app]() { _app.stop(); };

    view view_(_win);

    view_.content(make_controls(), background);

    link_controls(view_);
    _app.run();
});
// ... do my work
t.join();
``` 

I'm looking for a way to do that to create a backend [for a plotting library](https://github.com/alandefreitas/matplotplusplus) but I can't seem to find a solution for mac os. These kinds of libraries don't make much sense if they block the main thread. The only solution has been gnuplot but pipes are very inefficient.

**Comment by Xeverous** [comment]
You can hook into built-in "hidden" event loop by inheriting from `view` and overriding `poll`.

**Comment by alandefreitas** [comment]
Cool. Is there an example that does that? Or somewhere in the documentation I can read about that?

**Comment by Xeverous** [comment]
No, but let's have one:

```cpp
class controller : public elements::view
{
public:
        controller(elements::window& w)
        : elements::view(w)
        {
        }

        void poll() override
        {
                elements::view::poll(); // don't remove the implementation

                // -- your code here --
        }
};
```

Also, there is `view::post` that takes a functor and (an optional) time delay, however:

- If you use a timer, there is no guuarantee that `post`ed functor will be run exactly once per frame. Time-based execution is never absolutely precise. This means that 60 FPS animations with it might not reach 60 FPS, or, actually perform duplicate work between renders.
- If you post a functor that reposts itself (with 0 time), you will end with an infinite loop because each time the functor queue is launched, it is drained to empty state. The infinite loop will also happen if the functor's exeuction time is larger than it's self-reposting delay.
- The functor ... must be a functor which can be annoying (lifetime + scope access complication)

You can read a-bit-heated discussions in #209 and (especially) #144 between me (highest-issue/code contributor) and Joel, the library author on this topic.

To me, *blocking event loop that is hidden with no straightforward way to run code between frames* never seemed right, but it's by design and likely it's going to stay, unless you want to use own implementation of `window`, `app` and `view` classes. The only way to hook some code to be done exactly once per frame is sort of hijacking the implementation like this:

**Comment by djowel** [comment]
> * If you use a timer, there is no guuarantee that `post`ed functor will be run exactly once per frame. Time-based execution is never absolutely precise. This means that 60 FPS animations with it might not reach 60 FPS, or, actually perform duplicate work between renders.

That is incorrect. @Xeverous you should not say these things without precise information. Go read about ASIO first. Seems you do not sufficient knowledge about ASIO. BTW, in case you have not noticed yet, the quanta now is 1ms. The only way for you not to reach 60fps (if you specify that duration) is if you have a callback that uses up a lot more time than 1/60th of a second.

> * If you post a functor that reposts itself (with 0 time), you will end with an infinite loop because each time the functor queue is launched, it is drained to empty state. The infinite loop will also happen if the functor's exeuction time is larger than it's self-reposting delay.

Zero time just means that you may execute immediately. Does not have anything to do with infinite loop, unless you (re)post again. Posts are executed only once! Again, read about ASIO. Your information is incorrect. Don't spread wrong information.

**Comment by djowel** [comment]
> I'm looking for a way to do that to create a backend [for a plotting library](https://github.com/alandefreitas/matplotplusplus) but I can't seem to find a solution for mac os. These kinds of libraries don't make much sense if they block the main thread. The only solution has been gnuplot but pipes are very inefficient.

Ignore @Xeverous. He does not know about ASIO. 

Don't put elements in a thread, instead, put your background services in a thread. Your main draw routines must be placed in the main thread. For your "background" tasks, use threads, or better yet, use ASIO IO services. Read about ASIO here: 

https://think-async.com/Asio/asio-1.18.0/doc/

Elements work well with ASIO and uses it underneath. You are guaranteed of thread safety when calling element's view functions, if you need to, via the view::post mechanism. They are guaranteed to be called only in the draw thread.

**Comment by Xeverous** [comment]
> BTW, in case you have not noticed yet, the quanta now is 1ms. The only way for you not to reach 60fps (if you specify that duration) is if you have a callback that uses up a lot more time than 1/60th of a second.

Indeed, sorry, I forgot about quanta change.

>> If you post a functor **that reposts itself (with 0 time)**, you will end with an infinite loop
> Zero time just means that you may execute immediately. Does not have anything to do with infinite loop, **unless you (re)post again**.

IMO my statement is correct: there are exactly 2 conditions for infinite loop with ASIO (and I have stated them):

- functor reposts itself
- functor has time delay smaller than it's execution time

Obviously if these are true, then ASIO is used wrong, however, if one uses a self-reposting functor with a delay I think there is a risk of problems in debuggers: if you stop inside the functor, artificially increasing its exeuction time, the debugger can endlessly get stuck in breakpointing the functor.

**Comment by djowel** [comment]
> MO my statement is correct: there are exactly 2 conditions for infinite loop with ASIO (and I have stated them):
> 
> * functor reposts itself
> * functor has time delay smaller than it's execution time
> 
> Obviously if these are true, then ASIO is used wrong, however, if one uses a self-reposting functor with a delay I think there is a risk of problems in debuggers: if you stop inside the functor, artificially increasing its exeuction time, the debugger can endlessly get stuck in breakpointing the functor.

I don't really know what you are doing, but one thing I know is that you are using ASIO incorrectly if you are calling the poll to perform background tasks as the OP requested, and you immediately provided an incorrect solution. You do not call poll to perform asynchronous background tasks! That is like turning a preemptive app into a cooperative one.

**Comment by djowel** [comment]
> The only solution has been gnuplot but pipes are very inefficient.

ASIO is high performance. Use it. Ignore @Xeverous remarks about using poll. It is not the correct/performant solution.

**Comment by Xeverous** [comment]
> if you are hooking into poll to perform background tasks as the OP requested

I'm hooking into poll to run specific code once per frame, that is, a typical `update(time_delta)` function. I launch long tasks in other threads.

> That is like turning a preemptive app into a cooperative one.

I actually like this one, you have summarized our application design differences very consicely in 1 statement!

> Ignore @Xeverous remarks about using poll. It is not the correct/performant solution.

Right, what I presented is a way to hook into poll to run code on each frame. It's definitely not what to use to launch background tasks, at most, a point to communicate between threads. Perhaps I wasn't clear enough that my example is not for the purpose OP is looking for.

**Comment by djowel** [comment]
> > That is like turning a preemptive app into a cooperative one.
> 
> I actually like this one, you have summarized our application design differences very consicely in 1 statement!

So stop it. Elements is about high performance using the asynchronous model. It is now being used in high performance audio applications which require high bandwidth services at high sampling rates, at least 44100/sec. A cooperative model won't cut it in this modern, multi thread age.

**Comment by djowel** [comment]
OK, to sum it up, here's the recommended thread model:

- Place elements in the mean thread. The GUI needs to be in the main thread.
- Use threads for background services. Ideally use ASIO io_context, which is much more powerful, easier to use, and less error prone.
- In your background thread, use view.poll to communicate with the view; e.g. call some of its member functions as needed.
    - Take note that the most important functions are already using poll underneath (e.g. refresh).
- If you use ASIO, you can also use your background's io_context::post to call some functions/member functions from the main thread, or from elements (e.g. if you are implementing a custom element for drawing something). ASIO's post mechanism guarantees of thread safety and actual post callbacks are made only in the thread the io_context is created in (e.g. element's main thread).

IMO, ASIO is the best concurrency mechanism for modern c++. It is currently the de-facto standard and there's a strong indication that it will be part of the standard in the future. Asio provides the tools to manage operations, without requiring programs to use concurrency models based on threads and explicit locking.

**Comment by alandefreitas** [comment]
Thank you for the answers. And thank you for the library.

**Comment by Xeverous** [comment]
> Take note that the most important functions are already using post underneath (e.g. refresh).

Shouldn't this be documented? That's pretty significant.

**Comment by djowel** [comment]
> > Take note that the most important functions are already using post underneath (e.g. refresh).
> 
> Shouldn't this be documented? That's pretty significant.

Absolutely. Let me add that in the TODO list.

**Comment by djowel** [comment]
> > > Take note that the most important functions are already using post underneath (e.g. refresh).
> > 
> > 
> > Shouldn't this be documented? That's pretty significant.
> 
> Absolutely. Let me add that in the TODO list.

Added. I should also add an example to demystify the asynchronous thread model to avoid further confusion.

**Comment by Xeverous** [comment]
So for such example, I would also like to see how you would code a complex logic between UI and the user state and background tasks - for example, say there are states W, X, Y and Z and:

- X requires periodic polling (mimicking network/time updates etc)
- user can change Y through UI
- user can change W substate through UI, actual W takes a lot of time to compute
- changes to X affect Y
- changes to Y affect Z
- changes to W affect Z
- each of W, X, Y, Z has own UI element that displays something

This should give some pattern how elements are to be used within complex applicatons. When I started, all I had was a mess of capturing lambdas and overlifetime.

**Comment by djowel** [comment]
> So for such example, I would also like to see how you would code a complex logic between UI and the user state and background tasks -

It seems you are asking about async software design, something that should be outside the scope of the examples, which should be kept as simple as possible. If you are interested in the async model, I'd refer you instead to other tutorials, for example to the ASIO docs and tutorials. For example, you ask about periodic polling? Use ASIO timers.
