### ISSUE TITLE
Port Artist to Elements

### ISSUE THREAD

**Issue by djowel** [cycfi/elements#226]
Targets
- [x] MacOS
    - [x] Quartz-2D
    - [x] Skia
- [x] Linux
    - [x] Skia
- [x] Windows
    - [x] Skia

**Comment by djowel** [comment]
- [ ] Skia
- [ ] Quartz-2D

**Comment by Xeverous** [comment]
Asking again, because I haven't seen a clear response: are you planning to strictly base elements on artist or use artist as an example implementation of "elements expected canvas interface" (such as W3C canvas API)?

**Comment by djowel** [comment]
Implementation issues

- [ ] Deal with fallback fonts for fonts not found

**Comment by djowel** [comment]
Skia Issues:

- Colors are a bit different (skia deals with colors a bit differently, but we need to be consistent)

**Comment by djowel** [comment]
- [x] Examples (Quartz 2D)
    - [x] aspects
    - [x] basic_sliders_and_knobs
    - [x] buttons
    - [x] dialogs
    - [x] empty
    - [x] hello_universe
    - [x] layout
    - [x] menus
    - [x] notebook
    - [x] popups
    - [x] scale
    - [x] simple_animation
    - [x] sprite_sliders_and_knobs
    - [x] text_and_icons
    - [x] text_edit
    - [x] tooltip
- [x] Examples (Skia)
    - [x] aspects
    - [x] basic_sliders_and_knobs
    - [x] buttons
    - [x] dialogs
    - [x] empty
    - [x] hello_universe
    - [x] layout
    - [x] menus
    - [x] notebook
    - [x] popups
    - [x] scale
    - [x] simple_animation
    - [x] sprite_sliders_and_knobs
    - [x] text_and_icons
    - [x] text_edit
    - [x] tooltip
