### ISSUE TITLE
Non-blocking app API

### ISSUE THREAD

**Issue by djowel** [cycfi/elements#230]
One of the confusion with elements is the claim that "It should not own the event loop and should be able to co-exist with components within a plugin host such as VST and AU." and people see code like that in the `app`, for example:

```c++
MSG messages;
while (_running && GetMessage(&messages, nullptr, 0, 0) > 0)
{
   TranslateMessage(&messages);
   DispatchMessage(&messages);
}
```

The lack of docs does not help. But the crucial point here is that the `app` **is optional(!)**. There's a reason why it is kept as simple as possible. These hosts are nothing more than exemplars on how you drive your GUI. And certainly, in a plugin setup, you do not need an `app`, and not even a `window`. The `base_view` is all you need. The `base_view` does not have an event loop, but responds to events.

Having said that, a small improvement over the `app` API is to decouple the event processing and provide a non-blocking variant.

**Comment by djowel** [comment]
This should be easy. Any takers :-) ?

**Comment by Xeverous** [comment]
This is not *that* easy. Various operating systems implement events differently (callback, blocking, polling), also different platforms differentiate between application-global events and window-specific events (these should be processed only by specific window). There is a very delicate balance what to put in `window` and what to put into `app` class.

**Comment by djowel** [comment]
It is easy. You must be in a different universe again :-) Or overthinking what I mean.

**Comment by djowel** [comment]
Here's the GLFW API, for example:

```c++
while (condition)
{
   /* ... */
    glfwPollEvents();  // <-- where events are handled if event queue is not empty
}
```

And it's implementation for MacOS is something like:

```c++
NSEvent *event = [NSApp nextEventMatchingMask:NSEventMaskAny
                                        untilDate:[NSDate distantFuture]
                                           inMode:NSDefaultRunLoopMode
                                          dequeue:YES];
[NSApp sendEvent:event];
```

Easy peasy. Windows is obviously very simple to decouple. GTK, well it has `gtk_main_iteration_do`.

**Comment by djowel** [comment]
OK, after more thinking, I think this "issue" is misguided. Regardless if run is blocking or non-blocking, the `app` will still own the event loop. The crux of the matter is the `view`/`base_view` and not the `app`. The latter two are optional and the case of not owning the event loop is the case where you do not instantiate an `app`.

Closing this one as invalid.
