### ISSUE TITLE
Help on writing interactive graph widget.

### ISSUE THREAD

**Issue by ark-sandbox** [cycfi/elements#235]
I am trying write a simple interactive line chart widget, But cursor method seems never been called.
Is there a guide/documentation how to extend element class?
`cpp
class LineChart : public element {
   bool mouseover = false;
   point cursor_pos;
public:
   void draw(context const& ctx){
      std::cout<<"draw called"<<std::endl;
      ctx.canvas.fill_rect(rect(0.0, 0.0, 100.0, 100.0));
      ctx.canvas.stroke_style(color(255, 255, 255));
      ctx.canvas.move_to(point(100, 30));
      ctx.canvas.line_to(point(90, 60));
      ctx.canvas.line_to(point(80, 30));
      ctx.canvas.line_to(point(70, 60));
      ctx.canvas.stroke();
      if (mouseover) {
         ctx.canvas.circle(circle(cursor_pos.x, cursor_pos.y, 10.0));
         ctx.canvas.stroke();
      }
   }
   bool cursor(context const& ctx, point p, cursor_tracking status) {
      std::cout<<"cursor called"<<std::endl;

      if (status == cursor_tracking::hovering) {
         mouseover = true;
      }
      if (status == cursor_tracking::leaving) {
         mouseover = false;
      }
      cursor_pos = p;
      ctx.view.refresh();
      return true;
   }
   bool wants_focus() const
   {
      return true;
   }
};`

**Comment by djowel** [comment]
Try overriding wants_control. I should probably make an example for making custom controls. Let's discuss in Discord: https://discord.gg/NJkadSx if you will.

**Comment by ark-sandbox** [comment]
thanks @djowel, now it works. Example would be great for newcomers like me :). Will discuss in discord as I make progress writing this graph widget .

**Comment by djowel** [comment]
If you can make a cute simple example with mouse tracking, etc. I can transform that into an exemplar on writing custom controls. There's a question about this already in Discord.

**Comment by ark-sandbox** [comment]
Sure.
https://gist.github.com/ark-sandbox/6bf8856afdc1f23789b4a1bfe10ad884
I end up with issue in overriding click method,
btn.state does not seem to be initialized? Am I missing something
click is called :: btn.state 1858962088  0

**Comment by djowel** [comment]
> btn.state does not seem to be initialized? Am I missing something
> click is called :: btn.state 1858962088 0

master? Try devel. I should probably merge to master. I'll do so tomorrow after some verifications.

**Comment by djowel** [comment]
> Sure.
> https://gist.github.com/ark-sandbox/6bf8856afdc1f23789b4a1bfe10ad884

Wonderful!

**Comment by djowel** [comment]
> > Sure.
> > https://gist.github.com/ark-sandbox/6bf8856afdc1f23789b4a1bfe10ad884
> 
> Wonderful!

Oh can you make a PR for that? I need "wall.jpg", for example. I'll add in some more stuff requested in Discord.
