### ISSUE TITLE
Compile with C++20 standard

### ISSUE THREAD

**Issue by Sigverus** [cycfi/elements#239]
Analysis on Issue #238 revealed that `Elements` currently does not build when the compiler is set to C++20. Example of a compile error:

```
C:\dev\cycfi\elements\lib\src\element\gallery\menu.cpp(172): error C2679: binary '+=': no operator found which takes a right-hand operand of type 'const char8_t [4]' (or there is no acceptable conversion)
```

Setting CMake to use C++20 should be done with `-DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON` on command line, or setting the variables before configuring the `Elements` app.

**Comment by djowel** [comment]
This is fixed now.
