### ISSUE TITLE
Can't build on MacOS

### ISSUE THREAD

**Issue by phillvancejr** [cycfi/elements#240]
I'm on High Sierra MacOS 10.13 and when I try to build with cmake I get the following error
```
CMake Error at lib/CMakeLists.txt:157 (add_subdirectory):
  The source directory

    /Users/phill.vance/sdk/elements/lib/infra

  does not contain a CMakeLists.txt file.
```

**Comment by redtide** [comment]
That usually happens when you download the source code archive from Github which doesn't contains the submodules (or not using `--recurse-submodules` / `--recursive` switch on `git clone`), so you are missing the library dependencies, one is the `infra` library.

**Comment by djowel** [comment]
No 1 FAQ, it seems.

**Comment by phillvancejr** [comment]
I was able to generate the makefiles however now I get errors about unused parameters in the macos/base_view.mm file

**Comment by djowel** [comment]
> I was able to generate the makefiles however now I get errors about unused parameters in the macos/base_view.mm file

That should be easy to fix. Please make a PR.
