### ISSUE TITLE
Load image from pixel data

### ISSUE THREAD

**Issue by Karthikeyan564** [cycfi/elements#241]
Could I add the ability to load image from pixel data already read by stb_image?

**Comment by djowel** [comment]
The artist port of elements has that already. Elements is positioned to move to the artist lib once things stabilize.

**Comment by Karthikeyan564** [comment]
Thank you for the reply,
but I think some projects still use elements including mine. It might be useful to add the functionality.

**Comment by djowel** [comment]
> but I think some projects still use elements including mine. It might be useful to add the functionality.

I am not sure I understand what you are saying. Elements will not go away. The artist library is a replacement of the drawing and canvas parts of elements. It is already in the artist_port branch of elements:

   https://github.com/cycfi/elements/tree/artist_port

Do you want the pixel data construction back-ported? If so, you might want to look at the API here:

   https://github.com/cycfi/artist/blob/d61c0771868dd3bfeb97aafed36ce5cb99691068/lib/include/artist/image.hpp

and the example here:

   https://github.com/cycfi/artist/blob/d61c0771868dd3bfeb97aafed36ce5cb99691068/examples/chessboard.cpp

**Comment by Karthikeyan564** [comment]
Thank you
