### ISSUE TITLE
Example hello_universe, throws exception because image is missing

### ISSUE THREAD

**Issue by Andersama** [cycfi/elements#245]
Seems as though the path given:
```c
   view_.content(
      scroller(image{ "space.jpg" })
   );
```
Is searching inside of the empty example directory, which doesn't have a space.jpg image.

**Comment by djowel** [comment]
Which OS?

**Comment by Andersama** [comment]
Windows 10, on master branch. Seems the issue would be with cmake since that appears to be how the resource directories seem to be set.

**Comment by djowel** [comment]
I just tried. I see no problem with it. When building with CMake, you should get something like this:

<img width="466" alt="Screen Shot 2021-01-07 at 1 46 02 PM" src="https://user-images.githubusercontent.com/568094/103856000-d91e1d00-50ee-11eb-97ca-5d9a9769efe3.png">

The image (space.jpg) is in the 'resources' directory, along with the application fonts.

**Comment by djowel** [comment]
Here, you can see it running: 
![Uploading Screen Shot 2021-01-07 at 1.52.34 PM.png…]()

**Comment by Andersama** [comment]
Here's what I'm getting:
![image](https://user-images.githubusercontent.com/25020235/103876807-f91af580-5088-11eb-8eab-053e9e8902b7.png)

Where the error's clearly stemming from this:
![image](https://user-images.githubusercontent.com/25020235/103876977-44350880-5089-11eb-88e3-854bf2ab4f54.png)

`get_resource_paths()` is returning a directory over. I've not messed with cmake to make sure it's still producing the error.

**Comment by djowel** [comment]
> To clarify: I'm building / running directly in MSVC. If I dig to the output folder and run the .exe that one runs fine*

Yes. It's not an issue with elements. It's a matter of correctly running the app with the correct working directory. It's just the way it is. Think of the exe and all the fonts and resources with it as a kind of a bundle. The app's resources, by default, should be in the same directory as the exe for it to work properly. If that is not desirable, you can add a resource path yourself and tell elements where it is at startup time. See resource_paths.hpp:

https://github.com/cycfi/elements/blob/master/lib/include/elements/support/resource_paths.hpp

**Comment by djowel** [comment]
Feel free to ask more questions! And feel free to close this if you have no further questions.

**Comment by Andersama** [comment]
Ah, well bummer, didn't want to fight cmake in the IDE, definitely will consider using that function at runtime instead.
Absolutely will do.

**Comment by djowel** [comment]
> I opened the project directly with MSVC*. I don't doubt this ordinarily works, because the folder's clearly off, it seems like a cmake issue in some fashion. Currently I'm using the MSVC 16.9.0 Preview 2.0.

BTW, just to offer some additional help:

1. There is a way to set the working directory of the project in visual studio: right-click on the project name in the Solution Explorer, then Properties, then under Configuration Properties / Debugging, set Working Directory.
2. CMake  > 3.8, has the VS_DEBUGGER_WORKING_DIRECTORY that you can set in your project: https://bit.ly/2XhBzSC

As for 2, I'd welcome a PR if you get that going with elements.

**Comment by Andersama** [comment]
The real question I'd have, because I'm not a cmake expert is why it's set to the empty example directory in the output folder. I'd be curious to know what the working exe in the output folder thinks is it's resource directory, because it clearly found the "space.jpg".

**Comment by djowel** [comment]
> The real question I'd have, because I'm not a cmake expert is why it's set to the empty example directory in the output folder. I'd be curious to know what the working exe in the output folder thinks is it's resource directory, because it clearly found the "space.jpg".

I think it's a Visual Studio thing where the output is placed in special folders depending on build type. Tell you what, I'm going to re-open this and investigate some more on VS. As far as I can recall, I did not have any problems with this, nor did any VS user thus far, so I'd like to better understand your situation.

> *On that note: get_resource_paths() doesn't seem to be accessible.

What do you mean?

**Comment by Andersama** [comment]
If you're trying to call `auto paths = cycfi::elements::get_resource_paths();` from the example in main you'll get a compiler error.
It's not declared in `elements\support\resource_paths.hpp`.

**Comment by djowel** [comment]
> If you're trying to call `auto paths = cycfi::elements::get_resource_paths();` from the example in main you'll get a compiler error.
> It's not declared in `elements\support\resource_paths.hpp`.

Please see the comment in the header for correct usage:

[resource_paths.hpp](https://github.com/cycfi/elements/blob/master/lib/include/elements/support/resource_paths.hpp)

What you want is `add_search_path`

**Comment by Andersama** [comment]
Wasn't looking to add a search path*, wanted to see the folders the application was getting from that function call*. I did just set a breakpoint in add_search_paths() however. So I think I see what you mean.
```c
      struct init_view_class
      {
         init_view_class()
         {
            WNDCLASSW windowClass = {};
            windowClass.hbrBackground = nullptr;
            windowClass.hCursor = LoadCursor(nullptr, IDC_ARROW);
            windowClass.hInstance = nullptr;
            windowClass.lpfnWndProc = WndProc;
            windowClass.lpszClassName = L"ElementsView";
            windowClass.style = CS_HREDRAW | CS_VREDRAW;
            if (!RegisterClassW(&windowClass))
               MessageBoxW(nullptr, L"Could not register class", L"Error", MB_OK);

            auto pwd = fs::current_path();
            auto resource_path = pwd / "resources";
            add_search_path(resource_path);
         }
      };
 ```
 ```c
 auto pwd = fs::current_path();
 ```
If you're in the debugger directly `current_path()` is apparently returning the example directory. Not clear why.

**Comment by djowel** [comment]
OK, it is running with Visual Studio 2019 via the debugger:

![hello-universe](https://user-images.githubusercontent.com/568094/103982664-de4a9d00-51be-11eb-982d-bf15ebc5a992.png)

The build files when building the solution should be:

![build](https://user-images.githubusercontent.com/568094/103982700-f02c4000-51be-11eb-8b5c-16dbd291156c.png)

I run cmake in the Visual Studio 2019 command prompt:

```
C:\dev\cycfi\elements\build>cmake  ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.28.29335.0
-- The CXX compiler identification is MSVC 19.28.29335.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_C_COMPILER C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
-- CMAKE_C_COMPILER_ID MSVC
-- CMAKE_C_COMPILER_VERSION 19.28.29335.0
-- CMAKE_CXX_COMPILER C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
-- CMAKE_CXX_COMPILER_ID MSVC
-- CMAKE_CXX_COMPILER_VERSION 19.28.29335.0
-- Link-time optimization disabled for elements
-- building elements with win32 host UI library
-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/cycfi/elements/build
```

After building with Visual Studio, I set the `hello_universe` as the Startup Project via right-click "Set Startup Project":

![solution](https://user-images.githubusercontent.com/568094/103982905-544f0400-51bf-11eb-871d-a609b5d22058.png)

VS sets the working directory properly:

![env](https://user-images.githubusercontent.com/568094/103983248-e3f4b280-51bf-11eb-96ac-b1dd5a5fce2b.png)

Then I run using "Local Windows Debugger" Button.

No problems here. Moreover, there are other MSVC/Visual Studio users using elements. So the problem must be unique to yours.

**Comment by Andersama** [comment]
Don't know that it makes a difference, but it looks like you're using an .sln, I've opened mine w/ MSVC's native cmake support.
![image](https://user-images.githubusercontent.com/25020235/103983913-0690b800-513b-11eb-87eb-5d09f6dffcbc.png)

When you do that approach tweaking settings in the properties pages you're kind of stuck having to do that per example right?

I got it to work with `add_search_path()`, makes the start of the examples a bit longer.
```c
/*=============================================================================
   Copyright (c) 2016-2020 Joel de Guzman

   Distributed under the MIT License (https://opensource.org/licenses/MIT)
=============================================================================*/
#include <elements.hpp>
#include <elements/support/resource_paths.hpp>
#include <string_view>

using namespace cycfi::elements;

int main(int argc, char* argv[])
{
   std::filesystem::path exe_path = std::string_view{ argv[0] };
   add_search_path(exe_path.parent_path() / "resources");

   app _app(argc, argv, "Hello Universe", "com.cycfi.hello-universe");
   ```

**Comment by djowel** [comment]
> Don't know that it makes a difference, but it looks like you're using an .sln, I've opened mine w/ MSVC's native cmake support.

OK, well, if you can find the right setup to get it working right-out-of-the-box with MSVC's native cmake, I'd be welcome to a PR or at least setup and build instructions. Adding `add_search_path` just to make MSVC happy is not ideal.

**Comment by Andersama** [comment]
At what point in your library / how are you adding paths from cmake? From what I saw it almost seemed as though the program only added in one path directly with `add_search_path()` but specifically to try to grab the current working directory. I'm guessing you're having cmake define a macro which expands out to a set of paths?

**Comment by Andersama** [comment]
Looking at the cmake, it seems as though you're copying from a user defined variable `ELEMENTS_RESOURCES` with a list of paths eventually into `CMAKE_CURRENT_BINARY_DIR` which appears to be doing all the work of collecting all the resources and copying / dumping them into a single folder with the exe?

If I'm not mistaken then the goal would be to communicate to the program that "${CMAKE_CURRENT_BINARY_DIR}/resources" is a folder to execute `add_search_paths()` on at the start.

**Comment by djowel** [comment]
I think this is solely a cmake issue and as much as possible I'd prefer the c++ code need not be touched. The main issue is msvc's cmake quirks, of which I am not familiar with. IMO, that's the one that needs to be solved.

**Comment by Andersama** [comment]
Found the problem:
Linux's host does the work of adding that resource path like I did, but MSVC's host does not*

**Comment by djowel** [comment]
> Found the problem:
> Linux's host does the work of adding that resource path like I did, but Window's host does not*

Ah, can you point me to the code?

**Comment by Andersama** [comment]
Check here:
https://github.com/cycfi/elements/blob/12a54afaa0381bae0445c7d9c3425fc78a08001f/lib/host/linux/app.cpp#L43

vs:

https://github.com/cycfi/elements/blob/12a54afaa0381bae0445c7d9c3425fc78a08001f/lib/host/windows/app.cpp#L62

I don't think the windows host is adding anything to the resource search paths.

That cmake stuff may also work.

**Comment by djowel** [comment]
OK, seems you're in the right path then ( pun intentional :-) ). PR most welcome!

**Comment by Andersama** [comment]
Would you prefer it be done with cmake trickery or just manually / natively in the host?

**Comment by djowel** [comment]
> Would you prefer it be done with cmake trickery or just manually / natively in the host?

I think the linux solution seems reasonable, come to think of it.

**Comment by Andersama** [comment]
That brings up a follow up question:
Does this section adding to the search paths make sense? This is where that erroneous empty directory gets added on my end. 
https://github.com/cycfi/elements/blob/12a54afaa0381bae0445c7d9c3425fc78a08001f/lib/host/windows/base_view.cpp#L478

**Comment by Andersama** [comment]
Seems to work 👍 
![image](https://user-images.githubusercontent.com/25020235/103993157-04822580-514a-11eb-9ae7-c9796aeb2c18.png)

**Comment by djowel** [comment]
> That brings up a follow up question:
> Does this section adding to the search paths make sense? This is where that erroneous empty directory gets added on my end.

Oh that is important. I'm glad you brought this up. Elements is modular. There are cases where you have an app-less and window-less program. For example, audio plugins (and all plugins in general). In such a case, the host app makes the window for you.


> Way too new to your library to know, this isn't a class that gets used for every window that's constructed right? Because otherwise opening new windows will end up modifying the search paths very time one is constructed.
> Nevermind the worrying bit of code is is in class seemingly to be constructed once statically. Still, this seems odd.

Good point, actually. I'll ponder on it some more...

**Comment by djowel** [comment]
> > Way too new to your library to know, this isn't a class that gets used for every window that's constructed right? Because otherwise opening new windows will end up modifying the search paths very time one is constructed.
> > Nevermind the worrying bit of code is is in class seemingly to be constructed once statically. Still, this seems odd.
> 
> Good point, actually. I'll ponder on it some more...

Hmmm... I might have to remove that now (I'll check). Thinking about it, for plugins, the startup code sets the resource paths and it can be different in different situations. I'm glad you brought this up!

**Comment by Andersama** [comment]
The linux host also appears to have a similar bit of code*, seems to me in general your approach is that you're assuming `/resources` is a folder right next to the executable which should contain all the program's data, but if the user's meant to define resources via cmake would it not be better to have a generalized startup function which adds paths once (from cmake) and then let the user manually add folders as needed? Because presumably in the app-less / window-less approach you may want a resources path set for some reason, but maybe not necessarily to draw.

**Comment by djowel** [comment]
> The linux host also appears to have a similar bit of code*, seems to me in general your approach is that you're assuming `/resources` is a folder right next to the executable which should contain all the program's data, but if the user's meant to define resources via cmake would it not be better to have a generalized startup function which adds paths once (from cmake) and then let the user manually add folders as needed? Because presumably in the app-less / window-less approach you may want a resources path set for some reason, but maybe not necessarily to draw.

Agreed in principle. However, I am still not sure if that path has to come from cmake. I'm still debating with myself :-) I do agree that the path should not be hard-wired to be in a certain place, even if it's by default (as originally intended).

**Comment by Andersama** [comment]
At a certain point if it seems like a thing to leave up to the developer it could be a cmake option...

**Comment by djowel** [comment]
> At a certain point if it seems like a thing to leave up to the developer it could be a cmake option...

Ok, at this point, I find myself totally agreeing with you. Would you like to do another PR?

**Comment by Andersama** [comment]
I had some thoughts, might actually be a nice tool to have in general. Since the user's defining a list of folders in cmake to collect together, it might be really useful to be able to specify those list and then be able to refer to specific lists of folders directly. Not a cmake expert, but that seems like an idea.

EG: As opposed to having one large list of every possible folder to search, it might be useful for the user to specify the folders specifically they expect to find those resources. Think like, audio resources, video resources, image resources, text...or whatever the developer might specifically know in advance.

**Comment by djowel** [comment]
I am inclined now to have the `ELEMENTS_RESOURCE_PATHS` as a cmake option, as you suggested. Keep in mind though that this is just the default. Users are always free to add search paths as needed. 

Also, I don't think I want to overdo it. As its basic form, a single resource path is sufficient. After all, the client can always 'modularize' the directory by adding more sub-directories under that. For example, `image{ "images/space.jpg" }` is perfectly doable if the client so wishes.

**Comment by Andersama** [comment]
Alright, now I'm back. I may have been mistaken on the semi-colon delimited list, was vaguely remembering some other source code, the text was coming through the command line. I'm fairly certain there's a way to collect a list of paths with cmake, still working that out.

**Comment by djowel** [comment]
> I'm fairly certain there's a way to collect a list of paths with cmake, still working that out.

Aww, it's just a space delimited, optionally double-quoted paths.

**Comment by Andersama** [comment]
The cmake documentation reads like variables are semicolon delimited strings*, but to play it safe I figured I should probably check if semicolons are legal characters in folder paths across operating systems, It seems ';' might be a valid character on linux. Might not matter though because it's how cmake works with variables anyway,, so I don't think you'd be able to work with ';''s in paths no matter what.

**Comment by djowel** [comment]
Why bother? Just separate the paths using spaces/newlines like this:

https://github.com/cycfi/elements/blob/master/lib/CMakeLists.txt#L12-L52

**Comment by Andersama** [comment]
Ah, sorry, not making things clear. I was worried about the internal representation that cmake would give to the program at the end. I wasn't particularly worried about the syntax in cmake, as far as I can tell:
`set(SOMETHING a.c b.c)` is equivalent to set(SOMETHING "a.c;b.c")` and it'd be roughly equivalent to `#define SOMETHING "a..c;b.c"` in c++ if I used `add_compile_definitions(SOMETHING=${SOMETHING}) `.

**Comment by djowel** [comment]
> Hopefully that makes sense?

Ok, well, I guess you are just thinking out loud :) many ways to skin a cat...

**Comment by Andersama** [comment]
Might be a nicer cmake way of going about this, something like this:
```
option(USE_ELEMENTS_RESOURCE_PATHS "If ON elements will copy resources to ELEMENTS_RESOURCE_PATHS, otherwise it will copy to /resources next to your output executable")
if (USE_ELEMENTS_RESOURCE_PATHS)
   if (NOT DEFINED ELEMENTS_RESOURCE_PATHS)
      set(ELEMENTS_RESOURCE_PATHS "${CMAKE_CURRENT_BINARY_DIR}/resources")
   endif()
else()
   set(ELEMENTS_RESOURCE_PATHS "${CMAKE_CURRENT_BINARY_DIR}/resources")
endif()

if (UNIX AND NOT APPLE)
   file(
      COPY ${ELEMENTS_RESOURCES} ${ELEMENTS_APP_RESOURCES}
      DESTINATION "${ELEMENTS_RESOURCE_PATHS}"
   )

endif()

if (WIN32)
   file(
      COPY ${ELEMENTS_RESOURCES} ${ELEMENTS_APP_RESOURCES}
      DESTINATION "${ELEMENTS_RESOURCE_PATHS}"
   )
endif()
...
# Pass along to compiler as preprocessor macros
add_compile_definitions(ELEMENTS_RESOURCE_PATHS="${ELEMENTS_RESOURCE_PATHS}")
if (USE_ELEMENTS_RESOURCE_PATHS)
   add_compile_definitions(USE_ELEMENTS_RESOURCE_PATHS=true)
else()
   add_compile_definitions(USE_ELEMENTS_RESOURCE_PATHS=false)
endif()
```

**Comment by Andersama** [comment]
I'm going to give up, not having luck getting anything to work. I get either macros properly expanded in the main program or ones not being defined in the elements lib.
