### ISSUE TITLE
Consider replacing std::rand()?

### ISSUE THREAD

**Issue by Andersama** [cycfi/elements#247]
Personal favorite of mine is a bit of a rewrite of the minimal c example from [https://www.pcg-random.org](https://www.pcg-random.org).
They've got a c++ repo as well https://github.com/imneme/pcg-cpp with their stuff under MIT license so it shouldn't conflict.

**Comment by djowel** [comment]
I don't think I am using rand anywhere, did I?. And if I did, I think I'd like to keep dependencies as minimal as possible, unless the functionality is crucial to the functioning of the library.

**Comment by Andersama** [comment]
Oh, you're right, I spotted std::rand() but it's in the examples folder*, nvm.
