### ISSUE TITLE
GUI scale problem (?)

### ISSUE THREAD

**Issue by Delta-dev-99** [cycfi/elements#253]
(I'm not sure this is a scale problem. It's just my guess)
I just cloned the master branch (and sub-modules) and built everything from source. All good.
When I run the example programs I get this kind of results:

![Screenshot from 2021-02-24 22-25-14](https://user-images.githubusercontent.com/46575220/109098439-51688e00-76ef-11eb-8fce-6c94d3fe32db.png)
![Screenshot from 2021-02-24 22-23-31](https://user-images.githubusercontent.com/46575220/109098480-6d6c2f80-76ef-11eb-818a-337a22ae8fdf.png)

It seems to be just a rendering problem. Widgets detected clicks in the zone they should be (not in the zone where they were erroneously rendered)

OS: Ubuntu 20.04.1 LTS - 64bit
GNOME 3.36.8
on Wayland

I can post any useful data, just ask.

**Comment by djowel** [comment]
Can you try the artist_port branch? I believe there were some fixes to the artist_port branch recently.

**Comment by djowel** [comment]
OK, confirmed. It seems I'm gonna have to do some wayland work :)

**Comment by djowel** [comment]
OK, this should be fixed now in develop. Please try and verify so we can close this. Thanks for reporting!

**Comment by Delta-dev-99** [comment]
Fix verified.
Yeah, it is working now.

**Comment by Delta-dev-99** [comment]
Oh, I reopened the issue because I realized this fix is not yet committed to the master branch.
Please commit it as soon as you can.

**Comment by djowel** [comment]
> Oh, I reopened the issue because I realized this fix is not yet committed to the master branch.
> Please commit it as soon as you can.

Oh, I will merge. I just wanted to confirm this first. I'll re-close this again.
