### ISSUE TITLE
Weird caret drawing

### ISSUE THREAD

**Issue by Delta-dev-99** [cycfi/elements#254]
Looking closely to the caret graphics on the text_edit example I noticed that there are actually 2 carets being drawn with different colors and with different visibility intervals. Some screenshots follow.
Both carets shown:
![caret shown](https://user-images.githubusercontent.com/46575220/109252045-95749500-77ba-11eb-8fda-9ade3abd5089.png)
Only one caret shown:
![caret half shown](https://user-images.githubusercontent.com/46575220/109252113-bfc65280-77ba-11eb-9648-3de729161a1b.png)
Both hidden: 
![caret hidden](https://user-images.githubusercontent.com/46575220/109252142-d1a7f580-77ba-11eb-9a53-be9254b8fba9.png)

I failed to capture only the brighter caret on display because it is too bright to see whether or not the other one is drawn, but probably that case happens too.
I actually saw the brighter caret go off, leaving only the dimmer one and after a short interval that one went off too. This proves that there are actually 2 different intervals (or maybe the same but at different phase).
To reproduce, just click around a bit and look carefully to the caret.

--------------------------------------------------------------------------------------------

I also noted some other (short lived) crazy caret behavior after changing caret position. Some screenshots are pretty much self explanatory.
Different caret sizes: ![Untitled](https://user-images.githubusercontent.com/46575220/109253763-78da5c00-77be-11eb-9be1-0c186a9d1660.png) ![Untitled1](https://user-images.githubusercontent.com/46575220/109253766-7aa41f80-77be-11eb-8fce-6a3bda63167f.png)
This one actually shows only the brighter caret (the previously missing case) ![Untitled2](https://user-images.githubusercontent.com/46575220/109253767-7b3cb600-77be-11eb-97e8-d830a470d779.png)
Caret size mismatch (between the two distinct carets simultaneously displayed) ![Untitled3](https://user-images.githubusercontent.com/46575220/109253768-7c6de300-77be-11eb-843e-59ba98e609f2.png)
Some more examples:
![Untitled4](https://user-images.githubusercontent.com/46575220/109253769-7d067980-77be-11eb-8799-939b39a089dc.png)
![Untitled5](https://user-images.githubusercontent.com/46575220/109253772-7d9f1000-77be-11eb-82c4-ed39d71a23bd.png)
Fragmented carets:
![Untitled6](https://user-images.githubusercontent.com/46575220/109253774-7e37a680-77be-11eb-9f66-bd7fdd337b38.png)
![Untitled7](https://user-images.githubusercontent.com/46575220/109253776-7f68d380-77be-11eb-90d8-4bdac06fec2f.png)
To reproduce just click around a bit and/or move the caret with the keyboard and look carefully.

------------------------------------------------------------------

Side note: I also noted some weird (double | triple | multi)click-selection behavior in which multi-clicks are detected even when they occur in different places. I will create a new issue about this later.

OS: Ubuntu 20.04.1 LTS - 64bit
GNOME 3.36.8
on Wayland

Example built from develop branch.

**Comment by djowel** [comment]
Would you be interested to do some sleuthing in the code :-P ? Seems easy to track down since each element class has only one draw member function to investigate. It might also be some masking/clipping issue.

**Comment by Delta-dev-99** [comment]
I'm taking a look at the library, but my time is somewhat limited. As for the interest, I got plenty. I really like this lib. I will try to find what happened there.

**Comment by djowel** [comment]
> I'm taking a look at the library, but my time is somewhat limited. As for the interest, I got plenty. I really like this lib. I will try to find what happened there.

Understood. I'll see what I can do. My guess is that it is simply a masking/refresh issue and can be fixed by making the refresh rect a bit bigger. 

Hmmm... Can you verify if this is also happening in the non-wayland world?

**Comment by Delta-dev-99** [comment]
I found it. There are actually 2 carets being drawn.
In `lib/src/element/text.cpp` look at lines 559 and 578
I just saw the problem. My first guess was to just remove one of the blocks, but there were two different intervals and that is not touched inside the block. So I think it will be better to look deeper before making rush changes

**Comment by Delta-dev-99** [comment]
I can try on X. I'll post the results

**Comment by Delta-dev-99** [comment]
I think I found the bug.
The caret draws a little bit out of its expected bounds (maybe due to sub-pixel anti-aliasing). So, when you refresh the view to remove the caret by repainting over it, you miss a little edge. This can be fixed by adding a little extra to the bounds (between 0.5 - 1.0)
That is half of it.
When the caret is drawn, a refresh is scheduled to remove it after 500ms, or more precisely, to refresh its region. But if you move the caret to another location, you cause an immediate refresh, but the scheduled refresh is not canceled. When the old and new carets' region overlap, the old caret's scheduled refresh ends up removing a fraction of the new one.

**Comment by djowel** [comment]
Cool! OK, I'll see what I can do...

Oh and yeah, I am also considering optimizations for such things.

**Comment by djowel** [comment]
> When the caret is drawn, a refresh is scheduled to remove it after 500ms, or more precisely, to refresh its region. But if you move the caret to another location, you cause an immediate refresh, but the scheduled refresh is not canceled. When the old and new carets' region overlap, the old caret's scheduled refresh ends up removing a fraction of the new one.

Makes sense. Thanks for investigating!
