### ISSUE TITLE
Error using textboxes

### ISSUE THREAD

**Issue by Andersama** [cycfi/elements#257]
Currently unable to use the textbox class (in or out of the elements project) due to this bizarre error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2280	'cycfi::elements::static_text_box::static_text_box(const cycfi::elements::static_text_box &)': attempting to reference a deleted function	E:\Github\_rec\out\build\x64-Debug\_rec	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\xutility	138	
```
It does give this error regardless of the constructor call used, or other text box classes.
It looks as though the && constructor is defaulted, I don't know if that's meant to automatically generate the const & constructor.

```c
#include "elements.hpp"
#include <iostream>
#include <string>

using namespace cycfi::elements;

int main(int argc, char *argv[]) {
    std::string log = "test text";

    auto constexpr bkd_color = rgba(35, 35, 37, 255);
    auto background          = box(bkd_color);
    //any variation of text box errors out
    auto txt_box = cycfi::elements::static_text_box(log, font{}, 9.0, rgba(255,255,255,255));

    app    _app(argc, argv, "_rec", "com.andersama._rec");
    window _win(_app.name());

    _win.on_close = [&_app]() {
        _app.stop();
    };

    auto main_content = make_main_window();

    view _view(_win);
    _view.content(txt_box, background);

    _app.run();

    return 0;
}
```

**Comment by djowel** [comment]
That is correct. Text boxes are not copyable, by design. Use share so it will be held by shared_ptr instead of by value. See the examples.

**Comment by Andersama** [comment]
Ah, ok, that makes sense, bit counterintuitive that it needs to be wrapped in a shared pointer for use, but I'll definitely make note of that if I run into that error elsewhere. Thank you.

**Comment by djowel** [comment]
> Ah, ok, that makes sense, bit counterintuitive that it needs to be wrapped in a shared pointer for use, but I'll definitely make note of that if I run into that error elsewhere. Thank you.

Probably a matter of documentation. As you know, as much as possible, elements are by-value. They are typically lightweight and can be passed around easily by value. Text edit elements on the other hand are not so lightweight. So, for performance, it is best not allow copy. In such cases, you can still pass them around without copying if you hold them in a smart pointer.
