### ISSUE TITLE
Window Icon support in Windows 

### ISSUE THREAD

**Issue by ahmedtalaat327** [cycfi/elements#265]
Thank God I managed to use this wonderful framewrok in windows using vs2019 but I don't really know how to add icon to my window I used resource.h file to add icon to task bar it's a visual studio thing but the window itself does not have the icon ,, I used this method previously but with console application like this console always take icon and leave the exe alone without the icon any ideas ..?

**Comment by redtide** [comment]
I guess you can include a [.rc][1] resource file and a `.ico` file icon into some `resources` directory of your project, add append the `.rc` file to the source files list in your CMake configuration.
@djowel what do you think to add this to the example projects?

[1]: https://docs.microsoft.com/en-us/windows/win32/menurc/icon-resource

**Comment by djowel** [comment]
> @djowel what do you think to add this to the example projects?

Sounds good.

**Comment by redtide** [comment]
Done in #266.

**Comment by ahmedtalaat327** [comment]
@redtide  I think these steps will eventually lead me to make the icon only appear in task bar not on the window itself .. BTW I'll test it again building the cmake after these mods..

**Comment by ahmedtalaat327** [comment]
![yu](https://user-images.githubusercontent.com/26097164/122161697-6cb00280-ce72-11eb-8b37-27f2dee63425.png)

**Comment by ahmedtalaat327** [comment]
I googled about adding icon to an exe  by adding add_executable(${PROJECT_NAME} ${SRCS} ... in CMakeLists file but input is not clear for cycfi resource file.

**Comment by redtide** [comment]
In order to set the window icon there is also a need for the API to provide a `window::set_icon(const some_icon(list)_class& icon(s))` as other frameworks does. Unfortunately ATM Elements doesn't have such feature and looking at windows and gtk implementations is not that trivial because they use a list of icons with different sizes, so there is a need also of some `icon_bundle` class to make it more complete.
I guess you can solve it by getting the native `HWND` handle of the window using `window::host()` and send a
```cpp
::SendMessage(windowHandle, WM_SETICON, wParam, lParam);
```
as described in the [documentation][1] once you have an [icon][2] from the ID you used in the `rc` file to use as `lParam`.

[1]: https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-seticon
[2]: https://docs.microsoft.com/it-it/windows/win32/menurc/using-icons

**Comment by djowel** [comment]
Elements is supposed to be minimal. When in doubt, I check GLFW, which is also minimal. How does GLFW deal with this?

**Comment by redtide** [comment]
> Elements is supposed to be minimal. When in doubt, I check GLFW, which is also minimal. How does GLFW deal with this?

looks like [about the same][1] as the others

[1]: https://www.glfw.org/docs/latest/group__window.html#gadd7ccd39fe7a7d1f0904666ae5932dc5

**Comment by ahmedtalaat327** [comment]
I managed to make it work using `<resource.h>` only for one project It's bad to use default icon using CMakeLists or Configs ..
Again as @redtide  mention only method works in my case by adding some lines of codes to Main method making every project diff than the others :
![Untitled](https://user-images.githubusercontent.com/26097164/122218954-3cd32000-ceaf-11eb-8803-478539a47d87.png)
the problem with me was how to get the cuurent window to extract the `HINSTANCE` object just by searching for the window name. Thanks for helping again.
![trrr](https://user-images.githubusercontent.com/26097164/122219333-a0f5e400-ceaf-11eb-8733-dc056272a90e.png)

**Comment by ahmedtalaat327** [comment]
@redtide Just a question How can I check the OS type what method used for this job in Elements.lib?

**Comment by ahmedtalaat327** [comment]
I want the code only be executed in windows env so .. Should I use some sort of if statement here..?

**Comment by redtide** [comment]
I guess you can use `#if defined(_WIN32)`.

**Comment by djowel** [comment]
> Thinking of it I don't think it's something complex and unneeded for an UI framework, it's about to pass a list/bundle of icons to the host implementation. In this case shouldn't be hard to make it natively either without touching the API.

Do you think you can do a PR for this? Looks easy alright.

**Comment by redtide** [comment]
I was on the way to do it yesterday in #266 but I'm still not sure how to implement the icon list/bundle to make it also usable without native host API, like using `sprite`/`pixmap` or a new `icon` class.

**Comment by ahmedtalaat327** [comment]
Thanks now the exe can handle which OS and `HWND ` will not give an exception of it's not it's environment..
How can I handle the focus event on input_text to change the outter strock like this ,.. 
![tr](https://user-images.githubusercontent.com/26097164/122350515-925e0a00-cf4d-11eb-965f-41224fe442a4.png)



is there any documentation for the rest of UI  components like menus or comboboxs or listboxs and events.

**Comment by djowel** [comment]
> How can I handle the focus event on input_text to change the outter strock like this ,..

One way is to subclass the text edit class and override the focus member functions.

> is there any documentation for the rest of UI components like menus or comboboxs or listboxs and events.

Not at the moment. You'll have to figure it out from the examples. Hopefully I'll have more time soon to write more docs.

**Comment by ahmedtalaat327** [comment]
It's something related to` text.cpp/text.h` files 
![thgft](https://user-images.githubusercontent.com/26097164/122481657-5e2b2d80-cfcf-11eb-92bc-70a24fd5bbf7.png)
but there is no outer line there. Even Rec object are always refer to text selection renderng..
Seems it's another layer Called `Frame `it's a Struct maybe.. trying to find-out later..

**Comment by djowel** [comment]
> but there is no outer line there. Even Rec object are always refer to text selection renderng..

No, you have to do the drawing yourself. One way to do it is to determine if you are in focus or not, maybe save a bool when you are in focus. Then, in your draw member function, just draw the frame before returning. There are other 'element-style' ways to do this, but this is the easiest way. Study how other elements draw depending on state; e.g. the checkbox highlights the control when hovering.

**Comment by djowel** [comment]
The 'element' style way of doing this is to make a generic class, say named focus_frame, which is a proxy with a subject. The proxy can contain any element, such as the input_box. It manages a `bool in_focus` member that updates it when the subject becomes the focus. Then in its draw member function, it draws the frame after subject draws itself. It's actually easier said than done, but requires knowledge of how element proxies work.

**Comment by ahmedtalaat327** [comment]
I added underline in input text just by removing layer frame and adding a condition to `draw `method in  `basic_input_box`
and this is the result ...
https://user-images.githubusercontent.com/26097164/123478847-589d9b00-d600-11eb-9384-4e124eebbe40.mp4

**Comment by djowel** [comment]
> I added underline in input text just by removing layer frame and adding a condition to `draw `method in `basic_input_box`
> and this is the result ...

Looks good! If this goes well, I might be able to write a 'custom proxy' example to show how to write this element's style, such that you can reuse the proxy anywhere.

**Comment by ahmedtalaat327** [comment]
is there any data grid or tables i mean cells rows and cols ...?
