### ISSUE TITLE
MultiThreading using join freezes the entire GUI.

### ISSUE THREAD

**Issue by ahmedtalaat327** [cycfi/elements#267]
I noticed when I use More than one thread inside events like `button `for ex .. My Whole window freeze Even with the `view.post` timer is just async method not working..! Is there is method like signal in Qt to solve this issue or other method for view I dont know?

**Comment by djowel** [comment]
Could you post an MVCE?

**Comment by ahmedtalaat327** [comment]
@djowel  Ok at first I have a method called `gateData(int case);` derived from class `called Scan`  
This method can handle about 50 thread in a concurrency way to minimize the time that the program needs timers can't do it with same way, When I call the method inside button click` scanbtn.on_click` like this:
scanbtn.on_click =

1.       [&view_, &_app, scanbtn, mbc,&refreshbtn, &_win](bool) mutable
2.    {
3.       if (scanbtn._acive) {
4. 
5.          view_.remove(mbc);
6.          //putting message
7.          auto msg_box = make_message();
8.          view_.add((msg_box));
9.          /////////////////////////////////////////////////--loading--//////////////////////////////////////////
10. #if defined(_WIN32)
11.          view_.post(1s,
12.             [&view_,&_app,&refreshbtn,msg_box]
13.             {
14.          string akno[20];
15.          string imgs[20];
16.          int akno_size = 0;
17.          //------scan object----
18.          Scan scan;
19.          //All threads goes here...
20.          scan.gateData(0);
21.          //scan.macs_net;
22.          akno_size = scan.ips_net.size();
23. .
24. .
25. .

it hangs cause of join that I'm using inside each loop of threads like this:

1.  if (gateCase == 0) {
2.       std::vector<std::thread> threads0;
3.       for (int i = 0; i < s0p0.size(); i++) {
4.          const char* c = s0p0[i].c_str();
5.        //  auto r = std::thread(&Scan::loadTracing_Ip, this, c);
6.      
7.          threads0.push_back(
8. 
9.             std::thread([this, c] {
10.                //Code
11.                Scan::loadTracing_Ip(c);
12.                })
13. 
14. 
15.          );
16.           
17.       }
18.       
19.       for (auto& th : threads0) {
20.          th.join();
21.       }

**Comment by ahmedtalaat327** [comment]
More than thing ..The window actually freezes for a seconds (you cant interact with any of it's components) then works perfect.

**Comment by djowel** [comment]
The only way I can help is if you post an MVCE: https://stackoverflow.com/help/minimal-reproducible-example
