### ISSUE TITLE
includes with "//"

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#27]
This is likely a source of weird underlines in some IDEs, not sure whether these headers are actually used in any source or it "just compiles" (unix paths treat multiple slashes as one) but I get broken include/comment highlight.

https://github.com/cycfi/elements/blob/02c1ab01cbcd887c640e3bf130e28618339aa58c/lib/include/elements/element/gallery/message_box.hpp#L10-L11

https://github.com/cycfi/elements/blob/02c1ab01cbcd887c640e3bf130e28618339aa58c/lib/include/elements/element/gallery/dialog.hpp#L16

I guess fixing these can not go wrong. ` grep -rn "#include" lib/ | grep "//"` does not report more.

**Comment by djowel** [comment]
fixed in develop branch
