### ISSUE TITLE
how to do get_text() for input_box?

### ISSUE THREAD

**Issue by dirkarnez** [cycfi/elements#270]
It seems input_box is a composed element, and i tried find_subject but failed. How do you guys do get_text()? Thank you!

**Comment by djowel** [comment]
Could you elaborate a bit more? What do you have so far?

**Comment by dirkarnez** [comment]
Thanks, I am doing dynamic form that consists of arbitrary input elements (input_box, radio button, checkbox... etc.). In form submission, all these user input will be collected.

I can have a MVCE soon.

**Comment by dirkarnez** [comment]
```cpp
#include <elements.hpp>

using namespace cycfi::elements;

int main(int argc, char* argv[])
{
	app _app(argc, argv, "TextEdit", "com.cycfi.text-edit");
	window _win(_app.name());
	_win.on_close = [&_app]() { _app.stop(); };

	view view_(_win);

	auto my_button = button("Button");
	my_button.on_click = [](bool) {
		// How can i get user text input to `input_pair_first_shared` in here?
	};
	
	auto buttons =
		vtile(
			top_margin(35,
				vtile(
					top_margin(20, my_button)
				)
			)
		);

	vtile_composite container;

	auto textbox = share(static_text_box("Some description"));

	auto input_pair = input_box("Show me more");
	auto input_pair_first = input_pair.first;
	auto input_pair_first_shared = share(input_pair_first);

	container.push_back(share(group("Title",
		margin({ 10, 10, 20, 20 },
			top_margin(25,
				vtile(
					top_margin(10, left_caption(hold(input_pair_first_shared), "Entry")),
					hmin_size(350, top_margin(10, hold(textbox)))
				)
			)
		)
	)));

	view_.content(
		vtile(
			vscroller(margin({ 20, 20, 20, 20 }, container)),
			htile(
				hmin_size(250, margin({ 20, 20, 20, 20 }, buttons))
			)
		), 
		box(rgba(35, 35, 37, 255))
	);

	_app.run();
	return 0;
}
```

**Comment by djowel** [comment]
I'll get back to this ASAP (very busy now). Meanwhile, the general solution to this is to move `auto textbox = share(static_text_box("Some description"));` before `auto my_button = button("Button");` so you can get a 'std::weak_ptr ' to  it in your button callback lambda. You can use element's `get(shared-element)` function to make a 'std::weak_ptr '. The dialog provides an example on how this is done:

https://github.com/cycfi/elements/blob/master/lib/include/elements/element/gallery/dialog.hpp#L59-L72

**Comment by dirkarnez** [comment]
Thank you @djowel, i don't know there is a `get()` method before your example.

Finally get the idea:
```cpp
auto text = input_box("").second->get_text();
```
i got the `first`, it was wrong :P.
