### ISSUE TITLE
Style guide?

### ISSUE THREAD

**Issue by WilliamBehrens** [cycfi/elements#275]
I'm pretty sure you're following the microsoft c++ style but I was wondering if you could confirm?

**Comment by djowel** [comment]
It's more related to the stl and boost libraries style guide. As for expression templates (i.e how elements are composed in the code), the style is related to the [boost.spirit style guide](https://www.boost.org/doc/libs/1_53_0/libs/spirit/doc/html/spirit/notes/style_guide.html).

If you are asking to have configurations for clang format, the general problem is that these formatters do not really handle expression level formatting. So, there still needs to be some manual formatting. Nevertheless, I'd be interested to see if clang format can capture element's coding style, at least in part.
