### ISSUE TITLE
How to get the native host handle in GTK3?

### ISSUE THREAD

**Issue by redtide** [cycfi/elements#276]
On Windows the `host()` function returns the native widget `HWND` handle directly:
```cpp
using host_view_handle = HWND;
using host_window_handle = HWND;

class base_view : non_copyable
{
public:
    // ...
    host_view_handle     host() const { return _view; }
private:
    host_view_handle     _view;
};
```
However GTK3 and macOS COCOA have:
```cpp
using host_view_handle = host_view*;
using host_window_handle = host_window*;
```
where host_{view|window} in GTK are structs containing the GtkWidget native handle:
```cpp
struct host_window
{
    GtkWidget* host = nullptr;
    std::vector<std::function<void()>> on_activate;
};
```
the related view version is different but similar.

Is there a way to obtain the native widget handle and if not but permitted, which acceptable/crossplatform aware solution could be made? This is required to being able to subclass natively the host where it's not possible via Elements API. IMO, for consistency, `host()` should return the handle directly like on the Windows version.

**Comment by redtide** [comment]
to me using host() in one platform and host()->host in another looks odd TBH, I don't see why not return the native handle/object (`Gtk{Widget|Window}` or `NS{View|Window}`) directly instead, but I can't use it anyway because the `host_{view|window}` structs are declared in the cpp file.

**Comment by djowel** [comment]
No. You should not do it that way. The struct is opaque for an obvious reason: encapsulation and data hiding. Clients should NEVER touch the data in that struct. Handles are opaque!

What I am trying to say is that the implementation *can" present the `GtkWidget`. One correct way to do this is by providing a platform specific member function or free function that, given a host handle, returns the `GtkWidget`. Example:

```
GtkWidget* get_gtk_widget(host_window_handle h);
```
I hope I made my self clear now?

**Comment by djowel** [comment]
It is usable, but not as you intended it would be. In general it is simply used as an opaque handle that is passed along to and from the implementation. Try doing a grep to see what I mean. Essentially, clients should not care about what these handles are. They can be anything. As a client, you should not assume anything and should not care what these are and the data they contain (much like private variables). The host's purpose is to provide, as much as possible, platform neutral facilities, and in some cases, if needed, platform specific facilities, via functions and member functions.

**Comment by redtide** [comment]
OK, I gave a look to another UI framework for reference and at least on wx there is a [GetHandle()](https://docs.wxwidgets.org/3.0/classwx_window.html#a185e6cd7065367b552748cb722651b27) member function that does what I mean.

**Comment by djowel** [comment]
> OK, I gave a look to another UI framework for reference and at least on wx there is a [GetHandle()](https://docs.wxwidgets.org/3.0/classwx_window.html#a185e6cd7065367b552748cb722651b27) member function that does what I mean.

Sure. That's their choice. But here's the thing: is it documented what that handle should be? Then OK, the handle is "defined". As to elements, the handle is "implementation-defined". 

In general, as a matter of design principle, defining the contents of handles is a bad design choice. The client should never peek into a handle and assume its contents. Implementations that allow handles that are not opaque calls for trouble in the end (reminds me of the old Mac toolbox). Non-opaque handles lead to an inflexible design where the host is constrained and not able to add or change the implementation.

**Comment by djowel** [comment]
> defining the contents of handles is a bad design choice

Which is akin to making your class member variables public.

**Comment by djowel** [comment]
> a generic `native_{view|window}_handle get_native_handle()` where handle can be either `HWND` on Windows, `Gtk{Widget|Window}`* or `NS{View|Window}` on macOS (which initially I thought `host_{view|window}_handle` was about).

I am OK with this and the naming. To summarize:

- `native_view_handle view::get_native_handle()`
- `native_window_handle window::get_native_handle()`

**Comment by redtide** [comment]
It turned out that my requirements for this was for the wrong case, out of the library scope, so I'm sorry for the noise.
I guess it might be useful instead in cases like native platform modal dialogs or docking windows, which should work outside the view that requires the native window/view to be passed as parent, so please let me know if to keep this open, or close and eventually reopen, in such cases.

**Comment by djowel** [comment]
> It turned out that my requirements for this was for the wrong case, out of the library scope, so I'm sorry for the noise.
> I guess it might be useful instead in cases like native platform modal dialogs or docking windows, which should work outside the view that requires the native window/view to be passed as parent, so please let me know if to keep this open, or close and eventually reopen, in such cases.

That would be a rework on the window and app classes. I'm fine if anyone wants to work on this.

**Comment by thirtythreeforty** [comment]
I am attempting to implement this - the goal is to embed my window within a VST host's display, and to do that I need the X11 window handle. The goal is an API that is eventually (on Linux as an example):

```c++
    GtkWidget* window::get_native_handle();
```

However, doing this will move the include of GTK from a _private_ dependency of Elements to a _public_ one, so that the GtkWidget typedef is available to consumers in the header file.  Is this acceptable?

**Comment by djowel** [comment]
> However, doing this will move the include of GTK from a _private_ dependency of Elements to a _public_ one, so that the GtkWidget typedef is available to consumers in the header file. Is this acceptable?

Should be fine.
