### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by bizehao** [cycfi/elements#292]
` view_.content(fixed_size({1000, 600}, vtile(button("111"), button("222"))), background);`
![image](https://user-images.githubusercontent.com/33247680/150157232-6cf325f8-7227-46d6-be3f-2995d874675d.png)

Normally, the size of the window should be 1000 * 600. Why is it compressed to exactly the height of the button?

**Comment by bizehao** [comment]
I know that using vstretch can display normal, but it has a conflict.

**Comment by djowel** [comment]
See https://cycfi.github.io/elements/layout#size-elements: "The limits of subject will be set to the specified limits constrained by the natural limits of the subject (the natural limits of the element will not be violated)."

The buttons have fixed vertical sizes (while having flexible horizontal sizes). What you can do is place the buttons inside a vertical align element, thereby making it flexible vertically. See https://cycfi.github.io/elements/layout#align-elements

**Comment by bizehao** [comment]
> Are you expecting an empty surface below buttons ? 

Yes, I hope that the following is blank, similar to QVBoxLayout in QT

**Comment by bizehao** [comment]
> See https://cycfi.github.io/elements/layout#size-elements: "The limits of subject will be set to the specified limits constrained by the natural limits of the subject (the natural limits of the element will not be violated)."
> 
> The buttons have fixed vertical sizes (while having flexible horizontal sizes). What you can do is place the buttons inside a vertical align element, thereby making it flexible vertically. See https://cycfi.github.io/elements/layout#align-elements

ok，I tried, the height of the entire layout was influenced by the height of the internal sub-elements.

**Comment by bizehao** [comment]
valign ，It is useful

**Comment by djowel** [comment]
> valign ，It is useful

I'll close this issue now. Tell us if you have any more questions.

**Comment by bizehao** [comment]
![image](https://user-images.githubusercontent.com/33247680/150247607-d4ef820e-4104-4c30-8b70-88d4d78e4a26.png)
![image](https://user-images.githubusercontent.com/33247680/150247678-eebd4485-5452-478f-b787-20f6c1caad35.png)
vstretch  It doesn't work.

**Comment by djowel** [comment]
Two things: 1. Please file another github issue (perhaps about vstretch). 2. Please post an MVCE instead of screenshots.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by bizehao** [comment]
ok

**Comment by bizehao** [comment]
Sorry, I didn't pay attention before, thank you for your fingertips.
