### ISSUE TITLE
Keyboard input Caton

### ISSUE THREAD

**Issue by bizehao** [cycfi/elements#293]
When the number of elements on the interface is too large, the interface will get stuck by keyboard input.

**Comment by djowel** [comment]
How many elements and how are the elements arranged? Have you seen this discussion?
https://github.com/cycfi/elements/pull/284

**Comment by bizehao** [comment]
This is a simple epitome of my project:
`auto constexpr bkd_color = rgba(35, 35, 37, 255);
        auto background = box(bkd_color);

        view_.content(
            htile(htile(htile(htile(htile(htile(htile(htile(
                vscroller(vtile(
                button("11"), button("11"), button("11"),
                input_box().first, input_box().first, input_box().first,
                button("11"), button("11"), button("11"),
                input_box().first, input_box().first, input_box().first,
                button("11"), button("11"), button("11"),
                input_box().first, input_box().first, input_box().first,
                button("11"), button("11"), button("11"),
                input_box().first, input_box().first, input_box().first,
                button("11"), button("11"), button("11"),
                input_box().first, input_box().first, input_box().first,
                button("11"), button("11"), button("11"),
                input_box().first, input_box().first, input_box().first,
                button("11"), button("11"), button("11"),
                input_box().first, input_box().first, input_box().first,
                button("11"), button("11"), button("11")
            )))))))))),
            background);

It's very catchy to enter from the keyboard here

**Comment by djowel** [comment]
As the saying goes, "if all you have is a hammer, everything looks like a nail" :-)

Don't use `htiles`  and `vtiles` that way. They are meant for top-level formatting. As I mentioned earlier, have a look at #284. In the layout docs, learn about dynamic lists and grids. For your specific use-case, study the `active_dynamic_list` example in the `develop` branch.

**Comment by bizehao** [comment]
ok, I see what you mean. I try to reduce the nesting of layouts.
I am currently doing a job, Embed flex layout in elements  [https://github.com/facebook/yoga](https://github.com/facebook/yoga)

**Comment by djowel** [comment]
> ok, I see what you mean. I try to reduce the nesting of layouts. 

Exactly. 

> I am currently doing a job, Embed flex layout in elements https://github.com/facebook/yoga

Cool. Please keep in mind that "Note: Flexbox layout is most appropriate to the components of an application, and small-scale layouts, while the Grid layout is intended for larger scale layouts."

Note: "small scale"

Reference: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

The same is true with element's tiles, grids, and lists. Flex layout can be computationally expensive.

BTW, have you tried the element's flow layout element?

https://cycfi.github.io/elements/layout#flow-element

**Comment by bizehao** [comment]
Not currently used flow layout element.
The element's  layout size is determined by the child elements, I want the layout to constrain the size of the child elements

**Comment by bizehao** [comment]
Thank you for this library. I transplanted flexlayout, yoga and Lottie animation to realize my works.
Do I need to close this issue?

**Comment by djowel** [comment]
Do you have a link to your code you can share here? Is it open source?

**Comment by bizehao** [comment]
OK, I'll optimize the code structure and do it.

**Comment by bizehao** [comment]
[my_test.zip](https://github.com/cycfi/elements/files/14165216/my_test.zip)

This is my test case. I used qt to achieve a similar effect, but it was very smooth.

**Comment by bizehao** [comment]
[qt_test.zip](https://github.com/cycfi/elements/files/14165248/qt_test.zip)
This is the test case for qt

**Comment by djowel** [comment]
Removing the odd super nested `htile` makes it go fast in both debug and release modes.

If you can tell me your use-case why you did that, I can show you how to do it properly in elements. 

PS> I'm still curious wha the QT counterpart is of this odd layout composition.

**Comment by bizehao** [comment]
I simulated a layout nesting situation. Sometimes there are various small layout nestings inside a large layout.

**Comment by bizehao** [comment]
I often encounter complex layout scenarios. Generally, if there is FlexLayout, it will be a good solution, but if there is no FlexLayout, it can only be arranged in a horizontal layout and vertical layout.

**Comment by djowel** [comment]
Again, if you can show me a specific and clear use-case, I'd be glad to show you how to do it. Take note that the ActiveList example has thousands of text boxes without any slowdown.

**Comment by bizehao** [comment]
No problem, I will show you

**Comment by bizehao** [comment]
This is a smaller version of my project.   
[my_test.zip](https://github.com/cycfi/elements/files/14204475/my_test.zip)

**Comment by djowel** [comment]
Try this:

```
/*=================================================================================================
   Copyright (c) 2016-2023 Joel de Guzman

   Distributed under the MIT License (https://opensource.org/licenses/MIT)
=================================================================================================*/
#include <elements.hpp>

namespace elements = cycfi::elements;
namespace artist = cycfi::artist;
using namespace elements;

// Main window background color
auto constexpr bkd_color = artist::rgba(35, 35, 37, 255);
auto background = elements::box(bkd_color);

auto makeInput()
{
   return align_center(fixed_size({50, 50}, input_box().first));
}

auto makeWidget1(const std::string labelStr)
{
   auto top = align_center(makeInput());
   auto leftAndRight =
       htile(
         align_left(makeInput()),
         label(labelStr),
         align_right(makeInput())
       );
   auto bottom = align_center(makeInput());
   auto widget = vtile(top, vspace(5), leftAndRight, vspace(5), bottom);
   return widget;
}

int main(int argc, char *argv[])
{
   elements::app _app(argc, argv, "Model", "com.cycfi.model");
   elements::window _win(_app.name());
   _win.on_close = [&_app]() { _app.stop(); };

   elements::view view_(_win);

   auto widthAndHeight =
      htile(
         top_caption(makeInput(), "width"),
         top_caption(makeInput(), "height")
      );

   auto minWidthAndHeight =
      htile(
         top_caption(makeInput(), "min-width"),
         top_caption(makeInput(), "min-height")
      );

   auto maxWidthAndHeight =
      htile(
         top_caption(makeInput(), "max-width"),
         top_caption(makeInput(), "max-height")
      );

   constexpr int space = 20;
   auto w1 =
      margin({10, 10, 10, 10},
         vtile(
            align_middle(widthAndHeight),
            vspace(5),
            align_middle(minWidthAndHeight),
            vspace(5),
            align_middle(maxWidthAndHeight),
            vspace(5),
            align_middle(makeWidget1("padding")),
            vspace(5),
            align_middle(makeWidget1("border")),
            vspace(5),
            align_middle(makeWidget1("margin")),
            vspace(5),
            align_middle(makeWidget1("position"))
         )
      );

   frame draw;
   static float const coords[] = {0.8, 1.0};
   auto w2 = hgrid(coords, draw, w1);

   auto main_pane = pane(heading{"title"}, w2);

   auto tabWidget =
       vnotebook(
         view_,
         deck(layer(main_pane, frame{}), frame{}, frame{}),
         tab("test1"), tab("test2"), tab("test3")
      );

   auto head = htile(button("button1"), button("button2"));
   auto body = vtile(head, vspace(10), main_pane);

   view_.content(body, background);

   _app.run();
   return 0;
}
```

**Comment by djowel** [comment]
It could still be better, but, I'm busy right now. 

In general:
- avoid too many nested layouts. 
- I'd use more more grids instead of htile/vtile (see how I used that at the top level):

```
   static float const coords[] = {0.8, 1.0};
   auto w2 = hgrid(coords, draw, w1);
```

**Comment by bizehao** [comment]
Thank you for your operation. I tested it and it is very fast now. Thank you. I have studied your code and it is very useful. I usually use grid layout to arrange things in a palace format. For complex ones, I usually use flex layout. I plan to add a flex layout, like [yoga](https://github.com/facebook/yoga), But the layout code can only be written in imperative style.

**Comment by djowel** [comment]
> Thank you for your operation. I tested it and it is very fast now. Thank you. I have studied your code and it is very useful. I usually use grid layout to arrange things in a palace format. For complex ones, I usually use flex layout. I plan to add a flex layout, like [yoga](https://github.com/facebook/yoga), But the layout code can only be written in imperative style.

Alright, I'm going to close this now. How about opening another issue and tell me more about the "flex" features you like to see in elements. I might have some ideas on how to implement it.
