### ISSUE TITLE
Successfull on Windows 

### ISSUE THREAD

**Issue by phicore** [cycfi/elements#3]
Just to let you know that everything (from the Windows-port branch) builds 
correctly under Windows

Target : Windows 10
Toochain: Visual Studio 2017 (15.9 version)

I had initially trouble with installing boost with the instruction on the boost site
and I was using MSVC 15.6 which lacks some C++17 compatibility.

Finally after building and installing vcpkg and using it to get the boost packages 
needed to build, upgrading the visual studio to 15.9 everything worked out of the box...

![image](https://user-images.githubusercontent.com/6534441/61966513-13ffc400-afd3-11e9-8a6b-a2ff469037ce.png)

![image](https://user-images.githubusercontent.com/6534441/61966584-3db8eb00-afd3-11e9-8d66-8aef4ecd497a.png)

![image](https://user-images.githubusercontent.com/6534441/61966596-4ad5da00-afd3-11e9-8870-b0c6fd92596e.png)

![image](https://user-images.githubusercontent.com/6534441/61966646-68a33f00-afd3-11e9-8bd1-e0a290c85f10.png)

![image](https://user-images.githubusercontent.com/6534441/61966669-7789f180-afd3-11e9-95cb-2e1f17f8be20.png)

**Comment by djowel** [comment]
Oh please keep in mind that this is still under heavy development. There are still a lot of rough edges. But I'm glad you got it running!

**Comment by phicore** [comment]
It is really nice looking and the declarative side of things is very appealing. But the dependency with boost makes it not so lightweight. I'm also not really a post c++11 educated dev, so some code is very obscure for me for the moment. I will try to learn when time allows it.

Anyway, great work, I hope it gets a great future, the c++ community would need a cross-platform GUI toolkit. Juce and QT are successes, I guess, but licensing will always limit the audience.

Another question: Beside musical dashboard like application, do you envision it more for desktop like apps (would need features like MDI, splitter windows, docking, etc...) or more for touch based app (would need another set of feature and interaction, like kinetic scrolling, etc...)? Personally, I would need it for touch based apps.

**Comment by djowel** [comment]
> It is really nice looking and the declarative side of things is very appealing. But the dependency with boost makes it not so lightweight. I'm also not really a post c++11 educated dev, so some code is very obscure for me for the moment. I will try to learn when time allows it.

Oh dependency on Boost is very light weight! Keep in mind that Boost is not monolithic. I only depend on a very few of Boost libraries.

> Another question: Beside musical dashboard like application, do you envision it more for desktop like apps (would need features like MDI, splitter windows, docking, etc...) or more for touch based apps (would need another set of features and interactions, like kinetic scrolling, etc...)? Personally, I would need it for touch based apps.

Absolutely! One step at a time :-) But contributions are always welcome.

**Comment by phicore** [comment]
Thanks, time will tell...

**Comment by djowel** [comment]
BTW, thanks for letting me know it's building for you. I'll add build Instructions for Windows as soon as I can.

**Comment by Xeverous** [comment]
As a someone who is interested in using the library (but need more features), I would like a wiki/separate readme with a list of widgets (maybe as a part of upcoming documentation). Many GUI libraries have all kinds of widgets but for some reasons I struggle to find a library (different than Qt or something with restricting licenses) which has all of them:

- three state checkbox
- generic slider (something simple and small enough, eg for volume slider)
- combox with a filter
- rich text box (support for arbitrary colors for arbitrary letters)
- some grid view optimized for displaying a subset of a large data structure

**Comment by djowel** [comment]
> * three state checkbox

Nods. Very easy to add. 

> * generic slider (something simple and small enough, eg for volume slider)

Available. But what do you mean by "generic"?

> * combox with a filter

Normally, you'd implement the filtering your self.

> * rich text box (support for arbitrary colors for arbitrary letters)

I have no need for a rich text box at the moment (I only implement what I need, for lack of time). Unless someone contributes that, it won't happen any time soon.

> * some grid view optimized for displaying a subset of a large data structure

This, I'll probably need, but probably not any time soon.

**Comment by Xeverous** [comment]
> But what do you mean by "generic"?

No artificial constraints like limited range of values or limited number of thresholds the slider can stay at. I think the best solution is to either make it a template or the value of the slider should be returned as a double between 0 and 1.

> Normally, you'd implement the filtering yourself.

Ok, but such combobox should be opened while entering the filter. People would expect to be able to write into the combobox directly and a list of options would update immediately.

**Comment by djowel** [comment]
> No artificial constraints like limited range of values or limited number of thresholds the slider can stay at. I think the best solution is to either make it a template or the value of the slider should be returned as a double between 0 and 1.

Yes. The slider's values are always in the 0.0 to 1.0 range.

> Ok, but such combobox should be opened while entering the filter. People would expect to be able to write into the combobox directly and a list of options would update immediately.

I'm not sure what you mean by "opened".

**Comment by phicore** [comment]
I would propose that new subjects need opening new issues. It would be better for future reference.

**Comment by Xeverous** [comment]
> I'm not sure what you mean by "opened".

Basically, I would like filterable combobox to work exactly as `name` or `mods` fields on this page: http://poe.trade/

These boxes looks like a normal text fields, but will expand and propose choices when you start typing.

**Comment by phicore** [comment]
On top left there is a red button showing that this thread is closed.
