### ISSUE TITLE
element.hpp - duplicated smart pointer aliases

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#30]
I guess the ones in the class can be removed?

https://github.com/cycfi/elements/blob/c5dc70e0fd32f564bbd3d968bb815aebc2a1aad0/lib/include/elements/element/element.hpp#L28-L33

https://github.com/cycfi/elements/blob/c5dc70e0fd32f564bbd3d968bb815aebc2a1aad0/lib/include/elements/element/element.hpp#L82-L85

**Comment by djowel** [comment]
Makes sense. A bit different though, esp. if a subclass is not in the same namespace, but I suppose that can easily be 'fixed'.

**Comment by Xeverous** [comment]
#43

**Comment by Xeverous** [comment]
#43 merged, closing
