### ISSUE TITLE
Webpage margins too wide on mobile

### ISSUE THREAD

**Issue by thirtythreeforty** [cycfi/elements#309]
The documentation is excellent, but somewhat difficult to read on mobile:

![Screenshot_20220814-114058.png](https://user-images.githubusercontent.com/3952613/184546634-4561edb5-075c-442b-bdb9-a1117e8e12c5.png)

The margins should be responsive to the screen width.

**Comment by djowel** [comment]
Good catch! Would you like to offer a PR to fix this?

**Comment by thirtythreeforty** [comment]
I am not a web developer, but I can probably work media queries well enough to send a PR :) where is the source for the docs? I don't see them in the main repo.

**Comment by redtide** [comment]
https://github.com/cycfi/cycfi.github.io/
