### ISSUE TITLE
device_to_user point conversion

### ISSUE THREAD

**Issue by ex-purple** [cycfi/elements#314]
Hi!
Why does the **canvas::device_to_user** method use **cairo_device_to_user_distance** instead of **cairo_device_to_user**?

Because of this, an unpleasant effect is observed:
```
canvas.translate({10, 10});

point p{0, 0};
auto up = canvas.device_to_user(p);
assert(up != p); // Fail!
```

The distance in both systems is the same, but the coordinate must be different

**Comment by djowel** [comment]
I'm not sure why, actually. But it does look wrong. It might be a workaround to another bug. Could you try it and see what happens to the examples? Then we can do the proper fix.

Thanks for reporting this!

**Comment by ex-purple** [comment]
Examples:
- [] empty
- [] hello_universe
- [] text_and_icons
- [] buttons
- [] menus
- [] basic_sliders_and_knobs
- [] sprite_sliders_and_knobs
- [] text_edit
- [] layout
- [] popups
- [] dialogs
- [] scale
- [] notebook
- [] doc_aspects
- [] simple_animation
- [] thumbwheels
- [] tooltip
- [] dynamic_list
- [] active_dynamic_list
- [] custom_control
- [] child_window
- [] sync_scrollbars
- [] icons_list []

**Comment by ex-purple** [comment]
Everything looks good
