### ISSUE TITLE
progress bar widget

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#32]
This issue is for tracking any decisions before implementing this widget.

Ideally, we want to support different behaviors:
  - being able to specify the fill color
  - support for arbitrary rectangle size
  - support for both horizontal and vertical placement
  - progress circle widget? could have the same interface, just different `draw()` method implementation
  - support for indeterminate progress state (that is, instead of increasing filling of the rectangle, a generic animation of a moving bar)

**Comment by djowel** [comment]
For the bar: Make it generic. Actually, this can already be implemented by writing a gallery code (no need for specialized subclasses). Basically, it's just a 2-element layer with 1) background layer 2) bar. The bar can be a 2-element horizontal tile with 1) left element, whatever you want to place there (template param) 2) right element, an empty element (infinitely stretchable). Then, you can modulate/adjust the 'span' of the left and right elements. See the tiles demo for inspiration.

For the circular thing, it can be a specialization or generalization of the knob. The basic idea is that we want to be as modular and reusable as possible down to the most basic elements. Actually, thinking about it, the bar can also be a generalization of the slider (e.g. a thumb-less slider).

Animation: let's talk about this; there's a facility, using ASIO for this that I should probably discuss.

**Comment by djowel** [comment]
After thinking about it, I think we need to generalize the code of sliders and knobs to implement bars. We can probably call it "linear_element" and "circular_element". The generalization should be able to support these things. Might be a good exercise! :-)

**Comment by Xeverous** [comment]
> The bar can be a 2-element horizontal tile with 1) left element, whatever you want to place there (template param) 2) right element, an empty element (infinitely stretchable). Then, you can modulate/adjust the 'span' of the left and right elements. See the tiles demo for inspiration.

I understand the 2-layer idea just how it is done in button but I don't get this. Isn't the bar (the fill) a just 1 rectangle? Or do you want to support very more complex bars like `[___###___]` which goes from middle outwards instead of traditional `[####____]` which goes only from left to right?

> For the circular thing, it can be a specialization or generalization of the knob. The basic idea is that we want to be as modular and reusable as possible down to the most basic elements

The knob is more complicated (it has some logic and more drawn elements) so it will likely be reusing bar or its parent type code.

> Animation: let's talk about this; there's a facility, using ASIO for this

Not sure what are the ASIO capabilities for this, but I would really like to have animations based on typical time deltas and update function ... for this elements would need to support user event loops and expose such event/time loop functionality on public API.

**Comment by djowel** [comment]
> For the bar: Make it generic. Actually, this can already be implemented by writing a gallery code (no need for specialized subclasses). Basically, it's just a 2-element layer with 1) background layer 2) bar. The bar can be a 2-element horizontal tile with 1) left element, whatever you want to place there (template param) 2) right element, an empty element (infinitely stretchable). Then, you can modulate/adjust the 'span' of the left and right elements. See the tiles demo for inspiration.
> 
> For the circular thing, it can be a specialization or generalization of the knob. The basic idea is that we want to be as modular and reusable as possible down to the most basic elements. Actually, thinking about it, the bar can also be a generalization of the slider (e.g. a thumb-less slider).

To understand what I mean by this, I suggest studying the slider.hpp code so we can be in the same understanding for 'linear' things. Then, studying dial.hpp would be good to read for 'circular' things.

**Comment by djowel** [comment]
> After thinking about it, I think we need to generalize the code of sliders and knobs to implement bars. We can probably call it "linear_element" and "circular_element". The generalization should be able to support these things. Might be a good exercise! :-)

To understand what I mean by this, I suggest studying the slider.hpp code so we can be in the same understanding for 'linear' things. Then, studying dial.hpp would be good to read for 'circular' things.

**Comment by djowel** [comment]
OK, ignore my previous comments... After thinking about it some more, I think it is best to keep it simple. Premature generalization or too much genericity is also not good. I think it is best to make progress-bar separate and simple. At the very least, I suggest using the basic_slider as an inspiration on how to structure the code, and its use of containment (i.e. _thumb and _body) instead of inheritance.

**Comment by Xeverous** [comment]
Regarding reuse of code: I would like a minimal comments above each class that describe its purpose. For many elements, the inheritance reasons (proxy, deck, layer) are unclear to me (that is, I don't know which code is being reused and why).

**Comment by djowel** [comment]
> Regarding reuse of code: I would like a minimal comments above each class that describe its purpose. For many elements (proxy, deck, layer and more), the inheritance reasons are unclear to me (that is, I don't know what code is being reused and why).

Of course. I can do that retroactively as we go, starting with the element, proxy and composite, which are the most important. Then working my way to each derived class. 

But out of curiosity, have a look at the basic_slider template in slider.hpp, and tell me what is not obvious.

**Comment by Xeverous** [comment]
`basic_slider`? Actually nothing. The most of unclear functions come from the base `element` class: `is_control`, `limits`, `layout`.

**Comment by Xeverous** [comment]
Trying to implement progress bar on a branch, got a couple of questions:
- What should the progress bar inherit from? `array_composite<2, deck_element>`?
- How should I pass the state (`double` in range `0.0` - `1.0`) to the bar elements (background, foreground) so they can be drawn correctly?
- How "generic" the class should be? My ideas so far:
  - Inherit from `array_composite<2, deck_element>` just like `button` to allow 2 arbitrary elements? I got the problem with passing state to the `draw()`.
  - Inherit from just `element`? The simplest implementation would have only 3 variables: background color, foreground color and the value. But such implementation does not allow fancy things like custom background/foreground image.

**Comment by djowel** [comment]
> * What should the progress bar inherit from? `array_composite<2, deck_element>`?

Or none at all. Have you studied the slider code? It's closest to what you want to do.

> * How should I pass the state (`double` in range `0.0` - `1.0`) to the bar elements (background, foreground) so they can be drawn correctly?

Actually there is a way, but you want to avoid passing state or any info as much as possible. The subjects should be oblivious to any of that. For example, the button subjects do not know anything about the button states. The slider thumb and track also do not know anything about the slider. 

What state info do you want to pass? I might be able to offer an alternative way, following the elements' way of composing.

> * How "generic" the class should be? My ideas so far:
>   
>   * Inherit from `array_composite<2, deck_element>` just like `button` to allow 2 arbitrary elements? I got the problem with passing state to the `draw()`.
>   * Inherit from just `element`? The simplest implementation would have only 3 variables: background color, foreground color and the value. But such implementation does not allow fancy things like custom background/foreground image.

Just inherit from element. Also, I dissuade you from having fixed behavior with background color and foreground color. The subjects should be free to draw anything. For example, your foreground can be an image element or just a solid color element. The bar should not care about how it draws its elements, but it should care about how it *layouts* its elements given its *value* from 0.0-1.0. I suggest studying the slider for better understanding (ignoring tracker because you do not need mouse tracking).

**Comment by Xeverous** [comment]
> "The bar should not care about how the elements are drawn, but it should care about how it layouts its elements given its value from 0.0-1.0. I suggest studying the slider for better understanding"

Very helpful comment - I tried to mimic button's code but should actually look at the slider. Now, after reading slider, I get how it should work. I see already there will be some common logic - perhaps I should create a common base class for slider and progress bar that will contain that logic. Not sure how to name such type - it will be a generic element allowing values in range 0 - 1 and having functions used for the layout.

**Comment by djowel** [comment]
> > "The bar should not care about how the elements are drawn, but it should care about how it layouts its elements given its value from 0.0-1.0. I suggest studying the slider for better understanding"
> 
> Very helpful comment - I tried to mimic button's code but should actually look at the slider. Now, after reading slider, I get how it should work. I see already there will be some common logic - perhaps I should create a common base class for slider and progress bar that will contain that logic. Not sure how to name such type - it will be a generic element allowing values in range 0 - 1 and having functions used for the layout. The rect also has some generic functions for layouting, btw.

That is what I was trying to say initially above (see comments about "linear_element" and "circular_element"). My thinking now is that this is premature generalization or too much generalization. Instead of this, what we can do is share code using helper utilities, such as the one I have for text_utils.hpp. IOTW, you generalize the algorithms, but not the class.

BTW, all relevant elements have normalized "value"s from 0.0-1.0 by design.

For example, the scrollbars also have a value from 0.0-1.0, but I decided not to generalize scrollbars and sliders.

**Comment by Xeverous** [comment]
> all relevant elements have normalized "value"s from 0.0-1.0 by design.

Is this invariant checked? I haven't seen any validation in ctors so it is either just clamped in the implementation or we go UB.

**Comment by djowel** [comment]
> Is this invariant checked? I haven't seen any validation in ctors so it is either just clamped in the implementation or we go UB.

It's more like a protocol, rather than an invariant. This can be violated in certain cases, but the subject should be able to handle it (clamping is one possibility). UI violations should react gracefully.

**Comment by Xeverous** [comment]
Explain this pls:

https://github.com/cycfi/elements/blob/02c1ab01cbcd887c640e3bf130e28618339aa58c/lib/src/element/slider.cpp#L13-L34

- Why there are `* 2`?
- Why the last line in both `if` branches does nothing (it maxes on the same variable)?

**Comment by djowel** [comment]
> * Why there are `* 2`?

Basically, two times the height/width of the thumb to *always* allow some space for movement.

> * Why the last line in both `if` branches does nothing (it maxes on the same variable)?

Probably an unnecessary artifact; can be removed.

**Comment by Xeverous** [comment]
See #59. The only thing I'm unsure about is the order of arguments (currently: background, foreground).
