### ISSUE TITLE
reactivity?

### ISSUE THREAD

**Issue by wtholliday** [cycfi/elements#320]
Reactivity may be more than what you want to tackle. But I thought I'd suggest it.

elements seems to be a traditional OOP gui with a nicer syntax for static UIs. But as soon as things get sufficiently dynamic, you are explicitly mutating views and you'll end up with the same state-synchronization issues that plague traditional OOP UIs.

As an example, in SwiftUI we might have something like:

```
ForEach(namedFonts) { namedFont in
        Text(namedFont.name)
            .font(namedFont.font)
    }
```

(see https://developer.apple.com/documentation/swiftui/foreach)

this "computes views on demand from an underlying collection of identified data"

so it automatically updates when your underlying data changes. There is no need for explicit synchronization between the data model and UI.

In elements, as I understand it, something like this would involve a `deck`, or perhaps a `dynamic_list`.

Referring to the example above, if my set of `namedFonts` changes, then I need to explicitly update the `deck` (and I need to keep around a reference to the deck).

I would recommend working through the SwiftUI tutorial to get a better sense of it: https://developer.apple.com/tutorials/SwiftUI (it may seem time consuming, but it's rather minor compared to developing a whole GUI library :) )

**Comment by djowel** [comment]
> In elements, as I understand it, something like this would involve a `deck`, or perhaps a `dynamic_list`.
> 
> Referring to the example above, if my set of `namedFonts` changes, then I need to explicitly update the `deck` (and I need to keep around a reference to the deck).

That is not correct. Dynamic lists are dynamically created and loaded on demand. No need to update. (not sure what you mean by "keep around a reference to the deck", but I suspect you are expecting the swift UI way of doing things in an entirely different UI library).

**Comment by djowel** [comment]
> sufficiently dynamic

You'll need to define "sufficiently dynamic" and provide a use-case and a set of requirements for it.
