### ISSUE TITLE
tracker<Base>::info

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#35]
`info` has always the same definition, but currently its definition is dependent on the tracker's template type paramer, which might be unwanted - this can cause some interoperatibility issues between different `tracker` instantiations.

https://github.com/cycfi/elements/blob/02c1ab01cbcd887c640e3bf130e28618339aa58c/lib/include/elements/element/tracker.hpp#L18-L23

I propose to make `info` a standalone `tracker_info` type.

**Comment by djowel** [comment]
Sounds good. Will you file a PR?

**Comment by Xeverous** [comment]
Working on it and actually got a question - what do we do with the `info_ptr` which is defined inside the class? It's also dependent on the template parameter because it's defined inside the class.

https://github.com/cycfi/elements/blob/02c1ab01cbcd887c640e3bf130e28618339aa58c/lib/include/elements/element/tracker.hpp#L52-L54

**Comment by djowel** [comment]
> what do we do with the `info_ptr` which is defined inside the class? It's also dependent on the template parameter because it's defined inside the class.

The obvious answer is to declare it outside the class too, perhaps tracker_info_ptr.

**Comment by djowel** [comment]
> > what do we do with the `info_ptr` which is defined inside the class? It's also dependent on the template parameter because it's defined inside the class.
> 
> The obvious answer is to declare it outside the class too, perhaps tracker_info_ptr.

On second thought, I'll probably just leave it as it is as I do not see any issue in doing so, do you?

**Comment by Xeverous** [comment]
I see - it will be dependent on the template parameter. Just because it resides in a class template. So passing/storing it will have the same issue: different instantiations will be different types.

**Comment by Xeverous** [comment]
Thinking whether `track_info` or `tracker_info` is better.

**Comment by djowel** [comment]
> Thinking whether `track_info` or `tracker_info` is better.

+1 for `tracker_info`. `track_info` does not make sense, IMO.

**Comment by djowel** [comment]
> I see - it will be dependent on the template parameter. Just because it resides in a class template. So passing/storing it will have the same issue: different instantiations will be different types.

No that is not correct. You are overthinking it... It is just a type alias. C++ does not have strong typedefs/using. `using info_ptr = std::unique_ptr<tracker_info>;` has the same type anywhere.

**Comment by Xeverous** [comment]
True, but then you can not refer through this alias without instantiating the class template. If I have my own type and would like to store it, I would have to store `tracker<T>::info_ptr` where the `T` is some arbitrary choosen type just to make the alias usable.

**Comment by djowel** [comment]
> True, but then you can not refer through this alias without instantiating the class template. If I have my own type and would like to store it, I would have to store `tracker<T>::info_ptr` where the `T` is some arbitrary choosen type just to make the alias usable.

Seems like nitpicking to me ;-) If I have my own type and would like to store it, I would probably store it as `std::unique_ptr<tracker_info>`. Keep in mind, this is in `protected` space.

**Comment by Xeverous** [comment]
See #66.

**Comment by Xeverous** [comment]
PR is merged.
