### ISSUE TITLE
size_element does not produce consistent bounds

### ISSUE THREAD

**Issue by eakoli** [cycfi/elements#357]
In the 'Size Elements' portion of the documentation it is stated that the 'natural limits of the element will not be violated'.  [Reference](https://cycfi.github.io/elements/layout#semantics-1)

I read this as that given a size (F), and limits (L), the resulting size (S) will be constrained by the limits (L). Such that S is as close to F as possible while still satisfying L.min < S < L.max

Based on this code, size_element adjusts the size to a size that is within the element natural limits. (meeting the above rule)
https://github.com/cycfi/elements/blob/f54953d256e2a218fc8bf1e9926d7cbe552f63ed/lib/include/elements/element/size.hpp#L52-L61

But this code, produces a bounds that violates the elements natural limits.
https://github.com/cycfi/elements/blob/f54953d256e2a218fc8bf1e9926d7cbe552f63ed/lib/include/elements/element/size.hpp#L63-L68

I believe the code should be 

```cpp
template <typename Subject>
inline void size_element<Subject>::prepare_subject(context& ctx)
{
      auto e_limits = this->subject().limits(ctx);
      ctx.bounds.right = ctx.bounds.left + e_limits.min.x;
      ctx.bounds.bottom = ctx.bounds.top + e_limits.min.y;
}
```

The same should apply to vsize_element and hsize_element.

Where this is noticeable is in the following example:

```cpp
int main(int argc, char* argv[])
{
   app _app(argc, argv, "Login", "com.cycfi.text-edit");
   window _win(_app.name());
   _win.on_close = [&_app]() { _app.stop(); };

   view view_(_win);

   view_.content(
            align_center_middle(
                hsize(50,button("a really long title for a button"))
            )
        )
        ,box(colors::white)
   );

   _app.run();
   return 0;
}
```

The resulting button is rendered at its minimum size, but can only be clicked on in the left most 50 pixels.

**Comment by djowel** [comment]
Oh!!! There you go. Good catch. Would you be so kind as to make a PR for this? If it's not too much to ask.

**Comment by djowel** [comment]
> Oh!!! There you go. Good catch. Would you be so kind as to make a PR for this? If it's not too much to ask.

Ah, don't bother. I'll do it. It's just two lines anyway. Many thanks for spotting!

**Comment by djowel** [comment]
Fixed. Again, many thanks! Pushed in `develop` and `cairo_2023` branches.

**Comment by djowel** [comment]
Oh... Reopened. Forgot vsize_element and hsize_element. If you can do a quick PR, that would be great. If not, I'll get to this as soon as I can.

**Comment by djowel** [comment]
Oh gee, and the code might still be wrong... Shouldn't it be:

```
    auto  e_limits = this->subject().limits(ctx); 
    float size_x = _size.x; 
    float size_y = _size.y; 
    clamp(size_x, e_limits.min.x, e_limits.max.x); 
    clamp(size_y, e_limits.min.y, e_limits.max.y);
    ctx.bounds.right = ctx.bounds.left + size_x; 
    ctx.bounds.bottom = ctx.bounds.top + size_y; 
```
???

**Comment by eakoli** [comment]
yea ill look at it next week, as I'm having some other oddities in sizing when wrapping a vtile in a hsize, so I think somewhere some math is off, just not sure where yet.

**Comment by djowel** [comment]
One thought: I'll be adding logging soon. In situations where the supplied size violates the limits of the subject, it would be appropriate to issue a warning.

**Comment by eakoli** [comment]
@djowel Do you mean for size_element::prepare_subject? 

size_element::limit already does the clamping with respect to size and returns a limit with no 'range' (min == max) so I think that's ok...

for hsize_element/vsize_element it probably needs to delegate the prepare to the subject() so that it can find out what size the subject wants to be, and then clamp that to the limit/size

**Comment by djowel** [comment]
> for hsize_element/vsize_element it probably needs to delegate the prepare to the subject() so that it can find out what size the subject wants to be, and then clamp that to the limit/size

Oh right! Of course! Seems you have a great deal of familiarity with Element's internals and behavior!

**Comment by djowel** [comment]
> > for hsize_element/vsize_element it probably needs to delegate the prepare to the subject() so that it can find out what size the subject wants to be, and then clamp that to the limit/size
> 
> Oh right! Of course! Seems you have a great deal of familiarity with Element's internals and behavior!

Hah! I spoke too fast... Except that you are calling `auto e_limits = this->subject().limits(ctx);` It should be:

```
template <typename Subject>
inline void size_element<Subject>::prepare_subject(context& ctx)
{
      auto our_limits = this->limits(ctx);
      ctx.bounds.right = ctx.bounds.left + our_limits.min.x;
      ctx.bounds.bottom = ctx.bounds.top + our_limits.min.y;
}
```

To have the effect that you desire. But! Again, this will set the limits to the `min`-imum, which is not necessarily what we want because the actual size may be somewhere in between `min` and `max`.

Hence, the code I gave still holds.

**Comment by eakoli** [comment]
Ahh...yea needs to use THIS limits not the subject limits.

But for hsize/vsize I think it's a tad more complex, as the opposite axis should be what the subject wants, not fixed to the min or max of the limits.

**Comment by eakoli** [comment]
I think I traced down the oddity I mentioned with vtile.

It builds down to trying to have a layout that is a fixed with and everything in it expand to that max. Which works fine for a layout like
```
hsize( 300, layout( vtile( 
    button("bob")
)))
```

but when you use something like a label, that has absolute max's, it means that the vtile gets contained to that max as well.
It gets even messier if you need to nest a vtile inside a vtile.

seems like containers need to either come in two different flavors (hugging and non-hugging) or you 'enable' hugging by wrapping inside a size/hsize/vsize to limit the size

**Comment by djowel** [comment]
> but when you use something like a label, that has absolute max's, it means that the vtile gets contained to that max as well. It gets even messier if you need to nest a vtile inside a vtile.
> 
> seems like containers need to either come in two different flavors (hugging and non-hugging) or you 'enable' hugging by wrapping inside a size/hsize/vsize to limit the size

If you can show me a minimal, complete and verifiable example (MCVE), I can investigate. 

That said, in general, you use tiles only as a fluid (flowable) outer layout mechanism that adjusts to window resizing. Tiles layouts are typically one-dimensional in their major axis and two-dimensional if you embed an `htile` in a `vtile` (or the inverse). If you need a moe complex hierarchial layout, use grids (hgrids and vgrids), which work on percentages.

**Comment by eakoli** [comment]
From what I can tell https://github.com/cycfi/elements/pull/359 seems to have fixed it.
