### ISSUE TITLE
view.h missing include

### ISSUE THREAD

**Issue by bruno-j-nicoletti** [cycfi/elements#385]
I've just updated to the latest master. If I include `view.h` without first including `infra/support.hpp` I get the following build error...

```
In file included from /Users/bruno/Work/kaiju/submodules/elements/lib/include/elements.hpp:11:
/Users/bruno/Work/kaiju/submodules/elements/lib/include/elements/view.hpp:165:4: error: unknown type name 'CYCFI_FORCE_INLINE'
  165 |    CYCFI_FORCE_INLINE point cursor_pos(view const& v)
      |    ^
/Users/bruno/Work/kaiju/submodules/elements/lib/include/elements/view.hpp:165:28: error: expected ';' after top level declarator
  165 |    CYCFI_FORCE_INLINE point cursor_pos(view const& v)
      |                            ^
      |                            ;
/Users/bruno/Work/kaiju/submodules/elements/lib/include/elements/view.hpp:171:4: error: unknown type name 'CYCFI_FORCE_INLINE'
  171 |    CYCFI_FORCE_INLINE rect view_bounds(view const& v)
      |    ^
/Users/bruno/Work/kaiju/submodules/elements/lib/include/elements/view.hpp:171:27: error: expected ';' after top level declarator
  171 |    CYCFI_FORCE_INLINE rect view_bounds(view const& v)
      |                           ^
      |                           ;
```

`view.h` should include `infra/support.hpp`

**Comment by djowel** [comment]
Thanks for spotting!

**Comment by bruno-j-nicoletti** [comment]
I've also had to add an explicit dependency on `artist` in my cmake, and unless I put `elements` before `artist` it will grab the `infra/support.hpp` from artist and still fail. A suggestion is that you namespace header files to avoid that kind of problem. So something like `infra/artist_support.hpp` for artist and `infra/elements_support.hpp` for elements. 

I can't wait for modules to be fully supported in the C++ tool chain to get around those kind of issues.

**Comment by bruno-j-nicoletti** [comment]
Ah, just spotted that you have deprecated artist.

**Comment by djowel** [comment]
> Ah, just spotted that you have deprecated artist.

No, I haven't. It just needs more work. Eventually, both Skia and Cairo will be integrated into artist.

**Comment by djowel** [comment]
> I've also had to add an explicit dependency on `artist` in my cmake, and unless I put `elements` before `artist` it will grab the `infra/support.hpp` from artist and still fail. A suggestion is that you namespace header files to avoid that kind of problem. So something like `infra/artist_support.hpp` for artist and `infra/elements_support.hpp` for elements.
> 
> I can't wait for modules to be fully supported in the C++ tool chain to get around those kind of issues.

This looks like a separate issue. Please file another issue so it won't get dropped. Either way, it will be a temporary matter before master and skia_2024 will be integrated into one.

**Comment by djowel** [comment]
> > I've also had to add an explicit dependency on `artist` in my cmake, and unless I put `elements` before `artist` it will grab the `infra/support.hpp` from artist and still fail. A suggestion is that you namespace header files to avoid that kind of problem. So something like `infra/artist_support.hpp` for artist and `infra/elements_support.hpp` for elements.
> > I can't wait for modules to be fully supported in the C++ tool chain to get around those kind of issues.
> 
> This looks like a separate issue. Please file another issue so it won't get dropped. Either way, it will be a temporary matter before master and skia_2024 will be integrated into one, so perhaps it's not relevant in the future anyway.

Ahh... no... it will still be relevant. But a better solution is to not have elements depend directly on infra, but reuse the infra that artist depends on.
