### ISSUE TITLE
Why is GDK_SMOOTH_SCROLL_MASK commented out in the GTK host?

### ISSUE THREAD

**Issue by djowel** [cycfi/elements#390]

**Comment by redtide** [comment]
It seems it was added from the beginning as [commented](https://github.com/cycfi/elements/commit/6db0ee4ac48ba8530719cf56c05cb01898df7239#diff-dcacddbfe6ca3351b9908069d86b3abed8a438da240d5f305eeacd5dbe35b909R249)

**Comment by djowel** [comment]
Fixed in `master` and `skia_2024`.
