### ISSUE TITLE
Using open_popup to show a message_box2 causes keyboard-input to not be recognized as button clicks

### ISSUE THREAD

**Issue by Flole998** [cycfi/elements#398]
```
    app _ap("Test");
    window _wn("Test");
    view _vw(_wn);
    _vw.content(
            background
    );
    auto popup1 = message_box2(_vw, "Danger! Do not press enter!", icons::attention, []() {
    }, []() {});
    auto popup = message_box2(_vw, "You can press enter!", icons::attention, [&_vw, &popup1]() {
        open_popup(popup1, _vw);
    }, []() {});
    open_popup(popup, _vw);

    _ap.run();
```

Running this on Windows, the first popup can not be cancelled by pressing the escape-key or ok'ed by pressing the enter-key. The second popup can be dismissed by pressing escape (to cancel) or enter (to "ok"),

**Comment by Flole998** [comment]
Additionally, clicking on the background stops the keys from working, and clicking on the popup again never restores the functionality. So it breaks the second popup if you click on the background after it opened, and clicking on the popup does not fix it again.

**Comment by djowel** [comment]
Keyboard focus at startup works on Windows now.

**Comment by djowel** [comment]
> Additionally, clicking on the background stops the keys from working, and clicking on the popup again never restores the functionality. So it breaks the second popup if you click on the background after it opened, and clicking on the popup does not fix it again.

This is also fixed now. 

I'll keep this open. There's still Linux.

**Comment by djowel** [comment]
I just checked. It works on Linux.
