### ISSUE TITLE
Windows x86 compilation

### ISSUE THREAD

**Issue by phicore** [cycfi/elements#4]
To be able to compile the windows_port branch under windows x86 (32bits)
I had to correct the linking of the provided FreeType binary.

The CMakeFile.txt list it under "Win86" folder, I should be "Win32"

**Comment by djowel** [comment]
Nice! Would be so kind as to provide a PR for this? Is that all you need to do? Thanks!

**Comment by phicore** [comment]
I'm currently not in situation to do a PR. But this is a one line change. All that is to be done is to edit the lib\CMakeList.txt file and replacing the occurrence of Win86 by Win32
![elt-cmakebug](https://user-images.githubusercontent.com/6534441/62192011-16687200-b375-11e9-85ba-b9251ea0fdea.png)

**Comment by djowel** [comment]
> I'm currently not in situation to do a PR. But this is a one line change. All that is to be done is to edit the lib\CMakeList.txt file and replacing the occurrence of Win86 by Win32

Ah right. My bad.

**Comment by djowel** [comment]
Fixed. Thanks!
