### ISSUE TITLE
rich text label

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#40]
This issue is for tracking any decisions before implementing this widget.

Wanted:
- arbitrary text color in arbitrary places
- arbitrary font support
- bold, underline, italic

Need ideas how the widget data should be stored and how to offer a convenient API for adding/editing rich text. There is definitely a better way than a vector of "character" objects, each having color, font, bold, italic and underline variables.

**Comment by Xeverous** [comment]
I see that the color of the label could easily be exposed on the public API, it's already being setup before drawing:

https://github.com/cycfi/elements/blob/70310d96839d1c968ae710e4d88efcfc68591c0c/lib/src/element/misc.cpp#L110-L127

My questions are:

- Are you fine with exposing more the cairo's functionality outside? Specifically, bold, italic and font color (independently for each label)
- What's the rationale behind current label and font implementation? I'm concerned about the efficiency.
  - Everytime a label is being drawn, a font object is searched by a string. (1)
  - Everytime canvas fill style is changed, it creates a new function object (potential allocation) (2)
- Do you have any recommendations on a rich text label implementation? (using multiple label widgets vs extending label interface to support more control)

1:

https://github.com/cycfi/elements/blob/70310d96839d1c968ae710e4d88efcfc68591c0c/lib/include/elements/support/detail/canvas_impl.hpp#L284-L298

2:

https://github.com/cycfi/elements/blob/70310d96839d1c968ae710e4d88efcfc68591c0c/lib/include/elements/support/detail/canvas_impl.hpp#L174-L182

I'm asking for this because I had a bad experience with SFGUI (GUI extension for SFML) which had a widget-related overhead big enough that having around 100 buttons (even with the same state) pushed drawing time beyond usable (up to 1s per frame).

For 1, the label could just take a font reference in its ctor. This pushes some lifetime management to the user. Or, for storing font objects, elements may use an associative container with O(1) value-by-key access where keys are unique and non-repeating which allows to detect invalidated keys.

**Comment by djowel** [comment]
Those are very valid points. You probably know by now, in our recent discussion, that I am not OK exposing cairo's functionality outside. On the contrary, I want to hide it, and abstract cairo away. I'd like to deal with this "rich text" myself, as it is in my TODO list already. Yes, ideally, there should be font objects that you pass easily, cheaply. It is not in the /canvas/ API yet, but ought to be. I am not quite happy with the text and font facilities exposed by /canvas/ yet. For example, it is embarrassingly using the "toy" cairo interface for text handling (see cairo_select_font_face in https://www.cairographics.org/manual/cairo-text.html). The "correct" way would be to use other libraries for font handling, and perhaps for text layout too, especially if we're aiming for editable rich text(!)

As for lifetime management, there are only a few fonts typically used in an application. A global container should be enough. 

I'll review the current state and find ways forward.

**Comment by Xeverous** [comment]
Ok, let me know of anything when you make progress. Viewable (not necessarily editable) rich text is my second most wanted feature after tabs.

**Comment by djowel** [comment]
So actually, we do have support for advanced glyphs:

https://github.com/cycfi/elements/blob/master/lib/include/elements/support/glyphs.hpp

What I am doing now is improve on that and have a simple facade layer for easy things like static "rich text" support. 

- arbitrary text color in arbitrary places
 Not a problem

- arbitrary font support
Yes

- bold, underline, italic
See "17. Is it  possible to perform styling" here:
https://www.freetype.org/freetype1/docs/faq/freetype1.txt

**Comment by djowel** [comment]
I would advise against misuse, or overuse of "rich text" in user ui elements though. Typically, such overuse is a sign of poor or amateurish UI design with lots of fonts all over the place. The better strategy is based on themes where you have only a handful of types/fonts for things such as labels, headings, etc. There is consistency, and you can switch the whole application to a new "theme" anytime.

**Comment by Xeverous** [comment]
>> arbitrary text color in arbitrary places

> Not a problem

How would such things be implemented in the API? I guess there is a better way than storing an array of colors that is as long as the string.

>> bold, underline, italic

> See "17. Is it possible to perform styling" here https://www.freetype.org/freetype1/docs/faq/freetype1.txt

So bold and italic can just be separate font files. Could we make an API for this so that one can load multiple font files with these stylings and fallback to runtime transformations when loaded fonts do not support them out of the box? Basically I thought of an API that hides how many font files were loaded and offers all of B/I/U/S stylings.

**Comment by djowel** [comment]
> So bold and italic can just be separate font files. Could we make an API for this so that one can load multiple font files with these stylings and fallback to runtime transformations when loaded fonts do not support them out of the box? Basically I thought of an API that hides how many font files were loaded and offers all of B/I/U/S stylings.

I'm starting such a thing here:
https://github.com/cycfi/elements/blob/text_revisit/lib/include/elements/support/font.hpp
https://github.com/cycfi/elements/blob/text_revisit/lib/src/support/font.cpp

`font` will support matrix manipulations for pseudo italics and bold (i.e. https://www.cairographics.org/manual/cairo-text.html#cairo-set-font-matrix). Work in progress... 

The canvas and text utils in that branch already support the `font` class (which takes care of your initial issue, e.g. "the label could just take a font reference in its ctor").

**Comment by djowel** [comment]
Here's the new `font.hpp` header:
https://github.com/cycfi/elements/blob/text_revisit/lib/include/elements/support/font.hpp

It is now used in the theme. For example:
```c++
font heading_font  = font_descr{ "Roboto" }.medium(); 
```

**Comment by Xeverous** [comment]
This will need documentation. Especially when some fonts supply multiple font files and I'm not sure how to load them all.

**Comment by djowel** [comment]
> This will need documentation. Especially when some fonts supply multiple font files and I'm not sure how to load them all.

Absolutely. Anyway, you just put them in the application's "resources" directory. The fonts map class will take care of the rest, including loading and searching for the best candidate from the available fonts both from the system and the application's resources.

**Comment by Xeverous** [comment]
Is the path hardcoded? I noticed there are some JSON files and others in each example, are they requird for any elements application?

**Comment by djowel** [comment]
> Is the path hardcoded? I noticed there are some JSON files and others in each example, are they requird for any elements application?

It is currently, but it does not have to be. In OSX, it is standard to have a Resource directory in the app bundle. The JSON files are needed in Linux (I'll have to check Windows) for the application state.

**Comment by djowel** [comment]
The text_revisit branch is now merged to develop. 'underline' is not yet implemented as it is not really part of the 'font' api, and could be implemented as a decorator/proxy. Feel free to add an issue if you think it is important.

**Comment by Xeverous** [comment]
I checked the branch and everything builds correctly, only this is weird to me:

https://github.com/cycfi/elements/blob/aa9ec926a4bb55a1104b38e9b163053866643f69/examples/typography/main.cpp#L11-L21

What is the reason for these includes in the example?

**Comment by djowel** [comment]
> What is the reason for these includes in the example?

Oh good you spotted that. Those are bogus and not needed! Thanks!

**Comment by djowel** [comment]
Fixed

**Comment by djowel** [comment]
Latest update:https://github.com/cycfi/elements/commit/b227723729b5d2c6bb0995b05f15394dbe540357

Now applied to labels.
