### ISSUE TITLE
Examples are not built as Asio.hpp is missing

### ISSUE THREAD

**Issue by sparkylein** [cycfi/elements#400]
I've followed the instructions for a macOS install and installed all dependency with brew.
Some examples need asio.hpp to build but it's not found.
Installed asio with brew as I thought this is the one missing, but Xcode still doesn't find it.

Any help is appreciated.
Thanks.

**Comment by djowel** [comment]
Could you post the errors?

**Comment by djowel** [comment]
My main development system is the Mac. I seldom use XCode now though. My main IDE is CLIon. That said, I just tried XCode and everything builds just fine (built from scratch starting with git clone.

<img width="595" alt="image" src="https://github.com/cycfi/elements/assets/568094/e8ff86ca-7fa3-4008-b456-1718e71435c0">

**Comment by sparkylein** [comment]
Did not, I missed that.
Will do and report back.
Thanks

**Comment by djowel** [comment]
> Did not, I missed that. Will do and report back. Thanks

I'll close this now. That's the problem you are experiencing. I also pushed a commit that uses FetchContent, making --recurse-submodules no longer necessary. Cheers!
