### ISSUE TITLE
Non-resizable window appears with white borders when they are created and moved

### ISSUE THREAD

**Issue by zhkkjun** [cycfi/elements#428]
i created a window whith these code:
`window _win(_app.name(), window::standard &~ window::resizable);`
and then the window appears with white borders when they are created and **moved**.

![elements-bug](https://github.com/user-attachments/assets/3191e31a-fbe2-45a2-98e0-ca07090a36ef)
![Snipaste_2024-10-26_22-13-35](https://github.com/user-attachments/assets/91e5c801-0b4f-4c8f-bc4b-9e0bf889989e)

I found that the reason is because elements doesn't notify the system when the border style of the window's frame is changed.
It can be fixed like this:

elements\lib\host\windows\window.cpp
before
```
      void disable_minimize(HWND hwnd)
      {
         SetWindowLongW(hwnd, GWL_STYLE,
         GetWindowLongW(hwnd, GWL_STYLE) & ~WS_MINIMIZEBOX);
      }

      void disable_maximize(HWND hwnd)
      {
         SetWindowLongW(hwnd, GWL_STYLE,
         GetWindowLongW(hwnd, GWL_STYLE) & ~WS_MAXIMIZEBOX);
      }

      void disable_resize(HWND hwnd)
      {
         SetWindowLongW(hwnd, GWL_STYLE,
            GetWindowLongW(hwnd, GWL_STYLE) & ~WS_SIZEBOX);
         disable_maximize(hwnd);
      }
```
after
```
      void disable_minimize(HWND hwnd)
      {
         SetWindowLongW(hwnd, GWL_STYLE, 
            GetWindowLongW(hwnd, GWL_STYLE) & ~WS_MINIMIZEBOX);
         SetWindowPos(hwnd, nullptr, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOZORDER | SWP_FRAMECHANGED);
      }

      void disable_maximize(HWND hwnd)
      {
         SetWindowLongW(hwnd, GWL_STYLE, 
            GetWindowLongW(hwnd, GWL_STYLE) & ~WS_MAXIMIZEBOX);
         SetWindowPos(hwnd, nullptr, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOZORDER | SWP_FRAMECHANGED);
      }

      void disable_resize(HWND hwnd)
      {
         SetWindowLongW(hwnd, GWL_STYLE, 
            GetWindowLongW(hwnd, GWL_STYLE) & ~WS_SIZEBOX & ~WS_MAXIMIZEBOX);
         SetWindowPos(hwnd, nullptr, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOZORDER | SWP_FRAMECHANGED);
      }
```

**Comment by djowel** [comment]
Can you make an MVCE test for this and do PR of your fix? Does it happen on Windows only?

Many thanks in advance!

**Comment by zhkkjun** [comment]
windows only, but I found that 'window::standard & ~window::resizable' does not work in Linux Mint Xfce.
![image](https://github.com/user-attachments/assets/f85ce13a-8bf9-47e6-90ac-9fd0b0d4e308)


> Can you make an MVCE test for this and do PR of your fix? Does it happen on Windows only?
> 
> Many thanks in advance!
