### ISSUE TITLE
element interface description

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#47]
There are multiple virtual functions in the base type that are unclear. I think we should add at least an explanatory comment how derived types should implement these functions.

https://github.com/cycfi/elements/blob/02c1ab01cbcd887c640e3bf130e28618339aa58c/lib/include/elements/element/element.hpp#L43-L72

The `context` and `basic_context` could also get some documentation.

**Comment by djowel** [comment]
Hold on a little bit. These are fundamental questions that needs to be answered properly. I'm thinking about the best way to document these. I think a wiki is best to capture these.

**Comment by Xeverous** [comment]
I would vote for wiki or just having a markdown files in the repository. With the second option, you can also git the docs.

**Comment by djowel** [comment]
> I would vote for wiki or just having a markdown files in the repository. With the second option, you can also git the docs.

I'm starting a wiki here: https://github.com/cycfi/elements/wiki/The-element-interface
