### ISSUE TITLE
replace_string

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#53]
I don't get the purpose of this thing:

https://github.com/cycfi/elements/blob/4dc738b1fbfa9484eb30ec0e03660ecbdef5b06e/lib/include/elements/element/text.hpp#L33-L39

- `std::basic_string<CharT, Traits, Allocator>` supports `operator=` for respectove string views. `dest = text` just works.
- This function uses copy-and-swap idiom where a copy is not actually used. It performs an unnecessary allocation and does not reuse the existing buffer.

**Comment by djowel** [comment]
Indeed! It is unecessary. I'm not sure how it got to be that way. Go fix it if you will.

**Comment by djowel** [comment]
OK, fixed in develop.
