### ISSUE TITLE
box and background_fill elements are the same

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#58]
https://github.com/cycfi/elements/blob/9cd3e77b70223f1def8400c2de4cf6044535eb0e/lib/include/elements/element/misc.hpp#L21-L40

https://github.com/cycfi/elements/blob/9cd3e77b70223f1def8400c2de4cf6044535eb0e/lib/include/elements/element/misc.hpp#L76-L84

https://github.com/cycfi/elements/blob/9cd3e77b70223f1def8400c2de4cf6044535eb0e/lib/src/element/misc.cpp#L10-L15

Something was either forgotten in one of these or they are accidental code duplication ... in 1 file.

**Comment by djowel** [comment]
Fixed in develop
