### ISSUE TITLE
clamp compile error

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#60]
7288d292 broke the build

```
lib/src/element/dial.cpp: In member function 'virtual double cycfi::elements::dial_base::value_from_point(const cycfi::elements::context&, cycfi::elements::point)':
lib/src/element/dial.cpp:54:36: error: void value not ignored as it ought to be
          return clamp(val, 0.0, 1.0);
                                    ^
```

The `clamp` from infra does not return a value (it has an output parameter). That's why I prefer `std::clamp` - it's standard and return value is cleaner than out parameter.

**Comment by Xeverous** [comment]
`std::clamp` also has a different order of arguments.

**Comment by djowel** [comment]
> The `clamp` from infra does not return a value (it has an output parameter). That's why I prefer `std::clamp` - it's standard and return value is cleaner than out parameter.

Update infra. The reason why I want my own is that of consistency. clamp_min and clamp_max which are not in std. The functional nature of std is also atypical of usage. Typically, you want it to just clamp the reference parameter. I don't like the standard version.

**Comment by djowel** [comment]
I don't like the standard version. It tries to be functional, but by nature clamp is procedural. You just clip a value. And the typical use-case in elements is just that. Feel free to convince me otherwise.

**Comment by djowel** [comment]
> `std::clamp` also has a different order of arguments.

All the more not to use it. I use infra::clamp not only in elements. Using a different clamp will cause confusion.

**Comment by Xeverous** [comment]
> The functional nature of std is also atypical of usage

I disagree. I find return value much cleaner than the output parameter. You can even add `[[nodiscard]]` which will trigger a warning when the return value is ignored.

Standard library does not have them because `clamp_min(val, min)` is `std::max(val, min)` and `clamp_max(val, max)` is `std::min(val, mix)`.

**Comment by djowel** [comment]
Search the library for clamp, clamp_min and clamp_max. This is how we use it. Using std::clamp will not be consistent. Take this code for example:

```c++
         clamp_min(limits.min.x, el.min.x);
         clamp_min(limits.min.y, el.min.y);
         clamp_max(limits.max.x, el.max.x);
         clamp_max(limits.max.y, el.max.y);
```

**Comment by djowel** [comment]
> Standard library does not have them because `clamp_min(val, min)` is `std::max(val, min)` and `clamp_max(val, max)` is `std::min(val, mix)`.

Sure, but that is not clamp. That is min. std::clamp should be named min_max, for consistency. IMO it is wrong.

**Comment by Xeverous** [comment]
Ok, I updated infra and now it builds. I still disagree on the clamp vs max but its your project after all.
