### ISSUE TITLE
Suggest hiding elements::app underneath the public api.

### ISSUE THREAD

**Issue by duzy** [cycfi/elements#7]
The very first example is https://github.com/cycfi/elements/blob/e50c5e70f92519a8e0b20a7b84c3e317d8a80ff3/examples/empty/main.cpp#L11 .

It's quite generic for almost all kinds of GUI applications that having a similar GUI specific `app` being created from client code. And of cause, app writers will have to do a similar `app.run()` invocation to bring up the GUI message loop or similar stuffs.

But while reviewing `elements`, I found that it's quite good for super lightweight applications to offer some kind of viewable elements on screen for users. Well, here the **application** has wider definitions than just a GUI application. Meaning that real applications should have their own initialization process and some kind of message loops or even none of such things. These applications may just looking to show some window/view to users, get data quickly from users, and then get back into its own processing flow. Apps don't care about such a GUI `app` instance at all. Not even decoupling the main process with GUI subsystem.

So following this principle, I demonstrated a different example:
```c++
#include <elements.hpp>

void initialize_process()
{
  // Just initialise 
}

void finish_all_jobs()
{
  // Just finish the main processing flow, nothing related to the gui
  // subsystem!
}

// This should be safe to invoke from any thread!
void show_user_important_notice()
{
  namespace elements = cycfi::elements;
  using namespace cycfi::elements; // for share, box, rgba, etc. 

  // Apps just create a window to show some view any time.
  elements::window win("Important Notice");
  win.on_close = []{ /* report to the main processor */ };

  elements::view view(win);
  view.content({ share(box(rgba(35, 35, 37, 255))) });

  // Show up on screen.
  win.show();

# if false
  // Explicitly request to wait for closing the window.
  // It blocks the flow at the point.
  win.wait_for_close();
# endif
}

int main(int argc, const char* argv[])
{
  initialize_process();

  // This is to call GUI to do the job, but no any interruptions to the
  // major processing flow.
  show_user_important_notice(); // It shouldn't block here!

  // This could be the app's processing loop having nothing to do with
  // the GUI subsystem.
  finish_all_jobs();

  // It should be OPTIONAL to wait for quit signal. The GUI subsystem
  // should be highly isolated from the main process, it should be safe
  // to just quit without waiting (say if the main process flow has
  // longer lifetime than the GUI subsystem).
# if OPTIONAL_WAIT_FOR_GUI
  return elements::wait_quit_signal();
# else
  return 0; // Just return without waiting GUI.
# endif
}
```

Which should explain more.

Such a fast responsive super GUI system should suite more app development. Including non-gui-heavy apps or a daemon in the background to present something to users. Even a command line program can easily present a decent graphics on screen without coupling too much with the GUI system.

A GUI specific `app` instance is leading developers to easily messing up app processing and GUI processing.

So I suggest that `elements` as a latest implemented new GUI option, it should have special design on the point. **It could be fully decoupled views and app logics since the beginning.** (MVC?)

**Comment by djowel** [comment]
I like the idea! I think it is doable. Actually, the app is a very thin wrapper over the event loop. In plugins, for example, you do not need it at all! It might be possible to distribute the event loop mechanism, maybe allowing some non-blocking polling operations to give the client more control on how he/she wants to structure the program. 

Let's keep this open. Or perhaps you want to work on it? If so, I'd be happy to review a PR.

**Comment by duzy** [comment]
I'd love to try changing it when my current work is done and move around using `elements` for the projects. And of cause sending a PR when something is made.

**Comment by djowel** [comment]
> I'd love to try changing it when my current work is done and move around using `elements` for the projects. And of cause sending a PR when something is made.

Keep me updated. What's most important to me is the design and API.

**Comment by Xeverous** [comment]
> Actually, the app is a very thin wrapper over the event loop. In plugins, for example, you do not need it at all! It might be possible to distribute the event loop mechanism, maybe allowing some non-blocking polling operations to give the client more control on how he/she wants to structure the program.

Right now, there is no direct control over event loop, am I right? I really liked the approach of SFML as in this example ([from here](https://www.sfml-dev.org/documentation/)):

```c++
    while (window.isOpen())
    {
        // Process events
        sf::Event event;
        while (window.pollEvent(event))
        {
            // Close window: exit
            if (event.type == sf::Event::Closed)
                window.close();
        }
        // Clear screen
        window.clear();
        // Draw the sprite
        window.draw(sprite);
        // Draw the string
        window.draw(text);
        // Update the window
        window.display();
    }
```

...but I have no idea how such control opportunity for the user deals with callbacks like `win.on_close = []() ...` - would this not be an issue (I have no experience with MVC stuff and have no knowledge on performance and lifetime issues there)? I like both approaches, but the "your own event loop + event passing" feels more like a library, not a framework.

**Comment by djowel** [comment]
That is what I mean by "polling". I only implement what I need, and I don't (currently) have a need for it now, but I can see how it can be useful (actually I have no need for the "app" and "window" at all, I only need the "view" which can be decoupled and used as is). So if anyone's up to it, go for it... Otherwise, I'll get back to it when I have time, or when I need it badly.
