### ISSUE TITLE
Build Failure on Fedora

### ISSUE THREAD

**Issue by williamkibira** [cycfi/elements#74]
Hello , let me start by saying awesome library , really dying to try it out but , i have got this issue running on Fedora 31 .
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: filesystem system date_time regex) (found
  suitable version "1.69.0", minimum required is "1.68")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  lib/CMakeLists.txt:240 (find_package)

```

Also any chance there will be a possible port to FreeBSD ?

**Comment by djowel** [comment]
Did you follow the Setup and Installation guide?  http://cycfi.github.io/elements/setup

I know little about FreeBSD. So unless someone champions the port, I doubt I'll have the bandwidth to do it.

**Comment by djowel** [comment]
> Could NOT find Boost (missing: filesystem system date_time regex) (found
>   suitable version "1.69.0", minimum required is "1.68")

That's an odd error message :-/

**Comment by Xeverous** [comment]
Elements requires some boost libraries which are not header only.

- `regex` - actually could be dropped, it is not used, #70
- `date_time` - would be needed to check but majority is header-only
- `system` - [since 1.69](https://www.boost.org/doc/libs/1_72_0/libs/system/doc/html/system.html) it's header-only
- `filesystem` - this is required

**Comment by djowel** [comment]
> * `regex` - actually could be dropped, it is not used, #70

Not sure about that. Have you actually tried VS yet?

**Comment by djowel** [comment]
> * `date_time` - would be needed to check but majority is header-only

I think this one is pulling regex in its parsers that gets pulled to non-headers. Just a quick note/guess based on my quick experience with building on VS. Then `date_time` is being pulled by... perhaps asio. Again, I don't have the time (yet) to investigate, so for now, let's just leave these dependencies as-is.

**Comment by williamkibira** [comment]
I have the requirements for Linux and i have all boost dependencies
installed on Fedora 31 .

**Comment by djowel** [comment]
> I have the requirements for Linux and i have all boost dependencies installed on Fedora 31 .

How was it installed? I get that cmake error when I have boost and the libraries were not built or perhaps with incompatible builds. Check if it's getting to the paths to, e.g. libboost_filesystem.a

**Comment by Xeverous** [comment]
> Not sure about that. Have you actually tried VS yet?

No, not a priority for me now. Potentially unneeded boost libs are one of the smallest of my problems now. Want to focus on the tab/notebook widget implementation.

**Comment by djowel** [comment]
This should no longer be an issue since we removed Boost dependence. I'm closing this now. Feel free to reopen if this is still an issue.
