### ISSUE TITLE
build with MinGW and GTK ?

### ISSUE THREAD

**Issue by yslking** [cycfi/elements#75]
I noticed it is really easy to build elements with MinGW and GTK. I simply made everything behave as Linux except for the boost::asio and it works fine. Are there any plans to officially support building for MinGW and GTK?

**Comment by djowel** [comment]
> I noticed it is really easy to build elements with MinGW and GTK. I simply made everything behave as Linux except for the boost::asio and it works fine. Are there any plans to officially support building for MinGW and GTK?

That's good! Sure we can do that. Are you willing to do a PR on the Setup and Installation instructions here: http://cycfi.github.io/elements/setup ?

**Comment by Xeverous** [comment]
What are the potetial benefits/drawbacks of such build configuraton? Does GTK on Windows bring some extra functionality over current plain WinAPI implementation?

**Comment by yslking** [comment]
> What are the potential benefits/drawbacks of such a build configuration? Does GTK on Windows brings some extra functionality over current plain WinAPI implementation?
@Xeverous 
It will not replace plain WinAPI implementation. I hope to add an option rather than replace anything. And adding support for GTK on Windows will not bring extra complications for the project.
 
benefits:
(Compared to MSVC) Many people (I guess) and I are not familiar with msvc's error message.
(Compared to MFC GCC as you said) GCC with WinAPI is not well implemented, as you posted in issue #9, but GTK for Windows supports new features like GetWindowDpi well. And GTK might support windows 7 for you.

(pseudo-)benefit:
It is just a normal choice to support it, as many other opensource cross-platform softwares(e.g. GIMP, inkscape and Anjuta) do.

drawbacks:
It may be slower in runtime and compile time.
 The multiple reference issue of GCC (I remembered it was put forward by you, but I am not able to find it now. I am sorry.)

**Comment by yslking** [comment]
> That's good! Sure we can do that. Are you willing to do a PR on the Setup and Installation instructions here: http://cycfi.github.io/elements/setup ?

Sure. I am glad to do it several days later.

**Comment by Xeverous** [comment]
> The multiple reference issue of GCC (I remembered it was put forward by you, but I am not able to find it now. I am sorry.)

Did you mean #69? This is unrelated to GTK, it's a MinGW LTO bug.

**Comment by yslking** [comment]
thanks, it is #69. I knew it is unrelated to GTK. I mentioned it  because I thought P(use MinGW | use GTK) > P(use MinGW | use win32 api).

I am a green hand. Please let me know if it is not encouraged to mention information that is not necessarily related (e.g. lto here). Thanks a lot.
________________________________

**Comment by djowel** [comment]
If you can prepare the build instructions, we can give it a try. I am all for adding this gtk/mingw and the msvc/mingw builds. It also makes sense to mention the limitations (if any). HiDPI support comes to mind. I wonder how well GTK on windows supports scaling and HiDPI.

**Comment by yslking** [comment]
thanks.
> If you can prepare the build instructions, we can give it a try.
What I did:
- Search for `__linux__` occurrences, and properly add `__MINGW32__` macro. Change the order of `elseif` if necessary.
- Search for `!defined(_WIN)` occurrences, and properly add `__MINGW32__` macro. 
- Search for `Unix` in CMake files occurrences, and add `MINGW` if necessary
[This](https://gist.github.com/yslking/651a4b0173d959b7843a9752da81fe9c) is the git diff result (performed on the master branch). In fact, only a few lines are changed.
I tried to build modified codes in MinGW(msys2) + GTK, msvc, Linux and succeeded. But when compiles with GCC + Win32 APIs, `MINGW` and `__MINGW32__` will also be defined. To live with GCC + Win32 APIs, I think an extra CMake variable/option, and an extra preprocessor's macro should be added, according to some user input (maybe in the form of a CMake cached variable), to determine whether a user wants to build with MinGW + GTK or with GCC + Win32 APIs.

> HiDPI support comes to mind. I wonder how well GTK on windows supports scaling and HiDPI.

I do not know the internal implementation of GTK, but it turned out that everything works fine. I purposely hot switch windows' scale factor, and move GTK apps to another screen with a different scale factor, and it responded correctly like any other modern Windows10 Apps. Its texts and images are clear. It works even better than on Gnome(X11) since Gnome(X11) itself does not support fractional scale factor.

**Comment by djowel** [comment]
> > If you can prepare the build instructions, we can give it a try.
> > What I did:
> 
[snip]

Could you do a PR instead? Also could you add some tips on how to get the dev environment going (e.g. no external libs, just MinGW with GTK?) I must confess, I haven't tried GTK on Windows.

> > HiDPI support comes to mind. I wonder how well GTK on windows supports scaling and HiDPI.
> 
> I do not know the internal implementation of GTK, but it turned out that everything works fine. I purposely hot switch windows' scale factor, and move GTK apps to another screen with a different scale factor, and it responded correctly like any other modern Windows10 Apps. Its texts and images are clear. It works even better than on Gnome(X11) since Gnome(X11) itself does not support fractional scale factor.

That is wonderful! The MFC/MinGW build on the other hand does not support HiDPI scaling, which is a bummer. At least now, there's another viable non-MSVC build.

**Comment by djowel** [comment]
> (maybe the convention is to create a new branch from the `develop` branch? ).

If I am not mistaken, I think develop and master are in sync now, so It's fine either way. I'd love to see a PR.

**Comment by djowel** [comment]
> To live with GCC + Win32 APIs, I think an extra CMake variable/option, and an extra preprocessor's macro should be added, according to some user input (maybe in the form of a CMake cached variable), to determine whether a user wants to build with MinGW + GTK or with GCC + Win32 APIs.

Makes sense. Love to see that happening! That is important and should be documented in the build/setup instructions.

**Comment by yslking** [comment]
see #76, please.

**Comment by Xeverous** [comment]
> The MFC/MinGW build on the other hand does not support HiDPI scaling, which is a bummer.

This is not a MinGW issue, in fact MCF distro is bundled with the newest headers and runtime possible. I tried other MinGW distrubutions and they support even less, requiring even more changes to build elements.
