### ISSUE TITLE
Link-time optimization supported.

### ISSUE THREAD

**Issue by wooyunjae** [cycfi/elements#77]
i have problem at "Setup and Installation" ( MacOS Installation )

i installed brew, cairo, boost, fontconfig, cmake.

And i got same issue like this link↓
https://stackoverflow.com/questions/58081084/target-boostlibrary-already-has-an-imported-location-link-errors

so i edit like this
=======================================================================
   ...

"Debug" "Release" "MinSizeRel" "RelWithDebInfo")
endif()

include(CheckIPOSupported)
**set(Boost_USE_MULTITHREADED TRUE) <==========Added**
check_ipo_supported(RESULT IPO_SUPPORTED)
if(IPO_SUPPORTED)
    message(STATUS "Link-time optimization supported. Will be enabled in Release build type")
endif()

 ...
=======================================================================

And i got like this.
I tried to solve it, but I can`t solve it. 
What should i do?

=======================================================================
uyunjaeui-Macmini:build uyunjae$ cmake -GXcode ../
-- Link-time optimization supported. Will be enabled in Release build type
CMake Error at CMakeLists.txt:31 (add_subdirectory):
  add_subdirectory given source "../json" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/Users/uyunjae/Downloads/elements-master/build/CMakeFiles/CMakeOutput.log".

=======================================================================

**Comment by djowel** [comment]
Please follow the setup and installation guide: http://cycfi.github.io/elements/setup

**Comment by wooyunjae** [comment]
> Please follow the setup and installation guide: http://cycfi.github.io/elements/setup
> 
> specifically the Git section:
> 
> Git
> Elements C++ GUI library, plus the Cycfi Infra and JSON libraries:
> 
> git clone https://github.com/cycfi/elements.git
> git clone https://github.com/cycfi/infra.git
> git clone https://github.com/cycfi/json.git

Thank you so much!

**Comment by Xeverous** [comment]
@wooyunjae Is your problem solved? Add a comment or close the issue.

**Comment by djowel** [comment]
Closing this issue now... @wooyunjae,  feel free to reopen if this is still an 'issue'.
