### ISSUE TITLE
List of widgets and planned features?

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#8]
I have read the [article about the library](https://www.cycfi.com/2019/07/photon-micro-gui/) and I'm interested in using it. I know it's still very early (no documentation) but I struggle to find a modern C++ GUI that has non-intrusive build and a large set of widgets.

I think it would be good to have a list of planned/implemented features/widgets. I'm mostly interested in rich text display (bold, italics, color, custom fonts) and simple canvas.

**Comment by djowel** [comment]
Yeah, a "non-intrusive build" is one of the most important requirements that compelled me to write Elements. 

Would you be willing to contribute such a wish-list? Do you need only rich text **display** or do you need rich text **editing**? Display is already possible. There is a also cairo-based (based on Element's canvas) monospace text-editor, although I am debating with myself on whether to use native widgets for such a thing. Same with  rich-text editor.

**Comment by Xeverous** [comment]
> Would you be willing to contribute such a wish-list?

I could, but I really have no skill/knowledge for anything graphics-relared. Also no documentation is a significant barrier to the project. Anything as simple as auto-generated Doxygen would help. I can learn, test and propose a lot though.

> Do you need only rich text display or do you need rich text editing?

Display only. But I need simple canvas capable of drawing text and basic shapes for other tasks.

> There is a also cairo-based (based on Element's canvas) monospace text-editor, although I am debating with myself on whether to use native widgets for such a thing. Same with rich-text editor.

I have no idea about the difference between native and non-native widgets.

**Comment by djowel** [comment]
> > Do you need only rich text display or do you need rich text editing?
> 
> Display only. But I need simple canvas capable of drawing text and basic shapes for other tasks.

Well then it's already there (both the simple canvas and the rich text display). I'd start by looking at the examples and trying to run them.

I'm hesitating to start documentation because the API is still changing. I can probably start documentation for some of the stable components.

**Comment by Xeverous** [comment]
> I'm hesitating to start documentation because the API is still changing. I can probably start documentation for some of the stable components.

Anything making easier to work with the library or for an eventual contribution could help. I can beta-test this in my project(s) but not sure if you like to have a lot of question-like issues.

**Comment by Xeverous** [comment]
What do you think about such list? https://github.com/qPCR4vir/nana-docs/wiki/Widgets

I find it very useful because any library user can quickly identify how each widget looks and how it is named.

**Comment by djowel** [comment]
> What do you think about such list? https://github.com/qPCR4vir/nana-docs/wiki/Widgets
> 
> I find it very useful because any library user can quickly identify how each widget looks and how it is named.

We already have most of those, some with similar names. The main difference with most other gui toolkits is that with elements, these are composed of smaller, more modular units (elements). A lot of these are composed in the "gallery", a compilation of pre-defined composites that the user can use as-is or modified to suit. Take a look at the menu, for example, to have an idea what I am talking about.

**Comment by djowel** [comment]
I think a good way to compartmentalize the library is by the examples. The examples provide a great overview over the current 'feature list' of the library.

**Comment by Xeverous** [comment]
Definitely agree. Your library already has a lot of them but I have to admit that for many libraries examples are a very good way to showcase what and how can be done with the library. For some very unique libraries (eg Spirit) it would be very hard to understand how they should be used without example programs.

I still haven't really checked the contents all examples (was more concerned about correct build), might aswell close this issue if after inspecting them I have no more questions.
