### ISSUE TITLE
Windows size on Linux (Wayland)

### ISSUE THREAD

**Issue by dmacvicar** [cycfi/elements#84]
I assume this is not normal:

![Screenshot from 2020-04-07 00-53-52](https://user-images.githubusercontent.com/15332/78612850-9df27300-786a-11ea-8461-a1ce3d981208.png)

The window can't be resized.

Opened for tracking. I will look into it  in the next days if time permits.

*Update* Only happens with Wayland backend. `GDK_BACKEND=x11 ./BasicSlidersAndKnobs` works as expected.

**Comment by djowel** [comment]
Oh hrmm... Not normal at all ;-/ But I did check Linux yesterday. I'll check again just to be sure.

**Comment by djowel** [comment]
I tried Ubuntu. I'm getting correct results:

![Screenshot from 2020-04-07 08-20-39](https://user-images.githubusercontent.com/568094/78617211-4aebe080-78a9-11ea-9144-c2bdb73e18b6.png)

**Comment by dmacvicar** [comment]
That is the screenshot I get with

```
GDK_BACKEND=x11 ./BasicSlidersAndKnobs
```

So I would guess this is happening with the Wayland backend.

**Comment by djowel** [comment]
If you can give me exact steps on how to repro this on Ubuntu, I'll see what I can do. I'm a MacOS guy and I know just enough of Linux as needed and I have not gone into the Wayland land yet.

**Comment by djowel** [comment]
OK, I also noticed that I can't resize windows on stock Ubuntu. It seems I have some debugging to do...

**Comment by djowel** [comment]
Alright, I pushed a hotfix to develop. I'll need to merge this hotfix to master as well. Please confirm.

**Comment by djowel** [comment]
> Alright, I pushed a hotfix to develop. I'll need to merge this hotfix to master as well. Please confirm.

Cherry-picked hotfix to master.

**Comment by dmacvicar** [comment]
![Screenshot from 2020-04-07 00-53-52](https://user-images.githubusercontent.com/15332/78813624-97c8d780-79cd-11ea-9dd9-e6980089456e.png)

It is better, but still there is a part covered when the window appears. With lastest develop HEAD I can at least resize, which will uncover the hidden parts, until it starts to recalculate the llayout.

**Comment by djowel** [comment]
> It is better, but still there is a part covered when the window appears. With lastest develop HEAD I can at least resize, which will uncover the hidden parts, until it starts to recalculate the llayout.

This might be a HiDPI issue. Tell me the steps how to repro this.

**Comment by dmacvicar** [comment]
I am using openSUSE Tumbleweed from 26.03.2020, Gtk 3.24, Wayland on an old Thinkpad X230, 1366x768.

So I am not doing anything else than running the example.

Let me get familiar with HiDPI and see if I can debug further.

**Comment by djowel** [comment]
> I am using openSUSE Tumbleweed from 26.03.2020, Gtk 3.24, Wayland on an old Thinkpad X230, 1366x768.

Oh, I suppose 1366x768 should scale to 1.0. Are the other examples exhibiting the same behavior?

**Comment by dmacvicar** [comment]
Dialogs and Sprite Knobs seem to be fine:

![Screenshot from 2020-04-10 12-04-57](https://user-images.githubusercontent.com/15332/78983010-a0cbbd00-7b23-11ea-83bc-05356ca81f1c.png)

![Screenshot from 2020-04-10 12-04-32](https://user-images.githubusercontent.com/15332/78983016-a6290780-7b23-11ea-8c49-ca26070227d3.png)

While Text and Buttons are not

![Screenshot from 2020-04-10 12-03-47](https://user-images.githubusercontent.com/15332/78983020-a9bc8e80-7b23-11ea-93a6-1699b08c246f.png)

![Screenshot from 2020-04-10 12-03-22](https://user-images.githubusercontent.com/15332/78983031-acb77f00-7b23-11ea-8ec8-a8c61ea364ee.png)

**Comment by djowel** [comment]
I tried Wayland on Ubuntu 19.04. Everything seems to draw just fine here. I am testing on a MacbookPro which is HiDPI. Thinking about it, my hunch is that there may be some quirks with standard DPI? I am not sure. I can probably switch to 1:1 scale and try again.

That said, there are some quirks with Wayland when resizing windows in my machine where there's a temporary black box surrounding the whole window and it flickers. It's not just for Elements. Other windows exhibit that behavior too. Also, in CLion (my preferred IDE), the text is very blurry and unusable. These quirks are probably the reasons why Ubuntu chose to not make it default after 17.10.

Oh, and I just read: https://wiki.ubuntu.com/Wayland

Will toolkits (Qt, GTK+, etc.) need to be ported to work on Wayland?
Yes. This is an area of heavy development currently. The toolkits must be ported as one of the pre-requisites to getting existing applications running on Wayland. Much progress has been made on Qt, GTK+, Clutter, SDL, and EFL.

So I did not recompile. I'll try recompiling and see what happens.

**Comment by djowel** [comment]
OK, I tried a clean rebuild. Same. I get the correct sizes and windows. I did notice one thing though: the text is blurred, like in CLion. I am not sure if it is because of the rebuild. Perhaps I was not paying attention on the text in my first try. But now I know why, Wayland is giving Elements a scale of 1:1 and stretching the contents to fit, thus making it blurry. I'm guessing it involves more than rebuilding. I suppose that's the minimum, but there are other API calls that need to be done, esp. for HiDPI. If you'd like to look into it, the linux/host directory has all the linux specific code, esp. windows.cpp and base_view.cpp. I'll see if I can do some more background research.

**Comment by djowel** [comment]
Oh!!! https://developer.gnome.org/gtk3/stable/gtk-wayland.html

The GDK Wayland backend provides support for running GTK+ applications under the Wayland display server. To run your application in this way, select the Wayland backend by setting GDK_BACKEND=wayland.

See if it works for you. Hah! I'll go give it a try later. 

Caveat: https://wiki.gnome.org/Initiatives/Wayland/GTK%2B "GTK+ already has a functional Wayland backend, but several pieces of functionality need to be completed before it is ready for prime time."

**Comment by djowel** [comment]
Gak! It's more nutty than I expected: https://github.com/swaywm/sway/wiki/Running-programs-natively-under-Wayland "Do not set GDK_BACKEND, it will break apps" So confusing...

**Comment by djowel** [comment]
Some links here on how Libre Office was ported to Wayland: https://www.phoronix.com/scan.php?page=search&q=McNamara

Elements using GTK3 is a good step to begin with. But there's probably more work to do. I haven't done any reading yet, just cursory going through links.

**Comment by dmacvicar** [comment]
Most toolkits are already ported to Wayland. Gtk, Qt, etc are all using the Wayland backend in Wayland enabled distros. In https://github.com/cycfi/elements/issues/84#issuecomment-610641579 I tried to point out that if I forced the X11 driver, the size was right. When I force the X11 driver, it basically connects to XWayland, which is a X11 server running inside of Wayland, and acts as a compatibility layer for all apps not ported, which are basically the ones using xlibs and everything non-Qt, non-Gtk and non-GL.

**Comment by dmacvicar** [comment]
Don't worry about this. I will dive into the code as I find time to do it. Need to reads docs about scaling first. It could be even some openSUSE specific bug.

**Comment by djowel** [comment]
> Don't worry about this. I will dive into the code as I find time to do it. Need to reads docs about scaling first. It could be even some openSUSE specific bug.

What bugs me with Wayland is that other apps also exhibit some odd behavior, e.g. with Clion drawing blurry text, with VSCode drawing the flickering black rectangle around the window when you draw-resize the window, which makes me think that it is not yet 'there' yet. The blurry text (actually blurry everything, but text is very obvious), is because the app is given a scale of 1:1 as mentioned, which, since the behavior is not unique to Elements, makes me think that something else needs to be done, beyond a simple rebuild.

**Comment by dmacvicar** [comment]
You may want to make sure those apps are running natively on Wayland.

For example, my system runs Wayland by default, therefore Gtk uses `GDK_BACKEND=wayland` as default.

If I unset the X11 `DISPLAY` variable from ":1" to "" and omit `GDK_BACKEND` or I set it explictly to "wayland". I can still open the elements examples, because Gtk is connecting to Wayland and ignoring the X11 `DISPLAY` variable.
However if I unset the `DISPLAY` variable, and set `GDK_BACKEND` to "x11", I can't open the examples anymore:

```
$ DISPLAY="" GDK_BACKEND=x11 ./BasicSlidersAndKnobs
(BasicSlidersAndKnobs:12123): Gtk-WARNING **: 15:10:39.197: cannot open display:
```

Why? because Gtk is now using the X11 backend, but can't because `DISPLAY` is not set. Letting `DISPLAY` alone but forcing the `x11` backend would make the _elements_ examples connect to Wayland through _XWayland_ (which in my case is the one not presenting those size problems).

With Qt apps, like KeepassXC, I see the opposite on my system. They connect to X11 (therefore `app-> x11 -> XWayland -> Wayland` by default. If I unset `DISPLAY`, then Qt uses the Wayland backend:

```
$ DISPLAY="" keepassxc
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

*The question now is: are Clion and VStudio Code Wayland native?*

If I run Visual Studio Code with `DISPLAY=""` it does not come up (I don't see the error message, as the `code` command seems to start it in the background.

Same with Idea (which I guess is the same runtime as Clion, Java).

```
$ DISPLAY="" bin/idea.sh
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

Startup Error: Unable to detect graphics environment
```

Which means, they are all X11 apps connecting to Wayland via the X11 translation layer. Unlike _elements_, which thanks to Gtk is using Wayland natively when available.

**Comment by djowel** [comment]
Right... It was a good decision to use Gtk3 from the start. It's the smart choice anyway, since Elements requires HiDPI, which Gtk2 did not support (if I recall correctly), and the other options are rather gnarly. I still need to figure out why I am getting a 1:1 scale with stretched size though, on my Mac which should give a higher DPI resolution than 1:1. And then the bug you are getting with clipped windows. My hunch is that these issues are related.

**Comment by djowel** [comment]
BTW, I tried looking into this again. I gave up when in Ubuntu, Wayland mode, I attached an external 4K HDPI monitor and before I even got to run the examples, the OS simply ran awry, sometimes crashing and often times just giving a blank black screen on the second monitor. IMO, Wayland is too flaky to be considered at this point.

**Comment by dmacvicar** [comment]
This bug has not given me problems in the UIs I am doing, so feel free to close it and it can be revisited when i becomes a problem for many people.

Right now I have anyway to focus on the backend of things.
