### ISSUE TITLE
ownership-aware API for strings

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#87]
> You can make multiple constructors:
> 
> * `const char(&)[N]` - this must be a C-string, guuaranteed infinite lifetime
> * `std::string_view` - user manages lifetime
> * `std::string` - widget manages lifetime
> * `const char* = delete` because it is unknown, require the user to wrap the call into `string` or `string_view`.

Exactly! But not on the ctor, instead the factory...

_Originally posted by @djowel in https://github.com/cycfi/elements/issues/23#issuecomment-597919623_

**Comment by djowel** [comment]
The way to tackle this is to think about expressions. To understand what;s happening, study what this expression does:
```c++
label("some text")
```
It is invoking a constructor here: https://github.com/cycfi/elements/blob/master/lib/include/elements/element/misc.hpp#L154

because of this declaration:
https://github.com/cycfi/elements/blob/master/lib/include/elements/element/misc.hpp#L251

tip: study the way the generators (factories) work [e.g. ```label_with_font```, ```label_with_font_size```, etc.] and how certain expressions generate certain objects with just the actual member variables needed; i.e. a ```label_with_font``` has an additional font member. I suggest stepping in with the debugger from this code example:
https://github.com/cycfi/elements/blob/master/examples/text_and_icons/main.cpp#L107

Now, the challenge is how to make the expression ```label("some text")``` call another generator instead of directly invoking the constructor. That generator can then generate the *actual* label object with the exact member needed based on the type of the string passed in.

Feel free to ask more questions.

**Comment by Xeverous** [comment]
API example:

http://coliru.stacked-crooked.com/a/3ddc49ac4d87e406

```cpp
#include <iostream>
#include <iomanip>
#include <string>
#include <string_view>
#include <typeinfo>
#include <utility>

struct element
{
    virtual std::string_view str() const = 0;
    virtual std::size_t size() const = 0;
};

template <typename T>
struct string_proxy : element
{
public:
    using value_type = T;

    string_proxy(T value): value(std::move(value)) {}

    virtual std::string_view str() const override { return value; }
    virtual std::size_t size() const override { return value.size(); }
private:
    T value;
};


string_proxy<std::string> string_impl(std::string str, std::false_type)
{
    return {std::move(str)};
}

string_proxy<std::string_view> string_impl(std::string_view str, std::false_type)
{
    return {str};
}

template <std::size_t N>
string_proxy<std::string_view> string_impl(const char (&str)[N], std::true_type)
{
    return {std::string_view(str, N)};
}

// surprise: overload resolution prefers pointer decay over perfectly deduced template
// this overload is not appropriate, it will catch arrays too
// https://stackoverflow.com/a/32513807/4818802
// https://stackoverflow.com/a/28243509/4818802
// void string(const char*) = delete;

void string_impl(const char*, std::false_type) = delete;

template<typename T>
auto string(T&& x)
{
    return string_impl(std::forward<T>(x), std::is_array<std::remove_reference_t<T>>());
}

template <typename T>
void print_info(const string_proxy<T>& sp)
{
    std::cout << "storing " << std::quoted(sp.str()) << " of type " << typeid(T).name() << "\n";
}

int main()
{
    std::string abc = "abc";
    std::string_view abc_ref = abc;
    char def[] = "def";
    
    print_info(string(abc));                // std::string&
    print_info(string(abc_ref));            // std::string_view&
    print_info(string(def));                // char (&)[4]
    print_info(string(std::string("ghi"))); // std::string&&
    
    std::cout << "\n";
    print_info(string(std::as_const(abc)));          // const std::string&
    print_info(string(std::as_const(abc_ref)));      // const std::string_view&
    print_info(string("def"));                       // const char (&)[4]
    
    // print_info(string(abc.c_str())); // should not compile
    // print_info(string(nullptr));     // should not compile
}
```

**Comment by djowel** [comment]
Looks good to me

**Comment by Xeverous** [comment]
Any thoughts about the name? `string_holder`? `string_proxy`? `string_store`?

**Comment by djowel** [comment]
let's go with `string_proxy` for now. We can change later if we find a better name.

**Comment by Xeverous** [comment]
After multiple thoughts of possible changes:

- If we want to add a template parameter determining storage, the implementation of already existing label factories will need to have an extra layer of templates. The current root non-template class (`default_label`) or the current root storage class template (`basic_label_base<T>`) would need to get an extra template parameter in order to support multiple storages. Then, we would need to rewrite all the code downward inheritance to support it.
- The whole issue is about optimizing out a single allocation (that is, storing `std::string_view` instead of `std::string`). I could bring much more CPU performance improvements simply by reviewing which API functions take `T const&` in their constructors (which is forced to create a copy, regardless of passed value category) and change them to post-modern-sutter recommended `T arg` and `_member(std::move(arg))`.
- If we go for this issue, we must document such ownership-aware API as it is very unintuitive and can not be simply described as any of "we take ownership" or "user retains ownership". What's worse, is that if we go for such API having different labels storing `std::string` or `std::string_view`, the API will either:
  - have a huge difference in their `set_text()` semantics (a user changes `label(str)` to `label("abcxyz")` => suddenly their code crashes because setters now do not take ownership)
  - have or not have such setter function in their API (a user changes `label(str)` to `label("abcxyz")` => suddenly they lose the setter)
- Storing `std::string_view` means we can not use null-terminated string APIs. This is obviously a design flaw of null-terminated strings APIs, but if we have to workaround the issue at least once then the whole "proxy storage optimization" is IMO not worth the increased complexity.
- Multiple functions in the linked file are marked as `virtual`. Shoudn't they be marked with `override`?
- The implementation of `tabbar` and `notebook` is not actually affected by this issue. Widget factories already do not care what they get since they will be function templates anyway.

In the precense of all of these, IMO we should not implement ownership-specific storage for different label instantiations. Instead I would:

- Fix constructors/factories taking `T const&`. They make an (unnecessary) copy, always. Constructors should be taking by value and factories should implement perfect forwarding. This alone will bring more allocation improvements than the whole ownership-aware storage theoretically can.
- Continue to use `std::string` as the storage type for all labels. This opens the non-workaround support for null-terminated string APIs, always-present setters which are lifetime-safe while also not complicating the API in any way.

What do you think?

**Comment by Xeverous** [comment]
One more reason: do not forget that the C++ standard encourages and all major implementations do small buffer optimization. Many `std::string` labels will never allocate.

**Comment by djowel** [comment]
Everything you are saying makes sense. Go for it! 

About the `virtual` vs. `override` , please feel free to fix. It's probably just an oversight.

**Comment by Xeverous** [comment]
See #90

**Comment by Xeverous** [comment]
PR merged, closing.
