### ISSUE TITLE
Remove string duplicates in widget factories

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#88]
There are multiple factories like this one which unnecesarily copy the string:

https://github.com/cycfi/elements/blob/ccb2f2c4107827cb9f9d98e8fb3daf3944e0567f/lib/include/elements/element/gallery/check_box.hpp#L35-L41

Instead of creating a such hierarchy:

- check_box
  - htile
    - layered_element
      - icon_on
      - icon_off
    - text

they create this:

- check_box
  - layered_element
    - htile
      - icon_on
      - text
    - htile
      - icon_off
      - text
___

This issue is blocked by #87

**Comment by Xeverous** [comment]
I see a bigger problem there: many factories are duplicating elements or their data in order to create 2 elements that represent some boolean state. I think this is a good place for another element type that will abstract such state. Types such as `layered_button` and `basic_choice`, for their ctors instead of taking 2 elements could then take such single element. This could offer to not copy the stored element if both states are the same while also having a way to actually have 2 separate elements.

**Comment by Xeverous** [comment]
All such factories:

```
$ grep -rn -C 7 "<false" lib/include/
lib/include/elements/element/gallery/check_box.hpp-31-   {
lib/include/elements/element/gallery/check_box.hpp-32-      draw_check_box(ctx, _text, state, ctx.bounds.includes(ctx.view.cursor_pos()));
lib/include/elements/element/gallery/check_box.hpp-33-   }
lib/include/elements/element/gallery/check_box.hpp-34-
lib/include/elements/element/gallery/check_box.hpp-35-   inline basic_toggle_button<> check_box(std::string text)
lib/include/elements/element/gallery/check_box.hpp-36-   {
lib/include/elements/element/gallery/check_box.hpp-37-      return basic_toggle_button(
lib/include/elements/element/gallery/check_box.hpp:38:         check_box_element<false>{ text }
lib/include/elements/element/gallery/check_box.hpp-39-       , check_box_element<true>{ text }
lib/include/elements/element/gallery/check_box.hpp-40-      );
lib/include/elements/element/gallery/check_box.hpp-41-   }
lib/include/elements/element/gallery/check_box.hpp-42-}}
lib/include/elements/element/gallery/check_box.hpp-43-
lib/include/elements/element/gallery/check_box.hpp-44-#endif
--
lib/include/elements/element/gallery/icon_button.hpp-63-   inline basic_toggle_button<> toggle_icon_button(
lib/include/elements/element/gallery/icon_button.hpp-64-      uint32_t code
lib/include/elements/element/gallery/icon_button.hpp-65-    , float size
lib/include/elements/element/gallery/icon_button.hpp-66-    , color body_color = get_theme().default_button_color
lib/include/elements/element/gallery/icon_button.hpp-67-   )
lib/include/elements/element/gallery/icon_button.hpp-68-   {
lib/include/elements/element/gallery/icon_button.hpp-69-      return {
lib/include/elements/element/gallery/icon_button.hpp:70:         icon_button_element<false>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-71-       , icon_button_element<true>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-72-      };
lib/include/elements/element/gallery/icon_button.hpp-73-   }
lib/include/elements/element/gallery/icon_button.hpp-74-
lib/include/elements/element/gallery/icon_button.hpp-75-   inline basic_toggle_button<> toggle_icon_button(
lib/include/elements/element/gallery/icon_button.hpp-76-      uint32_t code1
lib/include/elements/element/gallery/icon_button.hpp-77-    , uint32_t code2
--
lib/include/elements/element/gallery/icon_button.hpp-88-   inline layered_button icon_button(
lib/include/elements/element/gallery/icon_button.hpp-89-      uint32_t code
lib/include/elements/element/gallery/icon_button.hpp-90-    , float size
lib/include/elements/element/gallery/icon_button.hpp-91-    , color body_color = get_theme().default_button_color
lib/include/elements/element/gallery/icon_button.hpp-92-   )
lib/include/elements/element/gallery/icon_button.hpp-93-   {
lib/include/elements/element/gallery/icon_button.hpp-94-      return {
lib/include/elements/element/gallery/icon_button.hpp:95:         icon_button_element<false>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-96-       , icon_button_element<true>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-97-      };
lib/include/elements/element/gallery/icon_button.hpp-98-   }
lib/include/elements/element/gallery/icon_button.hpp-99-}}
lib/include/elements/element/gallery/icon_button.hpp-100-
lib/include/elements/element/gallery/icon_button.hpp-101-#endif
--
lib/include/elements/element/gallery/radio_button.hpp-31-   {
lib/include/elements/element/gallery/radio_button.hpp-32-      draw_radio_button(ctx, _text, state, ctx.bounds.includes(ctx.view.cursor_pos()));
lib/include/elements/element/gallery/radio_button.hpp-33-   }
lib/include/elements/element/gallery/radio_button.hpp-34-
lib/include/elements/element/gallery/radio_button.hpp-35-   inline basic_choice radio_button(std::string text)
lib/include/elements/element/gallery/radio_button.hpp-36-   {
lib/include/elements/element/gallery/radio_button.hpp-37-      return basic_choice(
lib/include/elements/element/gallery/radio_button.hpp:38:         radio_button_element<false>{ text }
lib/include/elements/element/gallery/radio_button.hpp-39-       , radio_button_element<true>{ text }
lib/include/elements/element/gallery/radio_button.hpp-40-      );
lib/include/elements/element/gallery/radio_button.hpp-41-   }
lib/include/elements/element/gallery/radio_button.hpp-42-}}
lib/include/elements/element/gallery/radio_button.hpp-43-
lib/include/elements/element/gallery/radio_button.hpp-44-#endif
--
lib/include/elements/element/gallery/tab.hpp-47-      return true;
lib/include/elements/element/gallery/tab.hpp-48-   }
lib/include/elements/element/gallery/tab.hpp-49-
lib/include/elements/element/gallery/tab.hpp-50-   template <typename W1, typename W2>
lib/include/elements/element/gallery/tab.hpp-51-   inline basic_choice tab(W1&& off, W2&& on)
lib/include/elements/element/gallery/tab.hpp-52-   {
lib/include/elements/element/gallery/tab.hpp-53-      return basic_choice(
lib/include/elements/element/gallery/tab.hpp:54:         tab_element<false, remove_cvref_t<W1>>{ std::forward<W1>(off) }
lib/include/elements/element/gallery/tab.hpp-55-       , tab_element<true, remove_cvref_t<W2>>{ std::forward<W2>(on) }
lib/include/elements/element/gallery/tab.hpp-56-      );
lib/include/elements/element/gallery/tab.hpp-57-   }
lib/include/elements/element/gallery/tab.hpp-58-}}
lib/include/elements/element/gallery/tab.hpp-59-
lib/include/elements/element/gallery/tab.hpp-60-#endif
```
```
lib/include/elements/element/button.hpp-86-   template <typename W1, typename W2>
lib/include/elements/element/button.hpp:87:   inline layered_button::layered_button(W1&& off, W2&& on)
lib/include/elements/element/button.hpp-88-    : _state(false)
lib/include/elements/element/button.hpp-89-   {
lib/include/elements/element/button.hpp:90:      (*this)[0] = share(std::forward<W1>(off));
lib/include/elements/element/button.hpp-91-      (*this)[1] = share(std::forward<W2>(on));
lib/include/elements/element/button.hpp-92-   }
```

I see 2 separate things here:

- an element which represents a boolean state and renders differently depending on the state
- an element which holds 2 elements

IMO these 2 should be separated. My vision:

- It should be possible to implement a single type that renders differently depending on the result of `bool state() const` (without having to construct 2 elements).
- A possible implementation that gives maximum customization possibilities is an array-composite-derived type that holds 2 elements.
- The library can offer a default implementation that holds only 1 element. A great example is the tab element, which will usually only change its background color.

The concept could then be possibly extended and/or multiplied by having multiple interfaces: `selectable`, `highlightable`, `hideable` etc. Currently I see a significant inconsistency how the library treats this problem:

- A) some elements implement runtime drawing and check the state inside `draw()`
- B) some elements hold 2 child elements and use drawing method on one of its childs

I think that A should be the default and B should be offered as a possible implementation of A.

**Comment by Xeverous** [comment]
No matter how many interfaces/states there are, A has flexible implementation and will adjust accordingly to any detail. Meanwhile B can get quickly out of control as every extra interface/state grows the number of stored elements exponentially.

**Comment by djowel** [comment]
An example of A is `basic_button` and an example of B is `layered_button`. Here's a bit of historical trivia... Initially, there was only `layered_button`. `basic_button` was added later precisely because of the issue you raised. Essentially, I already thought of what you are saying now. It's interesting though that you are coming to the same conclusion.

**Comment by djowel** [comment]
> An example of A is `basic_button` and an example of B is `layered_button`. Here's a bit of historical trivia... Initially, there was only `layered_button`. `basic_button` was added later precisely because of the issue you raised. Essentially, I already thought of what you are saying now. It's interesting though that you are coming to the same conclusion.

Notice how `basic_toggle_button` and friends are templated with the Base that defaults to `layered_button`:

https://github.com/cycfi/elements/blob/master/lib/include/elements/element/button.hpp#L97

guess why it is a template ;-) ?

**Comment by Xeverous** [comment]
Everything makes sense now. So `tab` inheritance tree should be modified similarly.

**Comment by Xeverous** [comment]
Could you enlighted me then what should be the inheritance hierarchy for the tab element? Should `basic_choice` expect only 1 element?

**Comment by djowel** [comment]
> Could you enlighted me then what should be the inheritance hierarchy for the tab element? Should `basic_choice` expect only 1 element?

One or two, depending on what you use as base class. `basic_choice` should be a template like `basic_toggle_button` and I think it should just use the ctor of the base using `basic_latching_button<Base>::basic_latching_button;` (likewise for `basic_toggle_button` and friends).

I should have done it that way with the `tabs`, `radio_button` and `check_box`. I must admit, sometimes I forget about these things. Well `check_box` predates `basic_button`, but the not the other buttons.

One might think why do we still need `layered_button`. Well it is still needed to allow image based buttons, for example. But on the other hand, the sliders and knobs use a sprite/state based implementation, which can also work well for image(sprite) based buttons. All this is evolution in progress interacting with my finite forgetful mind, dealing with many OSS libraries in addition to paid work. So, thank you for making me remind myself. Bottom line: `layered_button`can and should probably be extinct.

**Comment by Xeverous** [comment]
After 718af8410aa6a4084356bfb42d96f1c7e0afcdcf most is fixed but 2 factories still remain:

```
$ grep -rn -C 7 "<false" lib/include/
lib/include/elements/element/gallery/icon_button.hpp-63-   inline basic_toggle_button<> toggle_icon_button(
lib/include/elements/element/gallery/icon_button.hpp-64-      uint32_t code
lib/include/elements/element/gallery/icon_button.hpp-65-    , float size
lib/include/elements/element/gallery/icon_button.hpp-66-    , color body_color = get_theme().default_button_color
lib/include/elements/element/gallery/icon_button.hpp-67-   )
lib/include/elements/element/gallery/icon_button.hpp-68-   {
lib/include/elements/element/gallery/icon_button.hpp-69-      return {
lib/include/elements/element/gallery/icon_button.hpp:70:         icon_button_element<false>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-71-       , icon_button_element<true>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-72-      };
lib/include/elements/element/gallery/icon_button.hpp-73-   }
lib/include/elements/element/gallery/icon_button.hpp-74-
lib/include/elements/element/gallery/icon_button.hpp-75-   inline basic_toggle_button<> toggle_icon_button(
lib/include/elements/element/gallery/icon_button.hpp-76-      uint32_t code1
lib/include/elements/element/gallery/icon_button.hpp-77-    , uint32_t code2
--
lib/include/elements/element/gallery/icon_button.hpp-88-   inline layered_button icon_button(
lib/include/elements/element/gallery/icon_button.hpp-89-      uint32_t code
lib/include/elements/element/gallery/icon_button.hpp-90-    , float size
lib/include/elements/element/gallery/icon_button.hpp-91-    , color body_color = get_theme().default_button_color
lib/include/elements/element/gallery/icon_button.hpp-92-   )
lib/include/elements/element/gallery/icon_button.hpp-93-   {
lib/include/elements/element/gallery/icon_button.hpp-94-      return {
lib/include/elements/element/gallery/icon_button.hpp:95:         icon_button_element<false>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-96-       , icon_button_element<true>{ code, size, body_color }
lib/include/elements/element/gallery/icon_button.hpp-97-      };
lib/include/elements/element/gallery/icon_button.hpp-98-   }
lib/include/elements/element/gallery/icon_button.hpp-99-}}
lib/include/elements/element/gallery/icon_button.hpp-100-
lib/include/elements/element/gallery/icon_button.hpp-101-#endif
```

**Comment by djowel** [comment]
This should be "fixed" now. Closing...
