### ISSUE TITLE
CMake problems are back: ELEMENTS_HOST_UI_LIBRARY

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#91]
I have identified multiple problems with recent changes to support different host UI libraries

```
lib/include/elements/base_view.hpp:298:53: error: expected ')' before 'h'
  298 |                         base_view(host_window_handle h);
      |                                  ~                  ^~
      |                                                     )
lib/include/elements/base_view.hpp:318:7: error: 'host_view_handle' does not name a type
  318 |       host_view_handle  host() const { return _view; }
      |       ^~~~~~~~~~~~~~~~
```

**Please, if you ever do any #ifdef stuff without a fallback always add an meaningful `#else #error`.** This saves a ton of time for people who contribute and get the error like the above - the first thing I was searching were syntax/include errors but it's actually an `#ifdef` problem here:

https://github.com/cycfi/elements/blob/b5606c713f24c8c92fd9b47fe0045db1ec3f0660/lib/include/elements/base_view.hpp#L280-L288

In my case, none of these was defined causing missing type definitions.

___

None of these are guuaranteed to work for descendant projects:

https://github.com/cycfi/elements/blob/b5606c713f24c8c92fd9b47fe0045db1ec3f0660/CMakeLists.txt#L40-L55

cmake.org/cmake/help/v3.17/command/add_definitions.html - directory-affecting (or directory-poisoning) commands are superseeded in modern CMake. Worse, they do not work at all for elements-descendant projects that do not put elements in their subdirectory.

These should be replaced with `target_` commands with `PUBLIC` properties (not private because they are present in public headers). I will make a PR.

**Comment by djowel** [comment]
You should be the cmake police :-) Form now on, I won't merge cmake related PRs without your review :-) Can we fix this?

**Comment by Xeverous** [comment]
Yes, this is easily fixable. Already working on it.

**Comment by Xeverous** [comment]
Do you mind changing `HOST_UI_LIBRARY` to `ELEMENTS_HOST_UI_LIBRARY`? For consistency and tidiness when building projects using multiple libraries.

**Comment by Xeverous** [comment]
See #92

**Comment by djowel** [comment]
> Do you mind changing `HOST_UI_LIBRARY` to `ELEMENTS_HOST_UI_LIBRARY`? For consistency and tidiness when building projects using multiple libraries.

Please do. It makes more sense.
