### ISSUE TITLE
app::app should not take const char**

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#93]
Welcome to (one of the most unintuitive) type system corner cases. It is illegal to convert `T**` to `const T**`

The following code fails:

```cpp
#include <elements/app.hpp>

int main(int argc, char** argv)
{
    cycfi::elements::app app(argc, argv); // invalid convertion for argv
}
```

https://stackoverflow.com/questions/48560778/intermediate-pointers-in-cast-must-be-const-qualified-why

http://c-faq.com/ansi/constmismatch.html

Current implementations of app:

- Windows: both parameters ignored
- MacOS: both parameters ignored
- Linux: `g_application_run(G_APPLICATION(_app), argc, const_cast<char**>(argv))`

IMO the `const_cast` speaks for itself.

**Comment by djowel** [comment]
Good catch! Feel free to issue a PR for this.

**Comment by Xeverous** [comment]
Great. Can you review the PR (#92) for #91? I also need help with #23.

**Comment by Xeverous** [comment]
See #94

**Comment by Xeverous** [comment]
PR merged, closing.
