### ISSUE TITLE
minimum widget size limiter factory function

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#96]
The problem: I want to have a grid of labels and input boxes like the following (`#` means writeable area):

```
+-----------------------------------------+----------------+
| path to foo                             | ############## |
+-----------------------------------------+----------------+
| path to bar                             | ############## |
+-----------------------------------------+----------------+
| very long path description to something | ############## |
+-----------------------------------------+----------------+
```

There are 2 possible approaches:

1) tile columns

```cpp
htile(
	vtile(
		align_middle(align_left(label("path to foo"))),
		align_middle(align_left(label("path to bar"))),
		align_middle(align_left(label("very long path description to something")))
	),
	vtile(
		input_box().first,
		input_box().first,
		input_box().first
	)
)
```

2) tile rows

```cpp
vtile(
	htile(
		align_middle(align_left(label("path to foo"))),
		input_box().first,
	),
	htile(
		align_middle(align_left(label("path to bar"))),
		input_box().first,
	),
	htile(
		align_middle(align_left(label("very long path description to something"))),
		input_box().first,
	)
)
```
___

1) has the problem that if I stretch the window horizontally, labels also stretch (`_` means wasted space that I would like to be given to input boxes):

```
+------------------------------------------------+------------------------+
| path to foo                             ______ | ###################### |
+------------------------------------------------+------------------------+
| path to bar                             ______ | ###################### |
+------------------------------------------------+------------------------+
| very long path description to something ______ | ###################### |
+------------------------------------------------+------------------------+
```

2) has the problem that input boxes are not the same size which IMO looks ugly:

```
+-----------------------------------------+----------------+
| path to foo | ########################################## |
+-----------------------------------------+----------------+
| path to bar | ########################################## |
+-----------------------------------------+----------------+
| very long path description to something | ############## |
+-----------------------------------------+----------------+
```

___

I have no idea how to fix 2) but 1) could be easily fixed by changing behavior of labels so that they do not stretch and always occupy minimal required space.

For 1) we can implement factories which will override this behavior - very similar to existing v/hmin_size but without an explicit paramater - the factory should adapt to actually minimal required size of the provided widget.

```cpp
template <typename Subject>
auto hmin_required_size(Subject&& subject);

template <typename Subject>
auto vmin_required_size(Subject&& subject);

template <typename Subject>
auto min_required_size(Subject&& subject);
```

**Comment by djowel** [comment]
BTW, have you tried not using horizontal aligns at all? The horizontal aligns make the label infinitely resizable in the x plane. By default, labels are not resizable. Try this:

vtile(
   align_middle(label("path to foo")),
   align_middle(label("path to bar")),
   align_middle(label("very long path description to something"))
)

**Comment by Xeverous** [comment]
I did this and now have 2 problems:

- Label text is not left-aligned, it is centered horizontally
- For some (unknown) reason I can not resize the window horizontally (I get this problem often - we need a documentation which widgets block such behavior)

**Comment by djowel** [comment]
The latter can happen if the size is fixed (i.e. min limits == max limits), so you need some kind of springy things somewhere. Yes, this "limits" thing needs to be documented.

Why is the label centered?

**Comment by Xeverous** [comment]
> Why is the label centered?

Isn't this default behavior? Or is the default wrong? If I `vtile` just multiple `label()`s the text is vertically top aligned and horizontally centered.

**Comment by djowel** [comment]
> Isn't this default behavior? Or is the default wrong? If I `vtile` just multiple `label()`s the text is vertically top aligned and horizontally centered.

Hrmmm... Right labels are centered. We need to improve the API.

**Comment by djowel** [comment]
> > Isn't this default behavior? Or is the default wrong? If I `vtile` just multiple `label()`s the text is vertically top aligned and horizontally centered.
> 
> Hrmmm... Right labels are centered. We need to improve the API.

Oh, there is label_with_text_align! https://github.com/cycfi/elements/blob/master/lib/include/elements/element/misc.hpp#L217

**Comment by djowel** [comment]
> Oh, there is label_with_text_align! https://github.com/cycfi/elements/blob/master/lib/include/elements/element/misc.hpp#L217

It seems it's untested though, so it's a new addition. The code is probably wrong and should be fixed: https://github.com/cycfi/elements/blob/master/lib/src/element/misc.cpp#L45

**Comment by Xeverous** [comment]
FYI: you can make pretty multi-line code references: https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet

**Comment by djowel** [comment]
Here: https://github.com/cycfi/elements/blob/master/lib/src/element/misc.cpp#L50-L53

I'll need to adjust the drawing point cx, cy depending on alignment. Currently it is set to draw the text in the middle only. I'll need to add a test and adjust the code. Should be easy.

**Comment by djowel** [comment]
I did it in develop. Check this out:

<img width="513" alt="Screen Shot 2020-05-04 at 5 44 39 AM" src="https://user-images.githubusercontent.com/568094/80926631-fdd92c80-8dca-11ea-9ec3-a2e58d1d04fd.png">

The labels are aligned correctly within a vtile. Cool, eh :-) And the entire vtile can still be aligned as a group:

https://github.com/cycfi/elements/blob/develop/examples/text_and_icons/main.cpp#L112-L123

**Comment by Xeverous** [comment]
Now I have different issues (build on eb7af7f809426fea70905ba24e9021446ade6a07):

- some specific group of widgets is preventing the window from resizing horizontally (removing them removes the problem)
- If I remove this group, then actually nothing in the window stretches. Resizing the window only makes more unused background space.
- `label("text").text_align(canvas::left | canvas::middle)` - only `left` works, the text is aligned veritcally to the top - but I think it's the issue with the labels because they occupy minimal required space and therefore the text has no actual range to move vertically. `align_middle(label("text").text_align(canvas::left))` spreads the labels, and then `align_middle(label("text").text_align(canvas::left | canvas::middle))` fixes the problem.

Honestly, at this point I have lost any sense how/when widgets stretch and why. Labels are working now but I have no idea how to make *specific* widgets stretch. Either nothing stretches, everything stretches, or I can not resize the window.

**Comment by djowel** [comment]
Can you post a *minimal* example I can try?

Also, have you seen this yet? https://cycfi.github.io/elements/layout

**Comment by djowel** [comment]
Oh one more thing. I suggest starting out with the example code here: https://github.com/cycfi/elements/blob/develop/examples/text_and_icons/main.cpp 
where the labels are clearly working correctly, I am sure you can try to figure out what's going on. You are smart and you should be able to figure it out ;-) Reading up on the layout docs should also help.

**Comment by djowel** [comment]
> Can you post a _minimal_ example I can try?

OK, scrap that. I think it's better if I make the example. I think I see what you mean now by trying out multiple text entries and labels. I'll need to implement some more to get this done right.

**Comment by djowel** [comment]
OK, this is an important use-case, so I needed to do this right. I think now that we are doing it wrong. I think the label and the input box should be together, not separated in columns. The tricky part was how to align the labels horizontally when they are in separate rows. Each row does not know the alignment of other rows. 

The solution is to use grids. Grids are just like tiles, but you have better control of the positions (now using fractional positions). The grid data itself is external, so, each row can share the same grid positions. For example, this grid:

```c++
float const grid[] = { 0.3, 1.0 };`
```

allows you to position elements at 0.3 of the total width.

So, now, I changed the grid system to use fractional positions and modified the TextAndIcons example to use grids. Here's the result:

<img width="487" alt="Screen Shot 2020-05-05 at 10 38 44 AM" src="https://user-images.githubusercontent.com/568094/81031305-694ff680-8ebe-11ea-926a-75add3c090fd.png">

Check out the code: https://github.com/cycfi/elements/blob/develop/examples/text_and_icons/main.cpp#L86-L113

**Comment by Xeverous** [comment]
> Also, have you seen this yet? https://cycfi.github.io/elements/layout

lol no, there is no way to reach this page from the documentation

**Comment by djowel** [comment]
> lol no, there is no way to reach this page from the documentation

Because it's not published yet. And you do not have twitter where I post stuff in advance. It will soon be published. I'm working hard on the docs, so don't ever think I am ignoring you.

**Comment by Xeverous** [comment]
> `{ { 100, 100 }, { 0, full_extent } }; // Fixed width, flexible height`

Typo? Here max < min.

**Comment by djowel** [comment]
OK, I really need to take a rest. Cya!

**Comment by Xeverous** [comment]
> The grid’s minimum vertical limit is computed as the minimum of the children elements’ minimum vertical limits.
> The grid’s maximum vertical limit is computed as the maximum of the children elements’ maximum vertical limits.

These should probably be:

> The grid’s minimum vertical limit is computed as the **maximum** of the children elements’ minimum vertical limits.
> The grid’s maximum vertical limit is computed as the **minimum** of the children elements’ maximum vertical limits.

**Comment by Xeverous** [comment]
Same typos in semantics of horizontal and vertical tiles, and layer.

___

> The `layer_composite` is basically a `std::vector<element_ptr>` that the client uses to manage the composite’s elements. The lifetime of the container, `c`, is the client’s responsibility. You use `layer_composite` just as you would a `std::vector`

It would be good to mention that the composite itself is also an element and while it has vector's interface it can also be put into `share()` or another element factory function.

> The Deck is very similar to layers. Elements are placed in the z-axis. But unlike layers, only the top-most element is active.

I would change this to "only selected element is active (top-most by default)".

**Comment by Xeverous** [comment]
Another: vstretch and hstretch are documented to take `view_stretch` but they actually take floats.

**Comment by Xeverous** [comment]
I looked into the example and understand how the grid now works, however this still is not what I want. The grid in the example splits available space 30:70, but I want x:1-x where x is the minimum required for the first column.

I got an idea and turns out that it is the simplest and cleanest possible solution: just put a column into `hstretch(0.0, ...)`! Apparently my inital intuition (`no_stretch` element) was very accurate. Since align factories already have premade functions for values `0.0`, `0.5`, `1.0`, how about adding a premade stretch functions with `0.0`?

**Comment by Xeverous** [comment]
Since the no-stretch issue is completely resolved for me, I attempted to bisect the hierarchy in order to find what is sometimes causing the entire hierarchy to be unstretchable (that is, every element occupying minimum required space).

```cpp
auto make_widgets()
{
	return group("path settings", margin({10, 10, 10, 10}, htile(
		vtile(
			align_middle(label("path to the template").text_align(canvas::left | canvas::middle)),
			align_middle(label("output directory").text_align(canvas::left | canvas::middle)),
			align_middle(label("name scheme of generated files").text_align(canvas::left | canvas::middle))
		),
		vtile(
			input_box().first,
			input_box().first,
			input_box().first
		),
		hstretch(0.0, vtile(
			button("browse..."),
			button("browse..."),
			align_left(label("reset"))
		))
	)));
}
```

Turns out this stretches (only horizontally):

```cpp
view.content(
	make_widgets(),
	box(background_color)
);
```

but this does not:

```cpp
view.content(
	vscroller(make_widgets()),
	box(background_color)
);
```

Somehow the `vscroller` is suddently making the enclosed hierarchy to occupy minimum required horizontal space, even though it is intended for veritcal scrolling only. Is this a bug?

**Comment by djowel** [comment]
> I got an idea and turns out that it is the simplest and cleanest possible solution: just put a column into `hstretch(0.0, ...)`! Apparently my inital intuition (`no_stretch` element) was very accurate. Since align factories already have premade functions for values `0.0`, `0.5`, `1.0`, how about adding a premade stretch functions with `0.0`?

Sure, that would be good.  `no_stretch`, `no_vstretch` and `no_hstretch`? Feel free to do a PR.

**Comment by djowel** [comment]
> Somehow the `vscroller` is suddently making the enclosed hierarchy to occupy minimum required horizontal space, even though it is intended for veritcal scrolling only. Is this a bug?

I'm not sure. hard to tell... Could you turn that into a minimal code that exhibits the same behavior, following the documented layout semantics?

**Comment by djowel** [comment]
Your doc related have been incorporated in my latest edits. Many thanks! You have very sharp eyes!

**Comment by Xeverous** [comment]
I actually work in validation...

The example code I pasted is minimal. Just put it into empty example into the view's content.

**Comment by djowel** [comment]
> The example code I pasted is minimal. Just put it into empty example into the view's content.

No, I mean, to understand it better, it is always best to have the most minimal code possible that exhibits the suspected behavior bug. That is what I always do when trying to understand some complex behavior. The less components possible, the better.

**Comment by Xeverous** [comment]
Ah ok, then I will try to minimize it.

**Comment by djowel** [comment]
> Ah ok, then I will try to minimize it.

Actually, I should have a system of tests done this way. There's the concept of emergent behavior, that although you design the behavior using very basic principles (as I try to capture in the layout docs), sometimes, the behavior becomes unintuitive, and starts to have a life of its own as you compose more complex structures. Of course, most of the time, it's just a bug :-)

**Comment by djowel** [comment]
> Ah ok, then I will try to minimize it.

Much appreciated!

**Comment by Xeverous** [comment]
```cpp
#include <elements.hpp>

using namespace cycfi::elements;

int main(int argc, char* argv[])
{
   app _app(argc, argv);
   window _win(_app.name());
   _win.on_close = [&_app]() { _app.stop(); };
   view view_(_win);

   view_.content(
      vscroller(htile(
         label("output directory"),
         button("browse...")
      )),
      box(rgba(35, 35, 37, 255))
   );

   _app.run();
}
```

Remove `vscroller` and the button is stretchable, keep it and everything will be on its minimum horizontal size.

**Comment by djowel** [comment]
> ```c++
> ```c++
> #include <elements.hpp>
> 
> using namespace cycfi::elements;
> 
> int main(int argc, char* argv[])
> {
>    app _app(argc, argv);
>    window _win(_app.name());
>    _win.on_close = [&_app]() { _app.stop(); };
>    view view_(_win);
> 
>    view_.content(
>       vscroller(htile(
>          label("output directory"),
>          button("browse...")
>       )),
>       box(rgba(35, 35, 37, 255))
>    );
> 
>    _app.run();
> }
> ```
> 
> 
> Remove vscroller and the button is stretchable, keep it and everything will be on its minimum horizontal size.
> ```

Ah that is expected behavior. The scrollers, V or H or both, require a fixed-sized element, otherwise, there is no way to compute the scroll positions. You'd want to give it a fixed size that is larger than the actual window size.

**Comment by Xeverous** [comment]
Hmm, this is problematic then. I thought of vertically scrollable pseudo-table that can be resized horizontally. I get why it needs a fixed size element, but why does it fix it at the minimum instead of possible maximum?

**Comment by djowel** [comment]
> why does it fix it at the minimum instead of possible maximum?

because the maximum is typically full_extents which is VERY BIG. Just give it an arbitrarily large size, but not too large that it becomes hard for the user to handle scrolling. Try different values and you'll see what I mean.

**Comment by djowel** [comment]
You give a good point about V scrolling only where the H is still resizable though. I'll think about this...

**Comment by Xeverous** [comment]
Yeah, that's what I mean. A single-axis scroller should not impact stretching in the opposite axis. The second axis should be left intact.

**Comment by djowel** [comment]
> Yeah, that's what I mean. A single-axis scroller should not impact stretching in the opposite axis. The second axis should be left intact.

Just like the web browser. Add an issue and I'll place it in my task queue with a high priority.

**Comment by djowel** [comment]
Haha. so it turns out that it is easy to implement :-)  No need to make an issue. I'll push asap.

**Comment by djowel** [comment]
> Haha. so it turns out that it is easy to implement :-) No need to make an issue. I'll push asap.

Done.

**Comment by Xeverous** [comment]
You named the commit 31109f5ae1f9808af144d2b1002c9841bf3a6a14 "Allow horizontal resizing of vertical scrollables". Does it means that the opposite (veritcal resizing of horizontal scrollables) is not possible?

**Comment by djowel** [comment]
> You named the commit [31109f5](https://github.com/cycfi/elements/commit/31109f5ae1f9808af144d2b1002c9841bf3a6a14) "Allow horizontal resizing of vertical scrollables". Does it mean that the opposite (veritcal resizing of horizontal scrollables) is not possible?

patience ;-)

**Comment by Xeverous** [comment]
no stretch factories: #105

**Comment by djowel** [comment]
> > You named the commit [31109f5](https://github.com/cycfi/elements/commit/31109f5ae1f9808af144d2b1002c9841bf3a6a14) "Allow horizontal resizing of vertical scrollables". Does it mean that the opposite (veritcal resizing of horizontal scrollables) is not possible?
> 
> patience ;-)

Done.

**Comment by Xeverous** [comment]
At this point all of the problems mentioned here are fixed

- labels always are fixed-size but offer internal text alignment on the canvas
- scrollers do not modify resizing behavior of the opposite axis
- no-strech is in the API
