### ISSUE TITLE
text_alignment

### ISSUE THREAD

**Issue by Xeverous** [cycfi/elements#97]
Found it while trying to align tabs:

https://github.com/cycfi/elements/blob/c7d7952becc8e5bd86430451058b2b8cbe0866f4/lib/include/elements/support/canvas.hpp#L133-L145

I think you probably meant:

```cpp
    middle   = 16,       // Align text vertically to middle. 
    bottom   = 32        // Align text vertically to bottom. 
```

I wrote `canvas_.text_align(canvas_.center | canvas_.middle);` in the implementation of tabs and got some broken result with text outside enclosing widget.

**Comment by djowel** [comment]
No, that should be correct `top`, `middle` and `bottom` cannot mix. Do you have some code I can try? Oh BTW, take note that center will place the **center** of the text at the drawing point! Which can potentially draw outside your bounds.

Have a look at this (artist) test results:

https://cycfi.github.io/artist/assets/images/typography.png

and test code:

https://github.com/cycfi/artist/blob/master/test/main.cpp#L378

**Comment by Xeverous** [comment]
> Do you have some code I can try?

652e32e. But now, after your information I think I just centered the text at the wrong point (top left corner instead of the center of the box).

**Comment by Xeverous** [comment]
Labels work now as intended. A combination of my mistakes and/or recent label changes. This is no longer relevant, closing.
